import { ApiError } from "../core/api-error.js";
import type { ApiPromise } from "../core/api-promise.js";
import type { RequestOptions } from "../core/api-request.js";
import { noneAuth } from "../core/auth/schemes.js";
import type { FileInput } from "../core/binary.js";
import type { RawClient } from "../core/raw-client.js";
import { uuid } from "../core/uuid.js";
import * as s from "../core/validation/index.js";
import { uploadTypeSchema, type UploadType } from "../models/upload-type.js";
import {
  uploadsAbortMultipartJsonRequestSchema,
  type UploadsAbortMultipartJsonRequest,
} from "../models/uploads-abort-multipart-json-request.js";
import {
  uploadsAbortMultipartJsonResponseSchema,
  type UploadsAbortMultipartJsonResponse,
} from "../models/uploads-abort-multipart-json-response.js";
import {
  uploadsBatchPresignMultipartPartsJsonRequestSchema,
  type UploadsBatchPresignMultipartPartsJsonRequest,
} from "../models/uploads-batch-presign-multipart-parts-json-request.js";
import {
  uploadsBatchPresignMultipartPartsJsonResponseSchema,
  type UploadsBatchPresignMultipartPartsJsonResponse,
} from "../models/uploads-batch-presign-multipart-parts-json-response.js";
import {
  uploadsCompleteExternalUploadJsonRequestSchema,
  type UploadsCompleteExternalUploadJsonRequest,
} from "../models/uploads-complete-external-upload-json-request.js";
import {
  uploadsCompleteExternalUploadJsonResponseSchema,
  type UploadsCompleteExternalUploadJsonResponse,
} from "../models/uploads-complete-external-upload-json-response.js";
import {
  uploadsCompleteMultipartJsonRequestSchema,
  type UploadsCompleteMultipartJsonRequest,
} from "../models/uploads-complete-multipart-json-request.js";
import {
  uploadsCompleteMultipartJsonResponseSchema,
  type UploadsCompleteMultipartJsonResponse,
} from "../models/uploads-complete-multipart-json-response.js";
import {
  uploadsCreateMultipartJsonRequestSchema,
  type UploadsCreateMultipartJsonRequest,
} from "../models/uploads-create-multipart-json-request.js";
import {
  uploadsCreateMultipartJsonResponseSchema,
  type UploadsCreateMultipartJsonResponse,
} from "../models/uploads-create-multipart-json-response.js";
import {
  uploadsGeneratePresignedPutJsonRequestSchema,
  type UploadsGeneratePresignedPutJsonRequest,
} from "../models/uploads-generate-presigned-put-json-request.js";
import {
  uploadsGeneratePresignedPutJsonResponseSchema,
  type UploadsGeneratePresignedPutJsonResponse,
} from "../models/uploads-generate-presigned-put-json-response.js";
import { uploadsJsonResponseSchema, type UploadsJsonResponse } from "../models/uploads-json-response.js";
import type { Servers } from "../servers.js";

export class Uploads {
  readonly #rawClient: RawClient;
  readonly #servers: Servers;

  constructor(rawClient: RawClient, servers: Servers) {
    this.#rawClient = rawClient;
    this.#servers = servers;
  }

  /**
   * Abort multipart upload
   *
   * @remarks
   * This endpoint aborts the multipart upload initiated with /create-multipart. This should be used
   * when cancelling the upload. It does not matter if parts were already uploaded into the external
   * storage provider.
   *
   * You must have the correct permissions and CORS settings configured in your external provider.
   * We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must be set to true for
   * this endpoint to function.
   *
   * @returns external upload initialized
   *
   * @throws {@link ApiError} when the API answers with an error status
   *
   * @throws {@link DiscourseError} when no usable response was produced: a connection failure, a
   * timeout, a body that would not decode, a value that would not encode, or a credential that
   * could not be obtained
   */
  abortMultipart(
    request: Uploads.AbortMultipartRequest,
    options?: RequestOptions,
  ): ApiPromise<UploadsAbortMultipartJsonResponse, ApiError> {
    return this.#rawClient.execute(
      {
        method: "POST",
        urlTemplate: this.#servers.default("/uploads/abort-multipart.json"),
        auth: noneAuth,
        pathParams: [],
        query: [],
        headers: [{ name: "Idempotency-Key", value: uuid(), schema: s.string() }],
        body: {
          kind: "json",
          value: request.body,
          schema: s.optional(s.lazy(() => uploadsAbortMultipartJsonRequestSchema)),
        },
      },
      {
        success: { kind: "json", schema: uploadsAbortMultipartJsonResponseSchema },
        errorFactory: ApiError,
      },
      options,
    );
  }

  /**
   * Generates batches of presigned URLs for multipart parts
   *
   * @remarks
   * Multipart uploads are uploaded in chunks or parts to individual presigned URLs, similar to the
   * one generated by /generate-presigned-put. The part numbers provided must be between 1 and
   * 10000. The total number of parts will depend on the chunk size in bytes that you intend to use
   * to upload each chunk. For example a 12MB file may have 2 5MB chunks and a final 2MB chunk, for
   * part numbers 1, 2, and 3.
   *
   * This endpoint will return a presigned URL for each part number provided, which you can then use
   * to send PUT requests for the binary chunk corresponding to that part. When the part is
   * uploaded, the provider should return an ETag for the part, and this should be stored along with
   * the part number, because this is needed to complete the multipart upload.
   *
   * You must have the correct permissions and CORS settings configured in your external provider.
   * We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must be set to true for
   * this endpoint to function.
   *
   * @returns external upload initialized
   *
   * @throws {@link ApiError} when the API answers with an error status
   *
   * @throws {@link DiscourseError} when no usable response was produced: a connection failure, a
   * timeout, a body that would not decode, a value that would not encode, or a credential that
   * could not be obtained
   */
  batchPresignMultipartParts(
    request: Uploads.BatchPresignMultipartPartsRequest,
    options?: RequestOptions,
  ): ApiPromise<UploadsBatchPresignMultipartPartsJsonResponse, ApiError> {
    return this.#rawClient.execute(
      {
        method: "POST",
        urlTemplate: this.#servers.default("/uploads/batch-presign-multipart-parts.json"),
        auth: noneAuth,
        pathParams: [],
        query: [],
        headers: [{ name: "Idempotency-Key", value: uuid(), schema: s.string() }],
        body: {
          kind: "json",
          value: request.body,
          schema: s.optional(s.lazy(() => uploadsBatchPresignMultipartPartsJsonRequestSchema)),
        },
      },
      {
        success: { kind: "json", schema: uploadsBatchPresignMultipartPartsJsonResponseSchema },
        errorFactory: ApiError,
      },
      options,
    );
  }

  /**
   * Completes a direct external upload
   *
   * @remarks
   * Completes an external upload initialized with /get-presigned-put. The file will be moved from
   * its temporary location in external storage to a final destination in the S3 bucket. An Upload
   * record will also be created in the database in most cases.
   *
   * If a sha1-checksum was provided in the initial request it will also be compared with the
   * uploaded file in storage to make sure the same file was uploaded. The file size will be
   * compared for the same reason.
   *
   * You must have the correct permissions and CORS settings configured in your external provider.
   * We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must be set to true for
   * this endpoint to function.
   *
   * @returns external upload initialized
   *
   * @throws {@link ApiError} when the API answers with an error status
   *
   * @throws {@link DiscourseError} when no usable response was produced: a connection failure, a
   * timeout, a body that would not decode, a value that would not encode, or a credential that
   * could not be obtained
   */
  completeExternalUpload(
    request: Uploads.CompleteExternalUploadRequest,
    options?: RequestOptions,
  ): ApiPromise<UploadsCompleteExternalUploadJsonResponse, ApiError> {
    return this.#rawClient.execute(
      {
        method: "POST",
        urlTemplate: this.#servers.default("/uploads/complete-external-upload.json"),
        auth: noneAuth,
        pathParams: [],
        query: [],
        headers: [{ name: "Idempotency-Key", value: uuid(), schema: s.string() }],
        body: {
          kind: "json",
          value: request.body,
          schema: s.optional(s.lazy(() => uploadsCompleteExternalUploadJsonRequestSchema)),
        },
      },
      {
        success: { kind: "json", schema: uploadsCompleteExternalUploadJsonResponseSchema },
        errorFactory: ApiError,
      },
      options,
    );
  }

  /**
   * Complete multipart upload
   *
   * @remarks
   * Completes the multipart upload in the external store, and copies the file from its temporary
   * location to its final location in the store. All of the parts must have been uploaded to the
   * external storage provider. An Upload record will be completed in most cases once the file is
   * copied to its final location.
   *
   * You must have the correct permissions and CORS settings configured in your external provider.
   * We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must be set to true for
   * this endpoint to function.
   *
   * @returns external upload initialized
   *
   * @throws {@link ApiError} when the API answers with an error status
   *
   * @throws {@link DiscourseError} when no usable response was produced: a connection failure, a
   * timeout, a body that would not decode, a value that would not encode, or a credential that
   * could not be obtained
   */
  completeMultipart(
    request: Uploads.CompleteMultipartRequest,
    options?: RequestOptions,
  ): ApiPromise<UploadsCompleteMultipartJsonResponse, ApiError> {
    return this.#rawClient.execute(
      {
        method: "POST",
        urlTemplate: this.#servers.default("/uploads/complete-multipart.json"),
        auth: noneAuth,
        pathParams: [],
        query: [],
        headers: [{ name: "Idempotency-Key", value: uuid(), schema: s.string() }],
        body: {
          kind: "json",
          value: request.body,
          schema: s.optional(s.lazy(() => uploadsCompleteMultipartJsonRequestSchema)),
        },
      },
      {
        success: { kind: "json", schema: uploadsCompleteMultipartJsonResponseSchema },
        errorFactory: ApiError,
      },
      options,
    );
  }

  /**
   * Creates a multipart external upload
   *
   * @remarks
   * Creates a multipart upload in the external storage provider, storing a temporary reference to
   * the external upload similar to /get-presigned-put.
   *
   * You must have the correct permissions and CORS settings configured in your external provider.
   * We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must be set to true for
   * this endpoint to function.
   *
   * @returns external upload initialized
   *
   * @throws {@link ApiError} when the API answers with an error status
   *
   * @throws {@link DiscourseError} when no usable response was produced: a connection failure, a
   * timeout, a body that would not decode, a value that would not encode, or a credential that
   * could not be obtained
   */
  createMultipartUpload(
    request: Uploads.CreateMultipartUploadRequest,
    options?: RequestOptions,
  ): ApiPromise<UploadsCreateMultipartJsonResponse, ApiError> {
    return this.#rawClient.execute(
      {
        method: "POST",
        urlTemplate: this.#servers.default("/uploads/create-multipart.json"),
        auth: noneAuth,
        pathParams: [],
        query: [],
        headers: [{ name: "Idempotency-Key", value: uuid(), schema: s.string() }],
        body: {
          kind: "json",
          value: request.body,
          schema: s.optional(s.lazy(() => uploadsCreateMultipartJsonRequestSchema)),
        },
      },
      {
        success: { kind: "json", schema: uploadsCreateMultipartJsonResponseSchema },
        errorFactory: ApiError,
      },
      options,
    );
  }

  /**
   * Creates an upload
   *
   * @returns file uploaded
   *
   * @throws {@link ApiError} when the API answers with an error status
   *
   * @throws {@link DiscourseError} when no usable response was produced: a connection failure, a
   * timeout, a body that would not decode, a value that would not encode, or a credential that
   * could not be obtained
   */
  createUpload(
    request: Uploads.CreateUploadRequest,
    options?: RequestOptions,
  ): ApiPromise<UploadsJsonResponse, ApiError> {
    return this.#rawClient.execute(
      {
        method: "POST",
        urlTemplate: this.#servers.default("/uploads.json"),
        auth: noneAuth,
        pathParams: [],
        query: [],
        headers: [{ name: "Idempotency-Key", value: uuid(), schema: s.string() }],
        body: {
          kind: "multipart",
          value: [
            { kind: "text", name: "upload_type", value: request.uploadType, schema: uploadTypeSchema },
            { kind: "text", name: "user_id", value: request.userId, schema: s.optional(s.int()) },
            {
              kind: "text",
              name: "synchronous",
              value: request.synchronous,
              schema: s.optional(s.boolean()),
            },
            { kind: "file", name: "file", value: request.file },
          ],
        },
      },
      {
        success: { kind: "json", schema: uploadsJsonResponseSchema },
        errorFactory: ApiError,
      },
      options,
    );
  }

  /**
   * Initiates a direct external upload
   *
   * @remarks
   * Direct external uploads bypass the usual method of creating uploads via the POST /uploads
   * route, and upload directly to an external provider, which by default is S3. This route begins
   * the process, and will return a unique identifier for the external upload as well as a presigned
   * URL which is where the file binary blob should be uploaded to.
   *
   * Once the upload is complete to the external service, you must call the POST
   * /complete-external-upload route using the unique identifier returned by this route, which will
   * create any required Upload record in the Discourse database and also move file from its
   * temporary location to the final destination in the external storage service.
   *
   * You must have the correct permissions and CORS settings configured in your external provider.
   * We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must be set to true for
   * this endpoint to function.
   *
   * @returns external upload initialized
   *
   * @throws {@link ApiError} when the API answers with an error status
   *
   * @throws {@link DiscourseError} when no usable response was produced: a connection failure, a
   * timeout, a body that would not decode, a value that would not encode, or a credential that
   * could not be obtained
   */
  generatePresignedPut(
    request: Uploads.GeneratePresignedPutRequest,
    options?: RequestOptions,
  ): ApiPromise<UploadsGeneratePresignedPutJsonResponse, ApiError> {
    return this.#rawClient.execute(
      {
        method: "POST",
        urlTemplate: this.#servers.default("/uploads/generate-presigned-put.json"),
        auth: noneAuth,
        pathParams: [],
        query: [],
        headers: [{ name: "Idempotency-Key", value: uuid(), schema: s.string() }],
        body: {
          kind: "json",
          value: request.body,
          schema: s.optional(s.lazy(() => uploadsGeneratePresignedPutJsonRequestSchema)),
        },
      },
      {
        success: { kind: "json", schema: uploadsGeneratePresignedPutJsonResponseSchema },
        errorFactory: ApiError,
      },
      options,
    );
  }
}

export namespace Uploads {
  export type AbortMultipartRequest = {
    body?: UploadsAbortMultipartJsonRequest;
  };

  export type BatchPresignMultipartPartsRequest = {
    body?: UploadsBatchPresignMultipartPartsJsonRequest;
  };

  export type CompleteExternalUploadRequest = {
    body?: UploadsCompleteExternalUploadJsonRequest;
  };

  export type CompleteMultipartRequest = {
    body?: UploadsCompleteMultipartJsonRequest;
  };

  export type CreateMultipartUploadRequest = {
    body?: UploadsCreateMultipartJsonRequest;
  };

  export type CreateUploadRequest = {
    uploadType: UploadType;
    /** required if uploading an avatar */
    userId?: number;
    /** Use this flag to return an id and url */
    synchronous?: boolean;
    file?: FileInput;
  };

  export type GeneratePresignedPutRequest = {
    body?: UploadsGeneratePresignedPutJsonRequest;
  };
}
