/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AdminBackupsJsonRequest,
  adminBackupsJsonRequestSchema,
} from '../models/adminBackupsJsonRequest.js';
import {
  AdminBackupsJsonResponse,
  adminBackupsJsonResponseSchema,
} from '../models/adminBackupsJsonResponse.js';
import {
  AdminBackupsJsonResponse1,
  adminBackupsJsonResponse1Schema,
} from '../models/adminBackupsJsonResponse1.js';
import { array, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class BackupsApi extends BaseApi {
  /**
   * @return Response from the API call
   */
  async getBackups(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminBackupsJsonResponse[]>> {
    const req = this.createRequest('GET', '/admin/backups.json');
    return req.callAsJson(
      array(adminBackupsJsonResponseSchema),
      requestOptions
    );
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createBackup(
    body?: AdminBackupsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminBackupsJsonResponse1>> {
    const req = this.createRequest('POST', '/admin/backups.json');
    const mapped = req.prepareArgs({
      body: [body, optional(adminBackupsJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(adminBackupsJsonResponse1Schema, requestOptions);
  }

  /**
   * @param filename
   * @return Response from the API call
   */
  async sendDownloadBackupEmail(
    filename: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({ filename: [filename, string()] });
    req.appendTemplatePath`/admin/backups/${mapped.filename}`;
    return req.call(requestOptions);
  }

  /**
   * @param filename
   * @param token
   * @return Response from the API call
   */
  async downloadBackup(
    filename: string,
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      filename: [filename, string()],
      token: [token, string()],
    });
    req.query('token', mapped.token);
    req.appendTemplatePath`/admin/backups/${mapped.filename}`;
    return req.call(requestOptions);
  }
}
