/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AdminBadgesJsonRequest,
  adminBadgesJsonRequestSchema,
} from '../models/adminBadgesJsonRequest.js';
import {
  AdminBadgesJsonRequest1,
  adminBadgesJsonRequest1Schema,
} from '../models/adminBadgesJsonRequest1.js';
import {
  AdminBadgesJsonResponse,
  adminBadgesJsonResponseSchema,
} from '../models/adminBadgesJsonResponse.js';
import {
  AdminBadgesJsonResponse1,
  adminBadgesJsonResponse1Schema,
} from '../models/adminBadgesJsonResponse1.js';
import {
  AdminBadgesJsonResponse2,
  adminBadgesJsonResponse2Schema,
} from '../models/adminBadgesJsonResponse2.js';
import {
  UserBadgesJsonResponse,
  userBadgesJsonResponseSchema,
} from '../models/userBadgesJsonResponse.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class BadgesApi extends BaseApi {
  /**
   * @return Response from the API call
   */
  async adminListBadges(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminBadgesJsonResponse>> {
    const req = this.createRequest('GET', '/admin/badges.json');
    return req.callAsJson(adminBadgesJsonResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createBadge(
    body?: AdminBadgesJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminBadgesJsonResponse1>> {
    const req = this.createRequest('POST', '/admin/badges.json');
    const mapped = req.prepareArgs({
      body: [body, optional(adminBadgesJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(adminBadgesJsonResponse1Schema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateBadge(
    id: number,
    body?: AdminBadgesJsonRequest1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminBadgesJsonResponse2>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(adminBadgesJsonRequest1Schema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/admin/badges/${mapped.id}.json`;
    return req.callAsJson(adminBadgesJsonResponse2Schema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async deleteBadge(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/admin/badges/${mapped.id}.json`;
    return req.call(requestOptions);
  }

  /**
   * @param username
   * @return Response from the API call
   */
  async listUserBadges(
    username: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UserBadgesJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ username: [username, string()] });
    req.appendTemplatePath`/user-badges/${mapped.username}.json`;
    return req.callAsJson(userBadgesJsonResponseSchema, requestOptions);
  }
}
