/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CategoriesJsonRequest,
  categoriesJsonRequestSchema,
} from '../models/categoriesJsonRequest.js';
import {
  CategoriesJsonRequest1,
  categoriesJsonRequest1Schema,
} from '../models/categoriesJsonRequest1.js';
import {
  CategoriesJsonResponse,
  categoriesJsonResponseSchema,
} from '../models/categoriesJsonResponse.js';
import {
  CategoriesJsonResponse1,
  categoriesJsonResponse1Schema,
} from '../models/categoriesJsonResponse1.js';
import {
  CategoriesJsonResponse2,
  categoriesJsonResponse2Schema,
} from '../models/categoriesJsonResponse2.js';
import { CJsonResponse, cJsonResponseSchema } from '../models/cJsonResponse.js';
import {
  CShowJsonResponse,
  cShowJsonResponseSchema,
} from '../models/cShowJsonResponse.js';
import { boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class CategoriesApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async createCategory(
    body?: CategoriesJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CategoriesJsonResponse>> {
    const req = this.createRequest('POST', '/categories.json');
    const mapped = req.prepareArgs({
      body: [body, optional(categoriesJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(categoriesJsonResponseSchema, requestOptions);
  }

  /**
   * @param includeSubcategories
   * @return Response from the API call
   */
  async listCategories(
    includeSubcategories?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CategoriesJsonResponse1>> {
    const req = this.createRequest('GET', '/categories.json');
    const mapped = req.prepareArgs({
      includeSubcategories: [includeSubcategories, optional(boolean())],
    });
    req.query('include_subcategories', mapped.includeSubcategories);
    return req.callAsJson(categoriesJsonResponse1Schema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateCategory(
    id: number,
    body?: CategoriesJsonRequest1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CategoriesJsonResponse2>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(categoriesJsonRequest1Schema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/categories/${mapped.id}.json`;
    return req.callAsJson(categoriesJsonResponse2Schema, requestOptions);
  }

  /**
   * @param slug
   * @param id
   * @return Response from the API call
   */
  async listCategoryTopics(
    slug: string,
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      slug: [slug, string()],
      id: [id, number()],
    });
    req.appendTemplatePath`/c/${mapped.slug}/${mapped.id}.json`;
    return req.callAsJson(cJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async getCategory(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CShowJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/c/${mapped.id}/show.json`;
    return req.callAsJson(cShowJsonResponseSchema, requestOptions);
  }
}
