/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DiscoursePostEventEventsJsonResponse,
  discoursePostEventEventsJsonResponseSchema,
} from '../models/discoursePostEventEventsJsonResponse.js';
import {
  IncludeDetails,
  includeDetailsSchema,
} from '../models/includeDetails.js';
import {
  IncludeSubcategories,
  includeSubcategoriesSchema,
} from '../models/includeSubcategories.js';
import { Order, orderSchema } from '../models/order.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class DiscourseCalendarEventsApi extends BaseApi {
  /**
   * @param includeDetails        Include detailed event information (creator, invitees, stats,
   *                                                      etc.)
   * @param categoryId            Filter events by category ID
   * @param includeSubcategories  Include events from subcategories when filtering by
   *                                                      category
   * @param postId                Filter to events associated with a specific post ID
   * @param attendingUser         Filter to events where the specified user (username) has
   *                                                      RSVP'd as going
   * @param before                Return events starting before this date/time (ISO 8601
   *                                                      format)
   * @param after                 Return events starting after this date/time (ISO 8601
   *                                                      format)
   * @param order                 Sort order for events by start date (default: asc)
   * @param limit                 Maximum number of events to return (default: 200)
   * @return Response from the API call
   */
  async listEvents(
    includeDetails?: IncludeDetails,
    categoryId?: number,
    includeSubcategories?: IncludeSubcategories,
    postId?: number,
    attendingUser?: string,
    before?: string,
    after?: string,
    order?: Order,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DiscoursePostEventEventsJsonResponse>> {
    const req = this.createRequest('GET', '/discourse-post-event/events.json');
    const mapped = req.prepareArgs({
      includeDetails: [includeDetails, optional(includeDetailsSchema)],
      categoryId: [categoryId, optional(number())],
      includeSubcategories: [
        includeSubcategories,
        optional(includeSubcategoriesSchema),
      ],
      postId: [postId, optional(number())],
      attendingUser: [attendingUser, optional(string())],
      before: [before, optional(string())],
      after: [after, optional(string())],
      order: [order, optional(orderSchema)],
      limit: [limit, optional(number())],
    });
    req.query('include_details', mapped.includeDetails);
    req.query('category_id', mapped.categoryId);
    req.query('include_subcategories', mapped.includeSubcategories);
    req.query('post_id', mapped.postId);
    req.query('attending_user', mapped.attendingUser);
    req.query('before', mapped.before);
    req.query('after', mapped.after);
    req.query('order', mapped.order);
    req.query('limit', mapped.limit);
    return req.callAsJson(
      discoursePostEventEventsJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * @param categoryId            Filter events by category ID
   * @param includeSubcategories  Include events from subcategories when filtering by
   *                                                      category
   * @param attendingUser         Filter to events where the specified user (username) has
   *                                                      RSVP'd as going
   * @param before                Return events starting before this date/time (ISO 8601
   *                                                      format)
   * @param after                 Return events starting after this date/time (ISO 8601
   *                                                      format)
   * @param order                 Sort order for events by start date (default: asc)
   * @param limit                 Maximum number of events to return (default: 200)
   * @return Response from the API call
   */
  async exportEventsIcs(
    categoryId?: number,
    includeSubcategories?: IncludeSubcategories,
    attendingUser?: string,
    before?: string,
    after?: string,
    order?: Order,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('GET', '/discourse-post-event/events.ics');
    const mapped = req.prepareArgs({
      categoryId: [categoryId, optional(number())],
      includeSubcategories: [
        includeSubcategories,
        optional(includeSubcategoriesSchema),
      ],
      attendingUser: [attendingUser, optional(string())],
      before: [before, optional(string())],
      after: [after, optional(string())],
      order: [order, optional(orderSchema)],
      limit: [limit, optional(number())],
    });
    req.query('category_id', mapped.categoryId);
    req.query('include_subcategories', mapped.includeSubcategories);
    req.query('attending_user', mapped.attendingUser);
    req.query('before', mapped.before);
    req.query('after', mapped.after);
    req.query('order', mapped.order);
    req.query('limit', mapped.limit);
    return req.callAsStream(requestOptions);
  }
}
