/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AdminGroupsJsonRequest,
  adminGroupsJsonRequestSchema,
} from '../models/adminGroupsJsonRequest.js';
import {
  AdminGroupsJsonResponse,
  adminGroupsJsonResponseSchema,
} from '../models/adminGroupsJsonResponse.js';
import {
  AdminGroupsJsonResponse1,
  adminGroupsJsonResponse1Schema,
} from '../models/adminGroupsJsonResponse1.js';
import {
  GroupsByIdJsonResponse,
  groupsByIdJsonResponseSchema,
} from '../models/groupsByIdJsonResponse.js';
import {
  GroupsJsonRequest,
  groupsJsonRequestSchema,
} from '../models/groupsJsonRequest.js';
import {
  GroupsJsonResponse,
  groupsJsonResponseSchema,
} from '../models/groupsJsonResponse.js';
import {
  GroupsJsonResponse1,
  groupsJsonResponse1Schema,
} from '../models/groupsJsonResponse1.js';
import {
  GroupsJsonResponse2,
  groupsJsonResponse2Schema,
} from '../models/groupsJsonResponse2.js';
import {
  GroupsMembersJsonRequest,
  groupsMembersJsonRequestSchema,
} from '../models/groupsMembersJsonRequest.js';
import {
  GroupsMembersJsonResponse,
  groupsMembersJsonResponseSchema,
} from '../models/groupsMembersJsonResponse.js';
import {
  GroupsMembersJsonResponse1,
  groupsMembersJsonResponse1Schema,
} from '../models/groupsMembersJsonResponse1.js';
import {
  GroupsMembersJsonResponse2,
  groupsMembersJsonResponse2Schema,
} from '../models/groupsMembersJsonResponse2.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class GroupsApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async createGroup(
    body?: AdminGroupsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminGroupsJsonResponse>> {
    const req = this.createRequest('POST', '/admin/groups.json');
    const mapped = req.prepareArgs({
      body: [body, optional(adminGroupsJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(adminGroupsJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async deleteGroup(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminGroupsJsonResponse1>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/admin/groups/${mapped.id}.json`;
    return req.callAsJson(adminGroupsJsonResponse1Schema, requestOptions);
  }

  /**
   * @param name Use group name instead of id
   * @return Response from the API call
   */
  async getGroup(
    name: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupsJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ name: [name, string()] });
    req.appendTemplatePath`/groups/${mapped.name}.json`;
    return req.callAsJson(groupsJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateGroup(
    id: number,
    body?: GroupsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupsJsonResponse1>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(groupsJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/groups/${mapped.id}.json`;
    return req.callAsJson(groupsJsonResponse1Schema, requestOptions);
  }

  /**
   * @param id Use group name instead of id
   * @return Response from the API call
   */
  async getGroupById(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupsByIdJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/groups/by-id/${mapped.id}.json`;
    return req.callAsJson(groupsByIdJsonResponseSchema, requestOptions);
  }

  /**
   * @param name Use group name instead of id
   * @return Response from the API call
   */
  async listGroupMembers(
    name: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupsMembersJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ name: [name, string()] });
    req.appendTemplatePath`/groups/${mapped.name}/members.json`;
    return req.callAsJson(groupsMembersJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async addGroupMembers(
    id: number,
    body?: GroupsMembersJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupsMembersJsonResponse1>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(groupsMembersJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/groups/${mapped.id}/members.json`;
    return req.callAsJson(groupsMembersJsonResponse1Schema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async removeGroupMembers(
    id: number,
    body?: GroupsMembersJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupsMembersJsonResponse2>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(groupsMembersJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/groups/${mapped.id}/members.json`;
    return req.callAsJson(groupsMembersJsonResponse2Schema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async listGroups(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupsJsonResponse2>> {
    const req = this.createRequest('GET', '/groups.json');
    return req.callAsJson(groupsJsonResponse2Schema, requestOptions);
  }
}
