/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  InvitesCreateMultipleJsonRequest,
  invitesCreateMultipleJsonRequestSchema,
} from '../models/invitesCreateMultipleJsonRequest.js';
import {
  InvitesCreateMultipleJsonResponse,
  invitesCreateMultipleJsonResponseSchema,
} from '../models/invitesCreateMultipleJsonResponse.js';
import {
  InvitesJsonRequest,
  invitesJsonRequestSchema,
} from '../models/invitesJsonRequest.js';
import {
  InvitesJsonResponse,
  invitesJsonResponseSchema,
} from '../models/invitesJsonResponse.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class InvitesApi extends BaseApi {
  /**
   * @param apiKey
   * @param apiUsername
   * @param body
   * @return Response from the API call
   */
  async createInvite(
    apiKey: string,
    apiUsername: string,
    body?: InvitesJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvitesJsonResponse>> {
    const req = this.createRequest('POST', '/invites.json');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      body: [body, optional(invitesJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(invitesJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param body
   * @return Response from the API call
   */
  async createMultipleInvites(
    apiKey: string,
    apiUsername: string,
    body?: InvitesCreateMultipleJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvitesCreateMultipleJsonResponse>> {
    const req = this.createRequest('POST', '/invites/create-multiple.json');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      body: [body, optional(invitesCreateMultipleJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      invitesCreateMultipleJsonResponseSchema,
      requestOptions
    );
  }
}
