/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  NotificationsJsonResponse,
  notificationsJsonResponseSchema,
} from '../models/notificationsJsonResponse.js';
import {
  NotificationsMarkReadJsonRequest,
  notificationsMarkReadJsonRequestSchema,
} from '../models/notificationsMarkReadJsonRequest.js';
import {
  NotificationsMarkReadJsonResponse,
  notificationsMarkReadJsonResponseSchema,
} from '../models/notificationsMarkReadJsonResponse.js';
import { optional } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class NotificationsApi extends BaseApi {
  /**
   * @return Response from the API call
   */
  async getNotifications(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NotificationsJsonResponse>> {
    const req = this.createRequest('GET', '/notifications.json');
    return req.callAsJson(notificationsJsonResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async markNotificationsAsRead(
    body?: NotificationsMarkReadJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NotificationsMarkReadJsonResponse>> {
    const req = this.createRequest('PUT', '/notifications/mark-read.json');
    const mapped = req.prepareArgs({
      body: [body, optional(notificationsMarkReadJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      notificationsMarkReadJsonResponseSchema,
      requestOptions
    );
  }
}
