/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  PostActionsJsonRequest,
  postActionsJsonRequestSchema,
} from '../models/postActionsJsonRequest.js';
import {
  PostActionsJsonResponse,
  postActionsJsonResponseSchema,
} from '../models/postActionsJsonResponse.js';
import {
  PostsJsonRequest,
  postsJsonRequestSchema,
} from '../models/postsJsonRequest.js';
import {
  PostsJsonRequest1,
  postsJsonRequest1Schema,
} from '../models/postsJsonRequest1.js';
import {
  PostsJsonRequest2,
  postsJsonRequest2Schema,
} from '../models/postsJsonRequest2.js';
import {
  PostsJsonResponse,
  postsJsonResponseSchema,
} from '../models/postsJsonResponse.js';
import {
  PostsJsonResponse1,
  postsJsonResponse1Schema,
} from '../models/postsJsonResponse1.js';
import {
  PostsJsonResponse2,
  postsJsonResponse2Schema,
} from '../models/postsJsonResponse2.js';
import {
  PostsJsonResponse3,
  postsJsonResponse3Schema,
} from '../models/postsJsonResponse3.js';
import {
  PostsLockedJsonRequest,
  postsLockedJsonRequestSchema,
} from '../models/postsLockedJsonRequest.js';
import {
  PostsLockedJsonResponse,
  postsLockedJsonResponseSchema,
} from '../models/postsLockedJsonResponse.js';
import {
  PostsRepliesJsonResponse,
  postsRepliesJsonResponseSchema,
} from '../models/postsRepliesJsonResponse.js';
import { array, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PostsApi extends BaseApi {
  /**
   * @param before Load posts with an id lower than this value. Useful for pagination.
   * @return Response from the API call
   */
  async listPosts(
    before?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PostsJsonResponse>> {
    const req = this.createRequest('GET', '/posts.json');
    const mapped = req.prepareArgs({ before: [before, optional(number())] });
    req.query('before', mapped.before);
    return req.callAsJson(postsJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param body
   * @return Response from the API call
   */
  async createTopicPostPm(
    apiKey: string,
    apiUsername: string,
    body?: PostsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PostsJsonResponse1>> {
    const req = this.createRequest('POST', '/posts.json');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      body: [body, optional(postsJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(postsJsonResponse1Schema, requestOptions);
  }

  /**
   * This endpoint can be used to get the number of likes on a post using the
   * `actions_summary` property in the response. `actions_summary` responses
   * with the id of `2` signify a `like`. If there are no `actions_summary`
   * items with the id of `2`, that means there are 0 likes. Other ids likely
   * refer to various different flag types.
   *
   *
   * @param id
   * @return Response from the API call
   */
  async getPost(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PostsJsonResponse2>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/posts/${mapped.id}.json`;
    return req.callAsJson(postsJsonResponse2Schema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updatePost(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: PostsJsonRequest1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PostsJsonResponse3>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(postsJsonRequest1Schema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/posts/${mapped.id}.json`;
    return req.callAsJson(postsJsonResponse3Schema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async deletePost(
    apiKey: string,
    apiUsername: string,
    id: number,
    body?: PostsJsonRequest2,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, number()],
      body: [body, optional(postsJsonRequest2Schema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/posts/${mapped.id}.json`;
    return req.call(requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async postReplies(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PostsRepliesJsonResponse[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/posts/${mapped.id}/replies.json`;
    return req.callAsJson(
      array(postsRepliesJsonResponseSchema),
      requestOptions
    );
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async lockPost(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: PostsLockedJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PostsLockedJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(postsLockedJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/posts/${mapped.id}/locked.json`;
    return req.callAsJson(postsLockedJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param body
   * @return Response from the API call
   */
  async performPostAction(
    apiKey: string,
    apiUsername: string,
    body?: PostActionsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PostActionsJsonResponse>> {
    const req = this.createRequest('POST', '/post_actions.json');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      body: [body, optional(postActionsJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(postActionsJsonResponseSchema, requestOptions);
  }
}
