/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  TopicsPrivateMessagesJsonResponse,
  topicsPrivateMessagesJsonResponseSchema,
} from '../models/topicsPrivateMessagesJsonResponse.js';
import {
  TopicsPrivateMessagesSentJsonResponse,
  topicsPrivateMessagesSentJsonResponseSchema,
} from '../models/topicsPrivateMessagesSentJsonResponse.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PrivateMessagesApi extends BaseApi {
  /**
   * @param username
   * @return Response from the API call
   */
  async listUserPrivateMessages(
    username: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TopicsPrivateMessagesJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ username: [username, string()] });
    req.appendTemplatePath`/topics/private-messages/${mapped.username}.json`;
    return req.callAsJson(
      topicsPrivateMessagesJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * @param username
   * @return Response from the API call
   */
  async getUserSentPrivateMessages(
    username: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TopicsPrivateMessagesSentJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ username: [username, string()] });
    req.appendTemplatePath`/topics/private-messages-sent/${mapped.username}.json`;
    return req.callAsJson(
      topicsPrivateMessagesSentJsonResponseSchema,
      requestOptions
    );
  }
}
