/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SearchJsonResponse,
  searchJsonResponseSchema,
} from '../models/searchJsonResponse.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class SearchApi extends BaseApi {
  /**
   * @param q    The query string needs to be url encoded and is made up of the following options: - Search
   *                       term. This is just a string. Usually it would be the first item in the query. -
   *                       `@<username>`: Use the `@` followed by the username to specify posts by this user. -
   *                       `#<category>`: Use the `#` followed by the category slug to search within this category. -
   *                       `tags:`: `api,solved` or for posts that have all the specified tags `api+solved`. - `before:
   *                       `: `yyyy-mm-dd` - `after:`: `yyyy-mm-dd` - `order:`: `latest`, `likes`, `views`,
   *                       `latest_topic` - `assigned:`: username (without `@`) - `in:`: `title`, `likes`, `personal`,
   *                       `messages`, `seen`, `unseen`, `posted`, `created`, `watching`, `tracking`, `bookmarks`,
   *                       `assigned`, `unassigned`, `first`, `pinned`, `wiki` - `with:`: `images` - `status:`: `open`,
   *                       `closed`, `public`, `archived`, `noreplies`, `single_user`, `solved`, `unsolved` - `group:`:
   *                       group_name or group_id - `group_messages:`: group_name or group_id - `min_posts:`: 1 -
   *                       `max_posts:`: 10 - `min_views:`: 1 - `max_views:`: 10  If you are using cURL you can use the
   *                       `-G` and the `--data-urlencode` flags to encode the query:  ``` curl -i -sS -X GET -G "http:
   *                       //localhost:3000/search.json" \ --data-urlencode 'q=wordpress @scossar #fun after:2020-01-
   *                       01' ```
   * @param page
   * @return Response from the API call
   */
  async search(
    q?: string,
    page?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SearchJsonResponse>> {
    const req = this.createRequest('GET', '/search.json');
    const mapped = req.prepareArgs({
      q: [q, optional(string())],
      page: [page, optional(number())],
    });
    req.query('q', mapped.q);
    req.query('page', mapped.page);
    return req.callAsJson(searchJsonResponseSchema, requestOptions);
  }
}
