/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SiteBasicInfoJsonResponse,
  siteBasicInfoJsonResponseSchema,
} from '../models/siteBasicInfoJsonResponse.js';
import {
  SiteJsonResponse,
  siteJsonResponseSchema,
} from '../models/siteJsonResponse.js';
import { BaseApi } from './baseApi.js';

export class SiteApi extends BaseApi {
  /**
   * Can be used to fetch all categories and subcategories
   *
   * @return Response from the API call
   */
  async getSite(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SiteJsonResponse>> {
    const req = this.createRequest('GET', '/site.json');
    return req.callAsJson(siteJsonResponseSchema, requestOptions);
  }

  /**
   * Can be used to fetch basic info about a site
   *
   * @return Response from the API call
   */
  async getSiteBasicInfo(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SiteBasicInfoJsonResponse>> {
    const req = this.createRequest('GET', '/site/basic-info.json');
    return req.callAsJson(siteBasicInfoJsonResponseSchema, requestOptions);
  }
}
