/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  TagGroupsJsonRequest,
  tagGroupsJsonRequestSchema,
} from '../models/tagGroupsJsonRequest.js';
import {
  TagGroupsJsonRequest1,
  tagGroupsJsonRequest1Schema,
} from '../models/tagGroupsJsonRequest1.js';
import {
  TagGroupsJsonResponse,
  tagGroupsJsonResponseSchema,
} from '../models/tagGroupsJsonResponse.js';
import {
  TagGroupsJsonResponse1,
  tagGroupsJsonResponse1Schema,
} from '../models/tagGroupsJsonResponse1.js';
import {
  TagGroupsJsonResponse2,
  tagGroupsJsonResponse2Schema,
} from '../models/tagGroupsJsonResponse2.js';
import {
  TagGroupsJsonResponse3,
  tagGroupsJsonResponse3Schema,
} from '../models/tagGroupsJsonResponse3.js';
import {
  TagJsonResponse,
  tagJsonResponseSchema,
} from '../models/tagJsonResponse.js';
import {
  TagsJsonResponse,
  tagsJsonResponseSchema,
} from '../models/tagsJsonResponse.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class TagsApi extends BaseApi {
  /**
   * @return Response from the API call
   */
  async listTagGroups(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TagGroupsJsonResponse>> {
    const req = this.createRequest('GET', '/tag_groups.json');
    return req.callAsJson(tagGroupsJsonResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createTagGroup(
    body?: TagGroupsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TagGroupsJsonResponse1>> {
    const req = this.createRequest('POST', '/tag_groups.json');
    const mapped = req.prepareArgs({
      body: [body, optional(tagGroupsJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(tagGroupsJsonResponse1Schema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async getTagGroup(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TagGroupsJsonResponse2>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/tag_groups/${mapped.id}.json`;
    return req.callAsJson(tagGroupsJsonResponse2Schema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateTagGroup(
    id: string,
    body?: TagGroupsJsonRequest1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TagGroupsJsonResponse3>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(tagGroupsJsonRequest1Schema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/tag_groups/${mapped.id}.json`;
    return req.callAsJson(tagGroupsJsonResponse3Schema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async listTags(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TagsJsonResponse>> {
    const req = this.createRequest('GET', '/tags.json');
    return req.callAsJson(tagsJsonResponseSchema, requestOptions);
  }

  /**
   * @param name
   * @return Response from the API call
   */
  async getTag(
    name: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TagJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ name: [name, string()] });
    req.appendTemplatePath`/tag/${mapped.name}.json`;
    return req.callAsJson(tagJsonResponseSchema, requestOptions);
  }
}
