/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  LatestJsonResponse,
  latestJsonResponseSchema,
} from '../models/latestJsonResponse.js';
import {
  TChangeTimestampJsonRequest,
  tChangeTimestampJsonRequestSchema,
} from '../models/tChangeTimestampJsonRequest.js';
import {
  TChangeTimestampJsonResponse,
  tChangeTimestampJsonResponseSchema,
} from '../models/tChangeTimestampJsonResponse.js';
import {
  TInviteGroupJsonRequest,
  tInviteGroupJsonRequestSchema,
} from '../models/tInviteGroupJsonRequest.js';
import {
  TInviteGroupJsonResponse,
  tInviteGroupJsonResponseSchema,
} from '../models/tInviteGroupJsonResponse.js';
import {
  TInviteJsonRequest,
  tInviteJsonRequestSchema,
} from '../models/tInviteJsonRequest.js';
import {
  TInviteJsonResponse,
  tInviteJsonResponseSchema,
} from '../models/tInviteJsonResponse.js';
import { TJsonRequest, tJsonRequestSchema } from '../models/tJsonRequest.js';
import { TJsonResponse, tJsonResponseSchema } from '../models/tJsonResponse.js';
import {
  TJsonResponse1,
  tJsonResponse1Schema,
} from '../models/tJsonResponse1.js';
import {
  TNotificationsJsonRequest,
  tNotificationsJsonRequestSchema,
} from '../models/tNotificationsJsonRequest.js';
import {
  TNotificationsJsonResponse,
  tNotificationsJsonResponseSchema,
} from '../models/tNotificationsJsonResponse.js';
import {
  TopJsonResponse,
  topJsonResponseSchema,
} from '../models/topJsonResponse.js';
import {
  TPostsJsonResponse,
  tPostsJsonResponseSchema,
} from '../models/tPostsJsonResponse.js';
import {
  TStatusJsonRequest,
  tStatusJsonRequestSchema,
} from '../models/tStatusJsonRequest.js';
import {
  TStatusJsonResponse,
  tStatusJsonResponseSchema,
} from '../models/tStatusJsonResponse.js';
import {
  TTimerJsonRequest,
  tTimerJsonRequestSchema,
} from '../models/tTimerJsonRequest.js';
import {
  TTimerJsonResponse,
  tTimerJsonResponseSchema,
} from '../models/tTimerJsonResponse.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class TopicsApi extends BaseApi {
  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @return Response from the API call
   */
  async getSpecificPostsFromTopic(
    apiKey: string,
    apiUsername: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TPostsJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.appendTemplatePath`/t/${mapped.id}/posts.json`;
    return req.callAsJson(tPostsJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @return Response from the API call
   */
  async getTopic(
    apiKey: string,
    apiUsername: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.appendTemplatePath`/t/${mapped.id}.json`;
    return req.callAsJson(tJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @return Response from the API call
   */
  async removeTopic(
    apiKey: string,
    apiUsername: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.appendTemplatePath`/t/${mapped.id}.json`;
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateTopic(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: TJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TJsonResponse1>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(tJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/t/-/${mapped.id}.json`;
    return req.callAsJson(tJsonResponse1Schema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async inviteToTopic(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: TInviteJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TInviteJsonResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(tInviteJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/t/${mapped.id}/invite.json`;
    return req.callAsJson(tInviteJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async inviteGroupToTopic(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: TInviteGroupJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TInviteGroupJsonResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(tInviteGroupJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/t/${mapped.id}/invite-group.json`;
    return req.callAsJson(tInviteGroupJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @return Response from the API call
   */
  async bookmarkTopic(
    apiKey: string,
    apiUsername: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.appendTemplatePath`/t/${mapped.id}/bookmark.json`;
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateTopicStatus(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: TStatusJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TStatusJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(tStatusJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/t/${mapped.id}/status.json`;
    return req.callAsJson(tStatusJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param order        Enum: `default`, `created`, `activity`, `views`, `posts`, `category`, `likes`,
   *                               `op_likes`, `posters`
   * @param ascending    Defaults to `desc`, add `ascending=true` to sort asc
   * @param perPage      Maximum number of topics returned, between 1-100
   * @return Response from the API call
   */
  async listLatestTopics(
    apiKey: string,
    apiUsername: string,
    order?: string,
    ascending?: string,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LatestJsonResponse>> {
    const req = this.createRequest('GET', '/latest.json');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      order: [order, optional(string())],
      ascending: [ascending, optional(string())],
      perPage: [perPage, optional(number())],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.query('order', mapped.order);
    req.query('ascending', mapped.ascending);
    req.query('per_page', mapped.perPage);
    return req.callAsJson(latestJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param period       Enum: `all`, `yearly`, `quarterly`, `monthly`, `weekly`, `daily`
   * @param perPage      Maximum number of topics returned, between 1-100
   * @return Response from the API call
   */
  async listTopTopics(
    apiKey: string,
    apiUsername: string,
    period?: string,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TopJsonResponse>> {
    const req = this.createRequest('GET', '/top.json');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      period: [period, optional(string())],
      perPage: [perPage, optional(number())],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.query('period', mapped.period);
    req.query('per_page', mapped.perPage);
    return req.callAsJson(topJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async setNotificationLevel(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: TNotificationsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TNotificationsJsonResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(tNotificationsJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/t/${mapped.id}/notifications.json`;
    return req.callAsJson(tNotificationsJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateTopicTimestamp(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: TChangeTimestampJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TChangeTimestampJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(tChangeTimestampJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/t/${mapped.id}/change-timestamp.json`;
    return req.callAsJson(tChangeTimestampJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param id
   * @param body
   * @return Response from the API call
   */
  async createTopicTimer(
    apiKey: string,
    apiUsername: string,
    id: string,
    body?: TTimerJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TTimerJsonResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      id: [id, string()],
      body: [body, optional(tTimerJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/t/${mapped.id}/timer.json`;
    return req.callAsJson(tTimerJsonResponseSchema, requestOptions);
  }

  /**
   * @param externalId
   * @return Response from the API call
   */
  async getTopicByExternalId(
    externalId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ externalId: [externalId, string()] });
    req.appendTemplatePath`/t/external_id/${mapped.externalId}.json`;
    return req.call(requestOptions);
  }
}
