/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, FileWrapper, RequestOptions } from '../core.js';
import {
  UploadsAbortMultipartJsonRequest,
  uploadsAbortMultipartJsonRequestSchema,
} from '../models/uploadsAbortMultipartJsonRequest.js';
import {
  UploadsAbortMultipartJsonResponse,
  uploadsAbortMultipartJsonResponseSchema,
} from '../models/uploadsAbortMultipartJsonResponse.js';
import {
  UploadsBatchPresignMultipartPartsJsonRequest,
  uploadsBatchPresignMultipartPartsJsonRequestSchema,
} from '../models/uploadsBatchPresignMultipartPartsJsonRequest.js';
import {
  UploadsBatchPresignMultipartPartsJsonResponse,
  uploadsBatchPresignMultipartPartsJsonResponseSchema,
} from '../models/uploadsBatchPresignMultipartPartsJsonResponse.js';
import {
  UploadsCompleteExternalUploadJsonRequest,
  uploadsCompleteExternalUploadJsonRequestSchema,
} from '../models/uploadsCompleteExternalUploadJsonRequest.js';
import {
  UploadsCompleteExternalUploadJsonResponse,
  uploadsCompleteExternalUploadJsonResponseSchema,
} from '../models/uploadsCompleteExternalUploadJsonResponse.js';
import {
  UploadsCompleteMultipartJsonRequest,
  uploadsCompleteMultipartJsonRequestSchema,
} from '../models/uploadsCompleteMultipartJsonRequest.js';
import {
  UploadsCompleteMultipartJsonResponse,
  uploadsCompleteMultipartJsonResponseSchema,
} from '../models/uploadsCompleteMultipartJsonResponse.js';
import {
  UploadsCreateMultipartJsonRequest,
  uploadsCreateMultipartJsonRequestSchema,
} from '../models/uploadsCreateMultipartJsonRequest.js';
import {
  UploadsCreateMultipartJsonResponse,
  uploadsCreateMultipartJsonResponseSchema,
} from '../models/uploadsCreateMultipartJsonResponse.js';
import {
  UploadsGeneratePresignedPutJsonRequest,
  uploadsGeneratePresignedPutJsonRequestSchema,
} from '../models/uploadsGeneratePresignedPutJsonRequest.js';
import {
  UploadsGeneratePresignedPutJsonResponse,
  uploadsGeneratePresignedPutJsonResponseSchema,
} from '../models/uploadsGeneratePresignedPutJsonResponse.js';
import {
  UploadsJsonResponse,
  uploadsJsonResponseSchema,
} from '../models/uploadsJsonResponse.js';
import { UploadType, uploadTypeSchema } from '../models/uploadType.js';
import { boolean, number, optional } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class UploadsApi extends BaseApi {
  /**
   * @param uploadType
   * @param userId      required if uploading an avatar
   * @param synchronous Use this flag to return an id and url
   * @param file
   * @return Response from the API call
   */
  async createUpload(
    uploadType: UploadType,
    userId?: number,
    synchronous?: boolean,
    file?: FileWrapper,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UploadsJsonResponse>> {
    const req = this.createRequest('POST', '/uploads.json');
    const mapped = req.prepareArgs({
      uploadType: [uploadType, uploadTypeSchema],
      userId: [userId, optional(number())],
      synchronous: [synchronous, optional(boolean())],
    });
    req.formData({
      upload_type: mapped.uploadType,
      user_id: mapped.userId,
      synchronous: mapped.synchronous,
      file: file,
    });
    return req.callAsJson(uploadsJsonResponseSchema, requestOptions);
  }

  /**
   * Direct external uploads bypass the usual method of creating uploads
   * via the POST /uploads route, and upload directly to an external provider,
   * which by default is S3. This route begins the process, and will return
   * a unique identifier for the external upload as well as a presigned URL
   * which is where the file binary blob should be uploaded to.
   *
   * Once the upload is complete to the external service, you must call the
   * POST /complete-external-upload route using the unique identifier returned
   * by this route, which will create any required Upload record in the Discourse
   * database and also move file from its temporary location to the final
   * destination in the external storage service.
   *
   * You must have the correct permissions and CORS settings configured in your
   * external provider. We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must
   * be set to true for this endpoint to function.
   *
   *
   *
   * @param body
   * @return Response from the API call
   */
  async generatePresignedPut(
    body?: UploadsGeneratePresignedPutJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UploadsGeneratePresignedPutJsonResponse>> {
    const req = this.createRequest(
      'POST',
      '/uploads/generate-presigned-put.json'
    );
    const mapped = req.prepareArgs({
      body: [body, optional(uploadsGeneratePresignedPutJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      uploadsGeneratePresignedPutJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * Completes an external upload initialized with /get-presigned-put. The
   * file will be moved from its temporary location in external storage to
   * a final destination in the S3 bucket. An Upload record will also be
   * created in the database in most cases.
   *
   * If a sha1-checksum was provided in the initial request it will also
   * be compared with the uploaded file in storage to make sure the same
   * file was uploaded. The file size will be compared for the same reason.
   *
   * You must have the correct permissions and CORS settings configured in your
   * external provider. We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must
   * be set to true for this endpoint to function.
   *
   *
   *
   * @param body
   * @return Response from the API call
   */
  async completeExternalUpload(
    body?: UploadsCompleteExternalUploadJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UploadsCompleteExternalUploadJsonResponse>> {
    const req = this.createRequest(
      'POST',
      '/uploads/complete-external-upload.json'
    );
    const mapped = req.prepareArgs({
      body: [body, optional(uploadsCompleteExternalUploadJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      uploadsCompleteExternalUploadJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * Creates a multipart upload in the external storage provider, storing
   * a temporary reference to the external upload similar to /get-presigned-put.
   *
   * You must have the correct permissions and CORS settings configured in your
   * external provider. We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must
   * be set to true for this endpoint to function.
   *
   *
   *
   * @param body
   * @return Response from the API call
   */
  async createMultipartUpload(
    body?: UploadsCreateMultipartJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UploadsCreateMultipartJsonResponse>> {
    const req = this.createRequest('POST', '/uploads/create-multipart.json');
    const mapped = req.prepareArgs({
      body: [body, optional(uploadsCreateMultipartJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      uploadsCreateMultipartJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * Multipart uploads are uploaded in chunks or parts to individual presigned
   * URLs, similar to the one generated by /generate-presigned-put. The part
   * numbers provided must be between 1 and 10000. The total number of parts
   * will depend on the chunk size in bytes that you intend to use to upload
   * each chunk. For example a 12MB file may have 2 5MB chunks and a final
   * 2MB chunk, for part numbers 1, 2, and 3.
   *
   * This endpoint will return a presigned URL for each part number provided,
   * which you can then use to send PUT requests for the binary chunk corresponding
   * to that part. When the part is uploaded, the provider should return an
   * ETag for the part, and this should be stored along with the part number,
   * because this is needed to complete the multipart upload.
   *
   * You must have the correct permissions and CORS settings configured in your
   * external provider. We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must
   * be set to true for this endpoint to function.
   *
   *
   *
   * @param body
   * @return Response from the API call
   */
  async batchPresignMultipartParts(
    body?: UploadsBatchPresignMultipartPartsJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UploadsBatchPresignMultipartPartsJsonResponse>> {
    const req = this.createRequest(
      'POST',
      '/uploads/batch-presign-multipart-parts.json'
    );
    const mapped = req.prepareArgs({
      body: [
        body,
        optional(uploadsBatchPresignMultipartPartsJsonRequestSchema),
      ],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      uploadsBatchPresignMultipartPartsJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * This endpoint aborts the multipart upload initiated with /create-multipart.
   * This should be used when cancelling the upload. It does not matter if parts
   * were already uploaded into the external storage provider.
   *
   * You must have the correct permissions and CORS settings configured in your
   * external provider. We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must
   * be set to true for this endpoint to function.
   *
   *
   *
   * @param body
   * @return Response from the API call
   */
  async abortMultipart(
    body?: UploadsAbortMultipartJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UploadsAbortMultipartJsonResponse>> {
    const req = this.createRequest('POST', '/uploads/abort-multipart.json');
    const mapped = req.prepareArgs({
      body: [body, optional(uploadsAbortMultipartJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      uploadsAbortMultipartJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * Completes the multipart upload in the external store, and copies the
   * file from its temporary location to its final location in the store.
   * All of the parts must have been uploaded to the external storage provider.
   * An Upload record will be completed in most cases once the file is copied
   * to its final location.
   *
   * You must have the correct permissions and CORS settings configured in your
   * external provider. We support AWS S3 as the default. See:
   *
   * https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
   *
   * An external file store must be set up and `enable_direct_s3_uploads` must
   * be set to true for this endpoint to function.
   *
   *
   *
   * @param body
   * @return Response from the API call
   */
  async completeMultipart(
    body?: UploadsCompleteMultipartJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UploadsCompleteMultipartJsonResponse>> {
    const req = this.createRequest('POST', '/uploads/complete-multipart.json');
    const mapped = req.prepareArgs({
      body: [body, optional(uploadsCompleteMultipartJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      uploadsCompleteMultipartJsonResponseSchema,
      requestOptions
    );
  }
}
