/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AdminUsersActivateJsonResponse,
  adminUsersActivateJsonResponseSchema,
} from '../models/adminUsersActivateJsonResponse.js';
import {
  AdminUsersAnonymizeJsonResponse,
  adminUsersAnonymizeJsonResponseSchema,
} from '../models/adminUsersAnonymizeJsonResponse.js';
import {
  AdminUsersDeactivateJsonResponse,
  adminUsersDeactivateJsonResponseSchema,
} from '../models/adminUsersDeactivateJsonResponse.js';
import {
  AdminUsersJsonRequest,
  adminUsersJsonRequestSchema,
} from '../models/adminUsersJsonRequest.js';
import {
  AdminUsersJsonResponse,
  adminUsersJsonResponseSchema,
} from '../models/adminUsersJsonResponse.js';
import {
  AdminUsersJsonResponse1,
  adminUsersJsonResponse1Schema,
} from '../models/adminUsersJsonResponse1.js';
import {
  AdminUsersJsonResponse2,
  adminUsersJsonResponse2Schema,
} from '../models/adminUsersJsonResponse2.js';
import {
  AdminUsersListJsonResponse,
  adminUsersListJsonResponseSchema,
} from '../models/adminUsersListJsonResponse.js';
import {
  AdminUsersLogOutJsonResponse,
  adminUsersLogOutJsonResponseSchema,
} from '../models/adminUsersLogOutJsonResponse.js';
import {
  AdminUsersSilenceJsonRequest,
  adminUsersSilenceJsonRequestSchema,
} from '../models/adminUsersSilenceJsonRequest.js';
import {
  AdminUsersSilenceJsonResponse,
  adminUsersSilenceJsonResponseSchema,
} from '../models/adminUsersSilenceJsonResponse.js';
import {
  AdminUsersSuspendJsonRequest,
  adminUsersSuspendJsonRequestSchema,
} from '../models/adminUsersSuspendJsonRequest.js';
import {
  AdminUsersSuspendJsonResponse,
  adminUsersSuspendJsonResponseSchema,
} from '../models/adminUsersSuspendJsonResponse.js';
import { Asc, ascSchema } from '../models/asc.js';
import {
  DirectoryItemsJsonResponse,
  directoryItemsJsonResponseSchema,
} from '../models/directoryItemsJsonResponse.js';
import { Flag, flagSchema } from '../models/flag.js';
import { Order2, order2Schema } from '../models/order2.js';
import { Order3, order3Schema } from '../models/order3.js';
import { Period1, period1Schema } from '../models/period1.js';
import {
  SessionForgotPasswordJsonRequest,
  sessionForgotPasswordJsonRequestSchema,
} from '../models/sessionForgotPasswordJsonRequest.js';
import {
  SessionForgotPasswordJsonResponse,
  sessionForgotPasswordJsonResponseSchema,
} from '../models/sessionForgotPasswordJsonResponse.js';
import {
  UByExternalJsonResponse,
  uByExternalJsonResponseSchema,
} from '../models/uByExternalJsonResponse.js';
import {
  UEmailsJsonResponse,
  uEmailsJsonResponseSchema,
} from '../models/uEmailsJsonResponse.js';
import { UJsonRequest, uJsonRequestSchema } from '../models/uJsonRequest.js';
import { UJsonResponse, uJsonResponseSchema } from '../models/uJsonResponse.js';
import {
  UJsonResponse1,
  uJsonResponse1Schema,
} from '../models/uJsonResponse1.js';
import {
  UPreferencesAvatarPickJsonRequest,
  uPreferencesAvatarPickJsonRequestSchema,
} from '../models/uPreferencesAvatarPickJsonRequest.js';
import {
  UPreferencesAvatarPickJsonResponse,
  uPreferencesAvatarPickJsonResponseSchema,
} from '../models/uPreferencesAvatarPickJsonResponse.js';
import {
  UPreferencesEmailJsonRequest,
  uPreferencesEmailJsonRequestSchema,
} from '../models/uPreferencesEmailJsonRequest.js';
import {
  UPreferencesUsernameJsonRequest,
  uPreferencesUsernameJsonRequestSchema,
} from '../models/uPreferencesUsernameJsonRequest.js';
import {
  UserActionsJsonResponse,
  userActionsJsonResponseSchema,
} from '../models/userActionsJsonResponse.js';
import {
  UserAvatarRefreshGravatarJsonResponse,
  userAvatarRefreshGravatarJsonResponseSchema,
} from '../models/userAvatarRefreshGravatarJsonResponse.js';
import {
  UsersJsonRequest,
  usersJsonRequestSchema,
} from '../models/usersJsonRequest.js';
import {
  UsersJsonResponse,
  usersJsonResponseSchema,
} from '../models/usersJsonResponse.js';
import {
  UsersPasswordResetJsonRequest,
  usersPasswordResetJsonRequestSchema,
} from '../models/usersPasswordResetJsonRequest.js';
import { array, boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class UsersApi extends BaseApi {
  /**
   * @param apiKey
   * @param apiUsername
   * @param body
   * @return Response from the API call
   */
  async createUser(
    apiKey: string,
    apiUsername: string,
    body?: UsersJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersJsonResponse>> {
    const req = this.createRequest('POST', '/users.json');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      body: [body, optional(usersJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(usersJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param username
   * @return Response from the API call
   */
  async getUser(
    apiKey: string,
    apiUsername: string,
    username: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      username: [username, string()],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.appendTemplatePath`/u/${mapped.username}.json`;
    return req.callAsJson(uJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param username
   * @param body
   * @return Response from the API call
   */
  async updateUser(
    apiKey: string,
    apiUsername: string,
    username: string,
    body?: UJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UJsonResponse1>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      username: [username, string()],
      body: [body, optional(uJsonRequestSchema)],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/u/${mapped.username}.json`;
    return req.callAsJson(uJsonResponse1Schema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param externalId
   * @return Response from the API call
   */
  async getUserExternalId(
    apiKey: string,
    apiUsername: string,
    externalId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UByExternalJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      externalId: [externalId, string()],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.appendTemplatePath`/u/by-external/${mapped.externalId}.json`;
    return req.callAsJson(uByExternalJsonResponseSchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param apiUsername
   * @param provider     Authentication provider name. Can be found in the provider callback URL:
   *                               `/auth/{provider}/callback`
   * @param externalId
   * @return Response from the API call
   */
  async getUserIdentiyProviderExternalId(
    apiKey: string,
    apiUsername: string,
    provider: string,
    externalId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UByExternalJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      apiUsername: [apiUsername, string()],
      provider: [provider, string()],
      externalId: [externalId, string()],
    });
    req.header('Api-Key', mapped.apiKey);
    req.header('Api-Username', mapped.apiUsername);
    req.appendTemplatePath`/u/by-external/${mapped.provider}/${mapped.externalId}.json`;
    return req.callAsJson(uByExternalJsonResponseSchema, requestOptions);
  }

  /**
   * @param username
   * @param body
   * @return Response from the API call
   */
  async updateAvatar(
    username: string,
    body?: UPreferencesAvatarPickJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UPreferencesAvatarPickJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      username: [username, string()],
      body: [body, optional(uPreferencesAvatarPickJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/u/${mapped.username}/preferences/avatar/pick.json`;
    return req.callAsJson(
      uPreferencesAvatarPickJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * @param username
   * @param body
   * @return Response from the API call
   */
  async updateEmail(
    username: string,
    body?: UPreferencesEmailJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      username: [username, string()],
      body: [body, optional(uPreferencesEmailJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/u/${mapped.username}/preferences/email.json`;
    return req.call(requestOptions);
  }

  /**
   * @param username
   * @param body
   * @return Response from the API call
   */
  async updateUsername(
    username: string,
    body?: UPreferencesUsernameJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      username: [username, string()],
      body: [body, optional(uPreferencesUsernameJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/u/${mapped.username}/preferences/username.json`;
    return req.call(requestOptions);
  }

  /**
   * @param period
   * @param order
   * @param asc
   * @param page
   * @return Response from the API call
   */
  async listUsersPublic(
    period: Period1,
    order: Order2,
    asc?: Asc,
    page?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DirectoryItemsJsonResponse>> {
    const req = this.createRequest('GET', '/directory_items.json');
    const mapped = req.prepareArgs({
      period: [period, period1Schema],
      order: [order, order2Schema],
      asc: [asc, optional(ascSchema)],
      page: [page, optional(number())],
    });
    req.query('period', mapped.period);
    req.query('order', mapped.order);
    req.query('asc', mapped.asc);
    req.query('page', mapped.page);
    return req.callAsJson(directoryItemsJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async adminGetUser(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/admin/users/${mapped.id}.json`;
    return req.callAsJson(adminUsersJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async deleteUser(
    id: number,
    body?: AdminUsersJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersJsonResponse1>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(adminUsersJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/admin/users/${mapped.id}.json`;
    return req.callAsJson(adminUsersJsonResponse1Schema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async activateUser(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersActivateJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/admin/users/${mapped.id}/activate.json`;
    return req.callAsJson(adminUsersActivateJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async deactivateUser(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersDeactivateJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/admin/users/${mapped.id}/deactivate.json`;
    return req.callAsJson(
      adminUsersDeactivateJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async suspendUser(
    id: number,
    body?: AdminUsersSuspendJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersSuspendJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(adminUsersSuspendJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/admin/users/${mapped.id}/suspend.json`;
    return req.callAsJson(adminUsersSuspendJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async silenceUser(
    id: number,
    body?: AdminUsersSilenceJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersSilenceJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, optional(adminUsersSilenceJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/admin/users/${mapped.id}/silence.json`;
    return req.callAsJson(adminUsersSilenceJsonResponseSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async anonymizeUser(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersAnonymizeJsonResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/admin/users/${mapped.id}/anonymize.json`;
    return req.callAsJson(
      adminUsersAnonymizeJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async logOutUser(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersLogOutJsonResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/admin/users/${mapped.id}/log_out.json`;
    return req.callAsJson(adminUsersLogOutJsonResponseSchema, requestOptions);
  }

  /**
   * @param username
   * @return Response from the API call
   */
  async refreshGravatar(
    username: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UserAvatarRefreshGravatarJsonResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ username: [username, string()] });
    req.appendTemplatePath`/user_avatar/${mapped.username}/refresh_gravatar.json`;
    return req.callAsJson(
      userAvatarRefreshGravatarJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * @param order
   * @param asc
   * @param page
   * @param showEmails  Include user email addresses in response. These requests will be logged in the
   *                               staff action logs.
   * @param stats       Include user stats information
   * @param email       Filter to the user with this email address
   * @param ip          Filter to users with this IP address
   * @return Response from the API call
   */
  async adminListUsers(
    order?: Order3,
    asc?: Asc,
    page?: number,
    showEmails?: boolean,
    stats?: boolean,
    email?: string,
    ip?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersJsonResponse2[]>> {
    const req = this.createRequest('GET', '/admin/users.json');
    const mapped = req.prepareArgs({
      order: [order, optional(order3Schema)],
      asc: [asc, optional(ascSchema)],
      page: [page, optional(number())],
      showEmails: [showEmails, optional(boolean())],
      stats: [stats, optional(boolean())],
      email: [email, optional(string())],
      ip: [ip, optional(string())],
    });
    req.query('order', mapped.order);
    req.query('asc', mapped.asc);
    req.query('page', mapped.page);
    req.query('show_emails', mapped.showEmails);
    req.query('stats', mapped.stats);
    req.query('email', mapped.email);
    req.query('ip', mapped.ip);
    return req.callAsJson(array(adminUsersJsonResponse2Schema), requestOptions);
  }

  /**
   * @param flag
   * @param order
   * @param asc
   * @param page
   * @param showEmails  Include user email addresses in response. These requests will be logged in the
   *                               staff action logs.
   * @param stats       Include user stats information
   * @param email       Filter to the user with this email address
   * @param ip          Filter to users with this IP address
   * @return Response from the API call
   */
  async adminListUsersFlag(
    flag: Flag,
    order?: Order3,
    asc?: Asc,
    page?: number,
    showEmails?: boolean,
    stats?: boolean,
    email?: string,
    ip?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AdminUsersListJsonResponse[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      flag: [flag, flagSchema],
      order: [order, optional(order3Schema)],
      asc: [asc, optional(ascSchema)],
      page: [page, optional(number())],
      showEmails: [showEmails, optional(boolean())],
      stats: [stats, optional(boolean())],
      email: [email, optional(string())],
      ip: [ip, optional(string())],
    });
    req.query('order', mapped.order);
    req.query('asc', mapped.asc);
    req.query('page', mapped.page);
    req.query('show_emails', mapped.showEmails);
    req.query('stats', mapped.stats);
    req.query('email', mapped.email);
    req.query('ip', mapped.ip);
    req.appendTemplatePath`/admin/users/list/${mapped.flag}.json`;
    return req.callAsJson(
      array(adminUsersListJsonResponseSchema),
      requestOptions
    );
  }

  /**
   * @param offset
   * @param username
   * @param filter
   * @return Response from the API call
   */
  async listUserActions(
    offset: number,
    username: string,
    filter: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UserActionsJsonResponse>> {
    const req = this.createRequest('GET', '/user_actions.json');
    const mapped = req.prepareArgs({
      offset: [offset, number()],
      username: [username, string()],
      filter: [filter, string()],
    });
    req.query('offset', mapped.offset);
    req.query('username', mapped.username);
    req.query('filter', mapped.filter);
    return req.callAsJson(userActionsJsonResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async sendPasswordResetEmail(
    body?: SessionForgotPasswordJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SessionForgotPasswordJsonResponse>> {
    const req = this.createRequest('POST', '/session/forgot_password.json');
    const mapped = req.prepareArgs({
      body: [body, optional(sessionForgotPasswordJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(
      sessionForgotPasswordJsonResponseSchema,
      requestOptions
    );
  }

  /**
   * @param token
   * @param body
   * @return Response from the API call
   */
  async changePassword(
    token: string,
    body?: UsersPasswordResetJsonRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      token: [token, string()],
      body: [body, optional(usersPasswordResetJsonRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/users/password-reset/${mapped.token}.json`;
    return req.call(requestOptions);
  }

  /**
   * @param username
   * @return Response from the API call
   */
  async getUserEmails(
    username: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UEmailsJsonResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ username: [username, string()] });
    req.appendTemplatePath`/u/${mapped.username}/emails.json`;
    return req.callAsJson(uEmailsJsonResponseSchema, requestOptions);
  }
}
