/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema.js';

export interface AccessControl {
  mandatoryAcl?: unknown;
  bannedAcl?: unknown;
}

export const accessControlSchema: Schema<AccessControl> = object({
  mandatoryAcl: ['mandatory_acl', optional(unknown())],
  bannedAcl: ['banned_acl', optional(unknown())],
});
