/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ActionsSummary6 {
  id?: number;
  canAct?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const actionsSummary6Schema: Schema<ActionsSummary6> = typedExpandoObject(
  { id: ['id', optional(number())], canAct: ['can_act', optional(boolean())] },
  'additionalProperties',
  optional(unknown())
);
