/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ActionsSummary5 {
  /** ID of the action type (e.g., 2 for like) */
  id?: number;
  /** Number of times this action has been performed */
  count?: number;
  /**
   * Whether the current user has performed this
   * action
   */
  acted?: boolean;
  /** Whether the current user can undo this action */
  canUndo?: boolean;
  /** Whether the current user can perform this action */
  canAct?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const actionsSummary5Schema: Schema<ActionsSummary5> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    count: ['count', optional(number())],
    acted: ['acted', optional(boolean())],
    canUndo: ['can_undo', optional(boolean())],
    canAct: ['can_act', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
