/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema } from '../schema.js';

export interface ActionsSummary8 {
  id: number;
  count: number;
  hidden: boolean;
  canAct: boolean;
}

export const actionsSummary8Schema: Schema<ActionsSummary8> = object({
  id: ['id', number()],
  count: ['count', number()],
  hidden: ['hidden', boolean()],
  canAct: ['can_act', boolean()],
});
