/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema } from '../schema.js';

export interface ActionsSummary {
  id: number;
  canAct: boolean;
}

export const actionsSummarySchema: Schema<ActionsSummary> = object({
  id: ['id', number()],
  canAct: ['can_act', boolean()],
});
