/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema.js';

export interface ActionsSummary2 {
  /** `2`: like, `3`, `4`, `6`, `7`, `8`: flag */
  id: number;
  count?: number;
  acted?: boolean;
  canUndo?: boolean;
  canAct?: boolean;
}

export const actionsSummary2Schema: Schema<ActionsSummary2> = object({
  id: ['id', number()],
  count: ['count', optional(number())],
  acted: ['acted', optional(boolean())],
  canUndo: ['can_undo', optional(boolean())],
  canAct: ['can_act', optional(boolean())],
});
