/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { AdminBadges, adminBadgesSchema } from './adminBadges.js';
import { Badge, badgeSchema } from './badge.js';
import { BadgeGrouping, badgeGroupingSchema } from './badgeGrouping.js';
import { BadgeType, badgeTypeSchema } from './badgeType.js';

export interface AdminBadgesJsonResponse {
  badges: Badge[];
  badgeTypes: BadgeType[];
  badgeGroupings: BadgeGrouping[];
  adminBadges: AdminBadges;
}

export const adminBadgesJsonResponseSchema: Schema<AdminBadgesJsonResponse> = lazy(
  () =>
    object({
      badges: ['badges', array(badgeSchema)],
      badgeTypes: ['badge_types', array(badgeTypeSchema)],
      badgeGroupings: ['badge_groupings', array(badgeGroupingSchema)],
      adminBadges: ['admin_badges', adminBadgesSchema],
    })
);
