/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface AdminUsersDeactivateJsonResponse {
  success: string;
}

export const adminUsersDeactivateJsonResponseSchema: Schema<AdminUsersDeactivateJsonResponse> = object(
  { success: ['success', string()] }
);
