/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface AdminBackupsJsonResponse1 {
  success: string;
}

export const adminBackupsJsonResponse1Schema: Schema<AdminBackupsJsonResponse1> = object(
  { success: ['success', string()] }
);
