/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Group, groupSchema } from './group.js';

export interface AdminGroupsJsonRequest {
  group: Group;
}

export const adminGroupsJsonRequestSchema: Schema<AdminGroupsJsonRequest> = lazy(
  () => object({ group: ['group', groupSchema] })
);
