/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema.js';

export interface AdminUsersJsonResponse1 {
  deleted: boolean;
}

export const adminUsersJsonResponse1Schema: Schema<AdminUsersJsonResponse1> = object(
  { deleted: ['deleted', boolean()] }
);
