/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface AdminBadgesJsonRequest1 {
  /** The name for the new badge. */
  name: string;
  /**
   * The ID for the badge type. 1 for Gold, 2 for Silver,
   * 3 for Bronze.
   */
  badgeTypeId: number;
}

export const adminBadgesJsonRequest1Schema: Schema<AdminBadgesJsonRequest1> = object(
  { name: ['name', string()], badgeTypeId: ['badge_type_id', number()] }
);
