/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

export interface AdminUsersJsonRequest {
  deletePosts?: boolean;
  blockEmail?: boolean;
  blockUrls?: boolean;
  blockIp?: boolean;
}

export const adminUsersJsonRequestSchema: Schema<AdminUsersJsonRequest> = object(
  {
    deletePosts: ['delete_posts', optional(boolean())],
    blockEmail: ['block_email', optional(boolean())],
    blockUrls: ['block_urls', optional(boolean())],
    blockIp: ['block_ip', optional(boolean())],
  }
);
