/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Badge1, badge1Schema } from './badge1.js';
import { BadgeType, badgeTypeSchema } from './badgeType.js';

export interface AdminBadgesJsonResponse1 {
  badgeTypes: BadgeType[];
  badge: Badge1;
}

export const adminBadgesJsonResponse1Schema: Schema<AdminBadgesJsonResponse1> = lazy(
  () =>
    object({
      badgeTypes: ['badge_types', array(badgeTypeSchema)],
      badge: ['badge', badge1Schema],
    })
);
