/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema.js';

export interface AdminBackupsJsonRequest {
  withUploads: boolean;
}

export const adminBackupsJsonRequestSchema: Schema<AdminBackupsJsonRequest> = object(
  { withUploads: ['with_uploads', boolean()] }
);
