/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface AdminUsersSilenceJsonRequest {
  silencedTill: string;
  reason: string;
  /** Will send an email with this message when present */
  message?: string;
  postAction?: string;
}

export const adminUsersSilenceJsonRequestSchema: Schema<AdminUsersSilenceJsonRequest> = object(
  {
    silencedTill: ['silenced_till', string()],
    reason: ['reason', string()],
    message: ['message', optional(string())],
    postAction: ['post_action', optional(string())],
  }
);
