/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Suspension, suspensionSchema } from './suspension.js';

export interface AdminUsersSuspendJsonResponse {
  suspension: Suspension;
}

export const adminUsersSuspendJsonResponseSchema: Schema<AdminUsersSuspendJsonResponse> = lazy(
  () => object({ suspension: ['suspension', suspensionSchema] })
);
