/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface AdminUsersActivateJsonResponse {
  success: string;
}

export const adminUsersActivateJsonResponseSchema: Schema<AdminUsersActivateJsonResponse> = object(
  { success: ['success', string()] }
);
