/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AdminBackupsJsonResponse {
  filename: string;
  size: number;
  lastModified: string;
  additionalProperties?: Record<string, unknown>;
}

export const adminBackupsJsonResponseSchema: Schema<AdminBackupsJsonResponse> = typedExpandoObject(
  {
    filename: ['filename', string()],
    size: ['size', number()],
    lastModified: ['last_modified', string()],
  },
  'additionalProperties',
  optional(unknown())
);
