/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { ApprovedBy, approvedBySchema } from './approvedBy.js';
import { Group10, group10Schema } from './group10.js';
import { PenaltyCounts, penaltyCountsSchema } from './penaltyCounts.js';
import { Tl3Requirements, tl3RequirementsSchema } from './tl3Requirements.js';
import {
  UpcomingChangesStat,
  upcomingChangesStatSchema,
} from './upcomingChangesStat.js';

export interface AdminUsersJsonResponse {
  id: number;
  username: string;
  name: string | null;
  avatarTemplate: string;
  active: boolean;
  admin: boolean;
  moderator: boolean;
  lastSeenAt: string | null;
  lastEmailedAt: string | null;
  createdAt: string;
  lastSeenAge: number | null;
  lastEmailedAge: number | null;
  createdAtAge: number | null;
  trustLevel: number;
  manualLockedTrustLevel: string | null;
  title: string | null;
  timeRead: number;
  staged: boolean;
  daysVisited: number;
  postsReadCount: number;
  topicsEntered: number;
  postCount: number;
  associatedAccounts?: unknown[];
  canSendActivationEmail: boolean;
  canActivate: boolean;
  canDeactivate: boolean;
  canChangeTrustLevel?: boolean;
  ipAddress: string;
  registrationIpAddress: string | null;
  canGrantAdmin: boolean;
  canRevokeAdmin: boolean;
  canGrantModeration: boolean;
  canRevokeModeration: boolean;
  canImpersonate: boolean;
  likeCount: number;
  likeGivenCount: number;
  topicCount: number;
  flagsGivenCount: number;
  flagsReceivedCount: number;
  privateTopicsCount: number;
  canDeleteAllPosts: boolean;
  canBeDeleted?: boolean;
  canBeAnonymized: boolean;
  canBeMerged: boolean;
  fullSuspendReason: string | null;
  latestExport?: unknown | null;
  fullSilenceReason?: string | null;
  silenceReason?: string | null;
  postEditsCount?: number | null;
  primaryGroupId: number | null;
  badgeCount: number;
  warningsReceivedCount: number;
  bounceScore: number | null;
  resetBounceScoreAfter: string | null;
  canViewActionLogs: boolean;
  canDisableSecondFactor: boolean;
  canDeleteSsoRecord: boolean;
  apiKeyCount: number;
  similarUsersCount?: number;
  singleSignOnRecord: string | null;
  approvedBy: ApprovedBy | null;
  suspendedBy: string | null;
  silencedBy: string | null;
  penaltyCounts?: PenaltyCounts;
  nextPenalty?: string;
  tl3Requirements?: Tl3Requirements;
  groups: Group10[];
  externalIds?: unknown;
  includeIp: boolean;
  upcomingChangesStats?: UpcomingChangesStat[];
}

export const adminUsersJsonResponseSchema: Schema<AdminUsersJsonResponse> = lazy(
  () =>
    object({
      id: ['id', number()],
      username: ['username', string()],
      name: ['name', nullable(string())],
      avatarTemplate: ['avatar_template', string()],
      active: ['active', boolean()],
      admin: ['admin', boolean()],
      moderator: ['moderator', boolean()],
      lastSeenAt: ['last_seen_at', nullable(string())],
      lastEmailedAt: ['last_emailed_at', nullable(string())],
      createdAt: ['created_at', string()],
      lastSeenAge: ['last_seen_age', nullable(number())],
      lastEmailedAge: ['last_emailed_age', nullable(number())],
      createdAtAge: ['created_at_age', nullable(number())],
      trustLevel: ['trust_level', number()],
      manualLockedTrustLevel: ['manual_locked_trust_level', nullable(string())],
      title: ['title', nullable(string())],
      timeRead: ['time_read', number()],
      staged: ['staged', boolean()],
      daysVisited: ['days_visited', number()],
      postsReadCount: ['posts_read_count', number()],
      topicsEntered: ['topics_entered', number()],
      postCount: ['post_count', number()],
      associatedAccounts: ['associated_accounts', optional(array(unknown()))],
      canSendActivationEmail: ['can_send_activation_email', boolean()],
      canActivate: ['can_activate', boolean()],
      canDeactivate: ['can_deactivate', boolean()],
      canChangeTrustLevel: ['can_change_trust_level', optional(boolean())],
      ipAddress: ['ip_address', string()],
      registrationIpAddress: ['registration_ip_address', nullable(string())],
      canGrantAdmin: ['can_grant_admin', boolean()],
      canRevokeAdmin: ['can_revoke_admin', boolean()],
      canGrantModeration: ['can_grant_moderation', boolean()],
      canRevokeModeration: ['can_revoke_moderation', boolean()],
      canImpersonate: ['can_impersonate', boolean()],
      likeCount: ['like_count', number()],
      likeGivenCount: ['like_given_count', number()],
      topicCount: ['topic_count', number()],
      flagsGivenCount: ['flags_given_count', number()],
      flagsReceivedCount: ['flags_received_count', number()],
      privateTopicsCount: ['private_topics_count', number()],
      canDeleteAllPosts: ['can_delete_all_posts', boolean()],
      canBeDeleted: ['can_be_deleted', optional(boolean())],
      canBeAnonymized: ['can_be_anonymized', boolean()],
      canBeMerged: ['can_be_merged', boolean()],
      fullSuspendReason: ['full_suspend_reason', nullable(string())],
      latestExport: ['latest_export', optional(nullable(unknown()))],
      fullSilenceReason: ['full_silence_reason', optional(nullable(string()))],
      silenceReason: ['silence_reason', optional(nullable(string()))],
      postEditsCount: ['post_edits_count', optional(nullable(number()))],
      primaryGroupId: ['primary_group_id', nullable(number())],
      badgeCount: ['badge_count', number()],
      warningsReceivedCount: ['warnings_received_count', number()],
      bounceScore: ['bounce_score', nullable(number())],
      resetBounceScoreAfter: ['reset_bounce_score_after', nullable(string())],
      canViewActionLogs: ['can_view_action_logs', boolean()],
      canDisableSecondFactor: ['can_disable_second_factor', boolean()],
      canDeleteSsoRecord: ['can_delete_sso_record', boolean()],
      apiKeyCount: ['api_key_count', number()],
      similarUsersCount: ['similar_users_count', optional(number())],
      singleSignOnRecord: ['single_sign_on_record', nullable(string())],
      approvedBy: ['approved_by', nullable(approvedBySchema)],
      suspendedBy: ['suspended_by', nullable(string())],
      silencedBy: ['silenced_by', nullable(string())],
      penaltyCounts: ['penalty_counts', optional(penaltyCountsSchema)],
      nextPenalty: ['next_penalty', optional(string())],
      tl3Requirements: ['tl3_requirements', optional(tl3RequirementsSchema)],
      groups: ['groups', array(group10Schema)],
      externalIds: ['external_ids', optional(unknown())],
      includeIp: ['include_ip', boolean()],
      upcomingChangesStats: [
        'upcoming_changes_stats',
        optional(array(upcomingChangesStatSchema)),
      ],
    })
);
