/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Silence, silenceSchema } from './silence.js';

export interface AdminUsersSilenceJsonResponse {
  silence: Silence;
}

export const adminUsersSilenceJsonResponseSchema: Schema<AdminUsersSilenceJsonResponse> = lazy(
  () => object({ silence: ['silence', silenceSchema] })
);
