/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AdminUsersJsonResponse2 {
  id: number;
  username: string;
  name: string | null;
  avatarTemplate: string;
  email?: string;
  secondaryEmails?: unknown[];
  active: boolean;
  admin: boolean;
  moderator: boolean;
  lastSeenAt: string | null;
  lastEmailedAt: string | null;
  createdAt: string;
  lastSeenAge: number | null;
  lastEmailedAge: number | null;
  createdAtAge: number | null;
  trustLevel: number;
  manualLockedTrustLevel: string | null;
  title: string | null;
  timeRead: number;
  staged: boolean;
  daysVisited: number;
  postsReadCount: number;
  topicsEntered: number;
  postCount: number;
  additionalProperties?: Record<string, unknown>;
}

export const adminUsersJsonResponse2Schema: Schema<AdminUsersJsonResponse2> = typedExpandoObject(
  {
    id: ['id', number()],
    username: ['username', string()],
    name: ['name', nullable(string())],
    avatarTemplate: ['avatar_template', string()],
    email: ['email', optional(string())],
    secondaryEmails: ['secondary_emails', optional(array(unknown()))],
    active: ['active', boolean()],
    admin: ['admin', boolean()],
    moderator: ['moderator', boolean()],
    lastSeenAt: ['last_seen_at', nullable(string())],
    lastEmailedAt: ['last_emailed_at', nullable(string())],
    createdAt: ['created_at', string()],
    lastSeenAge: ['last_seen_age', nullable(number())],
    lastEmailedAge: ['last_emailed_age', nullable(number())],
    createdAtAge: ['created_at_age', nullable(number())],
    trustLevel: ['trust_level', number()],
    manualLockedTrustLevel: ['manual_locked_trust_level', nullable(string())],
    title: ['title', nullable(string())],
    timeRead: ['time_read', number()],
    staged: ['staged', boolean()],
    daysVisited: ['days_visited', number()],
    postsReadCount: ['posts_read_count', number()],
    topicsEntered: ['topics_entered', number()],
    postCount: ['post_count', number()],
  },
  'additionalProperties',
  optional(unknown())
);
