/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, unknown } from '../schema.js';
import { Triggers, triggersSchema } from './triggers.js';

export interface AdminBadges {
  protectedSystemFields: unknown[];
  triggers: Triggers;
  badgeIds: unknown[];
  badgeGroupingIds: unknown[];
  badgeTypeIds: unknown[];
}

export const adminBadgesSchema: Schema<AdminBadges> = lazy(() =>
  object({
    protectedSystemFields: ['protected_system_fields', array(unknown())],
    triggers: ['triggers', triggersSchema],
    badgeIds: ['badge_ids', array(unknown())],
    badgeGroupingIds: ['badge_grouping_ids', array(unknown())],
    badgeTypeIds: ['badge_type_ids', array(unknown())],
  })
);
