/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { BasicGroup, basicGroupSchema } from './basicGroup.js';

export interface AdminGroupsJsonResponse {
  basicGroup: BasicGroup;
}

export const adminGroupsJsonResponseSchema: Schema<AdminGroupsJsonResponse> = lazy(
  () => object({ basicGroup: ['basic_group', basicGroupSchema] })
);
