/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema.js';

export interface Archetype {
  id: string;
  name: string;
  options: unknown[];
}

export const archetypeSchema: Schema<Archetype> = object({
  id: ['id', string()],
  name: ['name', string()],
  options: ['options', array(unknown())],
});
