/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface AvailableCategoryType {
  id: string;
  name: string;
  title: string;
  description: string;
  icon: string;
  available: boolean;
  visible: boolean;
  configurationSchema?: unknown;
}

export const availableCategoryTypeSchema: Schema<AvailableCategoryType> = object(
  {
    id: ['id', string()],
    name: ['name', string()],
    title: ['title', string()],
    description: ['description', string()],
    icon: ['icon', string()],
    available: ['available', boolean()],
    visible: ['visible', boolean()],
    configurationSchema: ['configuration_schema', optional(unknown())],
  }
);
