/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';

export interface Badge3 {
  id: number;
  name: string;
  description: string;
  grantCount: number;
  allowTitle: boolean;
  multipleGrant: boolean;
  icon: string;
  imageUrl: string | null;
  listable: boolean;
  enabled: boolean;
  badgeGroupingId: number;
  system: boolean;
  slug: string;
  manuallyGrantable: boolean;
  badgeTypeId: number;
}

export const badge3Schema: Schema<Badge3> = object({
  id: ['id', number()],
  name: ['name', string()],
  description: ['description', string()],
  grantCount: ['grant_count', number()],
  allowTitle: ['allow_title', boolean()],
  multipleGrant: ['multiple_grant', boolean()],
  icon: ['icon', string()],
  imageUrl: ['image_url', nullable(string())],
  listable: ['listable', boolean()],
  enabled: ['enabled', boolean()],
  badgeGroupingId: ['badge_grouping_id', number()],
  system: ['system', boolean()],
  slug: ['slug', string()],
  manuallyGrantable: ['manually_grantable', boolean()],
  badgeTypeId: ['badge_type_id', number()],
});
