/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface BadgeType {
  id: number;
  name: string;
  sortOrder: number;
}

export const badgeTypeSchema: Schema<BadgeType> = object({
  id: ['id', number()],
  name: ['name', string()],
  sortOrder: ['sort_order', number()],
});
