/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';

export interface Badge1 {
  id: number;
  name: string;
  description: string;
  grantCount: number;
  allowTitle: boolean;
  multipleGrant: boolean;
  icon: string;
  imageUrl: string | null;
  imageUploadId: number | null;
  listable: boolean;
  enabled: boolean;
  badgeGroupingId: number;
  system: boolean;
  longDescription: string;
  slug: string;
  manuallyGrantable: boolean;
  query: string | null;
  trigger: string | null;
  targetPosts: boolean;
  autoRevoke: boolean;
  showPosts: boolean;
  badgeTypeId: number;
  showInPostHeader: boolean;
}

export const badge1Schema: Schema<Badge1> = object({
  id: ['id', number()],
  name: ['name', string()],
  description: ['description', string()],
  grantCount: ['grant_count', number()],
  allowTitle: ['allow_title', boolean()],
  multipleGrant: ['multiple_grant', boolean()],
  icon: ['icon', string()],
  imageUrl: ['image_url', nullable(string())],
  imageUploadId: ['image_upload_id', nullable(number())],
  listable: ['listable', boolean()],
  enabled: ['enabled', boolean()],
  badgeGroupingId: ['badge_grouping_id', number()],
  system: ['system', boolean()],
  longDescription: ['long_description', string()],
  slug: ['slug', string()],
  manuallyGrantable: ['manually_grantable', boolean()],
  query: ['query', nullable(string())],
  trigger: ['trigger', nullable(string())],
  targetPosts: ['target_posts', boolean()],
  autoRevoke: ['auto_revoke', boolean()],
  showPosts: ['show_posts', boolean()],
  badgeTypeId: ['badge_type_id', number()],
  showInPostHeader: ['show_in_post_header', boolean()],
});
