/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';

export interface BadgeGrouping {
  id: number;
  name: string;
  description: string | null;
  position: number;
  system: boolean;
}

export const badgeGroupingSchema: Schema<BadgeGrouping> = object({
  id: ['id', number()],
  name: ['name', string()],
  description: ['description', nullable(string())],
  position: ['position', number()],
  system: ['system', boolean()],
});
