/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BasicTopic {
  id?: number;
  title?: string;
  fancyTitle?: string;
  slug?: string;
  postsCount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const basicTopicSchema: Schema<BasicTopic> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    title: ['title', optional(string())],
    fancyTitle: ['fancy_title', optional(string())],
    slug: ['slug', optional(string())],
    postsCount: ['posts_count', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
