/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface BasicGroup {
  id: number;
  automatic: boolean;
  name: string;
  userCount: number;
  mentionableLevel: number;
  messageableLevel: number;
  visibilityLevel: number;
  primaryGroup: boolean;
  title: string | null;
  grantTrustLevel: string | null;
  incomingEmail: string | null;
  hasMessages: boolean;
  flairUrl: string | null;
  flairBgColor: string | null;
  flairColor: string | null;
  bioRaw: string | null;
  bioCooked: string | null;
  bioExcerpt: string | null;
  publicAdmission: boolean;
  publicExit: boolean;
  allowMembershipRequests: boolean;
  fullName: string | null;
  defaultNotificationLevel: number;
  membershipRequestTemplate: string | null;
  membersVisibilityLevel: number;
  canSeeMembers: boolean;
  canAdminGroup: boolean;
  canEditGroup?: boolean;
  publishReadState: boolean;
}

export const basicGroupSchema: Schema<BasicGroup> = object({
  id: ['id', number()],
  automatic: ['automatic', boolean()],
  name: ['name', string()],
  userCount: ['user_count', number()],
  mentionableLevel: ['mentionable_level', number()],
  messageableLevel: ['messageable_level', number()],
  visibilityLevel: ['visibility_level', number()],
  primaryGroup: ['primary_group', boolean()],
  title: ['title', nullable(string())],
  grantTrustLevel: ['grant_trust_level', nullable(string())],
  incomingEmail: ['incoming_email', nullable(string())],
  hasMessages: ['has_messages', boolean()],
  flairUrl: ['flair_url', nullable(string())],
  flairBgColor: ['flair_bg_color', nullable(string())],
  flairColor: ['flair_color', nullable(string())],
  bioRaw: ['bio_raw', nullable(string())],
  bioCooked: ['bio_cooked', nullable(string())],
  bioExcerpt: ['bio_excerpt', nullable(string())],
  publicAdmission: ['public_admission', boolean()],
  publicExit: ['public_exit', boolean()],
  allowMembershipRequests: ['allow_membership_requests', boolean()],
  fullName: ['full_name', nullable(string())],
  defaultNotificationLevel: ['default_notification_level', number()],
  membershipRequestTemplate: [
    'membership_request_template',
    nullable(string()),
  ],
  membersVisibilityLevel: ['members_visibility_level', number()],
  canSeeMembers: ['can_see_members', boolean()],
  canAdminGroup: ['can_admin_group', boolean()],
  canEditGroup: ['can_edit_group', optional(boolean())],
  publishReadState: ['publish_read_state', boolean()],
});
