/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface CategorySetting {
  autoBumpCooldownDays?: number;
  numAutoBumpDaily?: number | null;
  requireReplyApproval?: boolean | null;
  requireTopicApproval?: boolean | null;
  nestedRepliesDefault?: boolean | null;
  topicPostingReviewMode?: string;
  replyPostingReviewMode?: string;
}

export const categorySettingSchema: Schema<CategorySetting> = object({
  autoBumpCooldownDays: ['auto_bump_cooldown_days', optional(number())],
  numAutoBumpDaily: ['num_auto_bump_daily', optional(nullable(number()))],
  requireReplyApproval: [
    'require_reply_approval',
    optional(nullable(boolean())),
  ],
  requireTopicApproval: [
    'require_topic_approval',
    optional(nullable(boolean())),
  ],
  nestedRepliesDefault: [
    'nested_replies_default',
    optional(nullable(boolean())),
  ],
  topicPostingReviewMode: ['topic_posting_review_mode', optional(string())],
  replyPostingReviewMode: ['reply_posting_review_mode', optional(string())],
});
