/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import {
  CategoryLocalization,
  categoryLocalizationSchema,
} from './categoryLocalization.js';
import { Permissions, permissionsSchema } from './permissions.js';

export interface CategoriesJsonRequest1 {
  name: string;
  color?: string;
  textColor?: string;
  styleType?: string;
  emoji?: string;
  icon?: string;
  parentCategoryId?: number;
  allowBadges?: boolean;
  slug?: string;
  topicFeaturedLinksAllowed?: boolean;
  permissions?: Permissions;
  searchPriority?: number;
  formTemplateIds?: unknown[];
  categoryLocalizations?: CategoryLocalization[];
}

export const categoriesJsonRequest1Schema: Schema<CategoriesJsonRequest1> = lazy(
  () =>
    object({
      name: ['name', string()],
      color: ['color', optional(string())],
      textColor: ['text_color', optional(string())],
      styleType: ['style_type', optional(string())],
      emoji: ['emoji', optional(string())],
      icon: ['icon', optional(string())],
      parentCategoryId: ['parent_category_id', optional(number())],
      allowBadges: ['allow_badges', optional(boolean())],
      slug: ['slug', optional(string())],
      topicFeaturedLinksAllowed: [
        'topic_featured_links_allowed',
        optional(boolean()),
      ],
      permissions: ['permissions', optional(permissionsSchema)],
      searchPriority: ['search_priority', optional(number())],
      formTemplateIds: ['form_template_ids', optional(array(unknown()))],
      categoryLocalizations: [
        'category_localizations',
        optional(array(categoryLocalizationSchema)),
      ],
    })
);
