/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CategoryLocalization {
  /**
   * The unique identifier for an existing localization.
   * Must be included otherwise the record will be deleted.
   */
  id?: number;
  /**
   * The locale for the localization, e.g., 'en',
   * 'zh_CN'. Locale should be in the list of SiteSetting.content_localization_supported_locales.
   */
  locale: string;
  /** The name of the category in the specified locale. */
  name: string;
  /**
   * The description excerpt of the category in the
   * specified locale.
   */
  description?: string;
  additionalProperties?: Record<string, unknown>;
}

export const categoryLocalizationSchema: Schema<CategoryLocalization> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    locale: ['locale', string()],
    name: ['name', string()],
    description: ['description', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
