/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface Category1 {
  id: number;
  name: string;
  color: string;
  textColor: string;
  styleType: string;
  emoji: string | null;
  icon: string | null;
  slug: string;
  topicCount: number;
  postCount: number;
  position: number;
  description: string | null;
  descriptionText: string | null;
  descriptionExcerpt: string | null;
  topicUrl: string | null;
  readRestricted: boolean;
  permission: number;
  notificationLevel: number;
  canEdit: boolean;
  topicTemplate: string | null;
  topicTitlePlaceholder: string | null;
  hasChildren: boolean;
  subcategoryCount: number | null;
  sortOrder: string | null;
  sortAscending: string | null;
  showSubcategoryList: boolean;
  numFeaturedTopics: number;
  defaultView: string | null;
  subcategoryListStyle: string;
  defaultTopPeriod: string;
  defaultListFilter: string;
  minimumRequiredTags: number;
  navigateToFirstPostAfterRead: boolean;
  topicsDay: number;
  topicsWeek: number;
  topicsMonth: number;
  topicsYear: number;
  topicsAllTime: number;
  isUncategorized?: boolean;
  subcategoryIds: unknown[];
  subcategoryList?: unknown[] | null;
  uploadedLogo: string | null;
  uploadedLogoDark: string | null;
  uploadedBackground: string | null;
  uploadedBackgroundDark: string | null;
}

export const category1Schema: Schema<Category1> = object({
  id: ['id', number()],
  name: ['name', string()],
  color: ['color', string()],
  textColor: ['text_color', string()],
  styleType: ['style_type', string()],
  emoji: ['emoji', nullable(string())],
  icon: ['icon', nullable(string())],
  slug: ['slug', string()],
  topicCount: ['topic_count', number()],
  postCount: ['post_count', number()],
  position: ['position', number()],
  description: ['description', nullable(string())],
  descriptionText: ['description_text', nullable(string())],
  descriptionExcerpt: ['description_excerpt', nullable(string())],
  topicUrl: ['topic_url', nullable(string())],
  readRestricted: ['read_restricted', boolean()],
  permission: ['permission', number()],
  notificationLevel: ['notification_level', number()],
  canEdit: ['can_edit', boolean()],
  topicTemplate: ['topic_template', nullable(string())],
  topicTitlePlaceholder: ['topic_title_placeholder', nullable(string())],
  hasChildren: ['has_children', boolean()],
  subcategoryCount: ['subcategory_count', nullable(number())],
  sortOrder: ['sort_order', nullable(string())],
  sortAscending: ['sort_ascending', nullable(string())],
  showSubcategoryList: ['show_subcategory_list', boolean()],
  numFeaturedTopics: ['num_featured_topics', number()],
  defaultView: ['default_view', nullable(string())],
  subcategoryListStyle: ['subcategory_list_style', string()],
  defaultTopPeriod: ['default_top_period', string()],
  defaultListFilter: ['default_list_filter', string()],
  minimumRequiredTags: ['minimum_required_tags', number()],
  navigateToFirstPostAfterRead: [
    'navigate_to_first_post_after_read',
    boolean(),
  ],
  topicsDay: ['topics_day', number()],
  topicsWeek: ['topics_week', number()],
  topicsMonth: ['topics_month', number()],
  topicsYear: ['topics_year', number()],
  topicsAllTime: ['topics_all_time', number()],
  isUncategorized: ['is_uncategorized', optional(boolean())],
  subcategoryIds: ['subcategory_ids', array(unknown())],
  subcategoryList: ['subcategory_list', optional(nullable(array(unknown())))],
  uploadedLogo: ['uploaded_logo', nullable(string())],
  uploadedLogoDark: ['uploaded_logo_dark', nullable(string())],
  uploadedBackground: ['uploaded_background', nullable(string())],
  uploadedBackgroundDark: ['uploaded_background_dark', nullable(string())],
});
