/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { CategoryList, categoryListSchema } from './categoryList.js';

export interface CategoriesJsonResponse1 {
  categoryList: CategoryList;
}

export const categoriesJsonResponse1Schema: Schema<CategoriesJsonResponse1> = lazy(
  () => object({ categoryList: ['category_list', categoryListSchema] })
);
