/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, Schema } from '../schema.js';
import { Category1, category1Schema } from './category1.js';

export interface CategoryList {
  canCreateCategory: boolean;
  canCreateTopic: boolean;
  categories: Category1[];
}

export const categoryListSchema: Schema<CategoryList> = lazy(() =>
  object({
    canCreateCategory: ['can_create_category', boolean()],
    canCreateTopic: ['can_create_topic', boolean()],
    categories: ['categories', array(category1Schema)],
  })
);
