/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Category2, category2Schema } from './category2.js';

export interface CategoriesJsonResponse2 {
  success: string;
  category: Category2;
}

export const categoriesJsonResponse2Schema: Schema<CategoriesJsonResponse2> = lazy(
  () =>
    object({
      success: ['success', string()],
      category: ['category', category2Schema],
    })
);
