/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import {
  RequiredTagGroup,
  requiredTagGroupSchema,
} from './requiredTagGroup.js';

export interface Category4 {
  id: number;
  name: string;
  color: string;
  textColor: string;
  styleType?: string;
  emoji?: string | null;
  icon?: string | null;
  slug: string;
  topicCount: number;
  postCount: number;
  position: number;
  description?: string | null;
  descriptionText?: string | null;
  descriptionExcerpt?: string | null;
  topicUrl: string;
  readRestricted: boolean;
  permission: number;
  notificationLevel: number;
  topicTemplate: string | null;
  topicTitlePlaceholder: string | null;
  hasChildren: boolean;
  subcategoryCount: number | null;
  sortOrder: string | null;
  sortAscending: string | null;
  showSubcategoryList: boolean;
  numFeaturedTopics: number;
  defaultView: string | null;
  subcategoryListStyle: string;
  defaultTopPeriod: string;
  defaultListFilter: string;
  minimumRequiredTags: number;
  navigateToFirstPostAfterRead: boolean;
  allowedTags: unknown[];
  allowedTagGroups: unknown[];
  allowGlobalTags: boolean;
  requiredTagGroups: RequiredTagGroup[];
  readOnlyBanner: string | null;
  uploadedLogo: string | null;
  uploadedLogoDark: string | null;
  uploadedBackground: string | null;
  uploadedBackgroundDark: string | null;
  canEdit: boolean;
  customFields?: unknown | null;
  parentCategoryId?: number;
  formTemplateIds?: unknown[];
  categoryTypes?: unknown;
}

export const category4Schema: Schema<Category4> = lazy(() =>
  object({
    id: ['id', number()],
    name: ['name', string()],
    color: ['color', string()],
    textColor: ['text_color', string()],
    styleType: ['style_type', optional(string())],
    emoji: ['emoji', optional(nullable(string()))],
    icon: ['icon', optional(nullable(string()))],
    slug: ['slug', string()],
    topicCount: ['topic_count', number()],
    postCount: ['post_count', number()],
    position: ['position', number()],
    description: ['description', optional(nullable(string()))],
    descriptionText: ['description_text', optional(nullable(string()))],
    descriptionExcerpt: ['description_excerpt', optional(nullable(string()))],
    topicUrl: ['topic_url', string()],
    readRestricted: ['read_restricted', boolean()],
    permission: ['permission', number()],
    notificationLevel: ['notification_level', number()],
    topicTemplate: ['topic_template', nullable(string())],
    topicTitlePlaceholder: ['topic_title_placeholder', nullable(string())],
    hasChildren: ['has_children', boolean()],
    subcategoryCount: ['subcategory_count', nullable(number())],
    sortOrder: ['sort_order', nullable(string())],
    sortAscending: ['sort_ascending', nullable(string())],
    showSubcategoryList: ['show_subcategory_list', boolean()],
    numFeaturedTopics: ['num_featured_topics', number()],
    defaultView: ['default_view', nullable(string())],
    subcategoryListStyle: ['subcategory_list_style', string()],
    defaultTopPeriod: ['default_top_period', string()],
    defaultListFilter: ['default_list_filter', string()],
    minimumRequiredTags: ['minimum_required_tags', number()],
    navigateToFirstPostAfterRead: [
      'navigate_to_first_post_after_read',
      boolean(),
    ],
    allowedTags: ['allowed_tags', array(unknown())],
    allowedTagGroups: ['allowed_tag_groups', array(unknown())],
    allowGlobalTags: ['allow_global_tags', boolean()],
    requiredTagGroups: ['required_tag_groups', array(requiredTagGroupSchema)],
    readOnlyBanner: ['read_only_banner', nullable(string())],
    uploadedLogo: ['uploaded_logo', nullable(string())],
    uploadedLogoDark: ['uploaded_logo_dark', nullable(string())],
    uploadedBackground: ['uploaded_background', nullable(string())],
    uploadedBackgroundDark: ['uploaded_background_dark', nullable(string())],
    canEdit: ['can_edit', boolean()],
    customFields: ['custom_fields', optional(nullable(unknown()))],
    parentCategoryId: ['parent_category_id', optional(number())],
    formTemplateIds: ['form_template_ids', optional(array(unknown()))],
    categoryTypes: ['category_types', optional(unknown())],
  })
);
