/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import {
  AvailableCategoryType,
  availableCategoryTypeSchema,
} from './availableCategoryType.js';
import { CategorySetting, categorySettingSchema } from './categorySetting.js';
import { GroupPermission, groupPermissionSchema } from './groupPermission.js';
import {
  RequiredTagGroup,
  requiredTagGroupSchema,
} from './requiredTagGroup.js';

export interface Category {
  id: number;
  name: string;
  color: string;
  textColor: string;
  styleType: string;
  emoji: string | null;
  icon: string | null;
  slug: string;
  locale?: string | null;
  topicCount: number;
  postCount: number;
  position: number;
  description: string | null;
  descriptionText: string | null;
  descriptionExcerpt: string | null;
  topicUrl: string | null;
  readRestricted: boolean;
  permission: number | null;
  notificationLevel: number;
  canEdit: boolean;
  topicTemplate: string | null;
  topicTitlePlaceholder: string | null;
  formTemplateIds?: unknown[];
  hasChildren: boolean | null;
  subcategoryCount: number | null;
  sortOrder: string | null;
  sortAscending: string | null;
  showSubcategoryList: boolean;
  numFeaturedTopics: number;
  defaultView: string | null;
  subcategoryListStyle: string;
  defaultTopPeriod: string;
  defaultListFilter: string;
  minimumRequiredTags: number;
  navigateToFirstPostAfterRead: boolean;
  customFields?: unknown;
  allowedTags?: unknown[];
  allowedTagGroups?: unknown[];
  allowGlobalTags?: boolean;
  requiredTagGroups: RequiredTagGroup[];
  categorySetting?: CategorySetting;
  categoryLocalizations?: unknown[];
  readOnlyBanner: string | null;
  availableGroups: unknown[];
  autoCloseHours: string | null;
  autoCloseBasedOnLastPost: boolean;
  allowUnlimitedOwnerEditsOnFirstPost: boolean;
  defaultSlowModeSeconds: string | null;
  groupPermissions: GroupPermission[];
  emailIn: string | null;
  emailInAllowStrangers: boolean;
  mailinglistMirror: boolean;
  allTopicsWiki: boolean;
  canDelete: boolean;
  allowBadges: boolean;
  topicFeaturedLinkAllowed: boolean;
  searchPriority: number;
  topicPostingReviewGroupIds: number[];
  replyPostingReviewGroupIds: number[];
  uploadedLogo: string | null;
  uploadedLogoDark: string | null;
  uploadedBackground: string | null;
  uploadedBackgroundDark: string | null;
  categoryTypes?: unknown;
  categoryTypeSettings?: unknown;
  availableCategoryTypes?: AvailableCategoryType[];
}

export const categorySchema: Schema<Category> = lazy(() =>
  object({
    id: ['id', number()],
    name: ['name', string()],
    color: ['color', string()],
    textColor: ['text_color', string()],
    styleType: ['style_type', string()],
    emoji: ['emoji', nullable(string())],
    icon: ['icon', nullable(string())],
    slug: ['slug', string()],
    locale: ['locale', optional(nullable(string()))],
    topicCount: ['topic_count', number()],
    postCount: ['post_count', number()],
    position: ['position', number()],
    description: ['description', nullable(string())],
    descriptionText: ['description_text', nullable(string())],
    descriptionExcerpt: ['description_excerpt', nullable(string())],
    topicUrl: ['topic_url', nullable(string())],
    readRestricted: ['read_restricted', boolean()],
    permission: ['permission', nullable(number())],
    notificationLevel: ['notification_level', number()],
    canEdit: ['can_edit', boolean()],
    topicTemplate: ['topic_template', nullable(string())],
    topicTitlePlaceholder: ['topic_title_placeholder', nullable(string())],
    formTemplateIds: ['form_template_ids', optional(array(unknown()))],
    hasChildren: ['has_children', nullable(boolean())],
    subcategoryCount: ['subcategory_count', nullable(number())],
    sortOrder: ['sort_order', nullable(string())],
    sortAscending: ['sort_ascending', nullable(string())],
    showSubcategoryList: ['show_subcategory_list', boolean()],
    numFeaturedTopics: ['num_featured_topics', number()],
    defaultView: ['default_view', nullable(string())],
    subcategoryListStyle: ['subcategory_list_style', string()],
    defaultTopPeriod: ['default_top_period', string()],
    defaultListFilter: ['default_list_filter', string()],
    minimumRequiredTags: ['minimum_required_tags', number()],
    navigateToFirstPostAfterRead: [
      'navigate_to_first_post_after_read',
      boolean(),
    ],
    customFields: ['custom_fields', optional(unknown())],
    allowedTags: ['allowed_tags', optional(array(unknown()))],
    allowedTagGroups: ['allowed_tag_groups', optional(array(unknown()))],
    allowGlobalTags: ['allow_global_tags', optional(boolean())],
    requiredTagGroups: ['required_tag_groups', array(requiredTagGroupSchema)],
    categorySetting: ['category_setting', optional(categorySettingSchema)],
    categoryLocalizations: [
      'category_localizations',
      optional(array(unknown())),
    ],
    readOnlyBanner: ['read_only_banner', nullable(string())],
    availableGroups: ['available_groups', array(unknown())],
    autoCloseHours: ['auto_close_hours', nullable(string())],
    autoCloseBasedOnLastPost: ['auto_close_based_on_last_post', boolean()],
    allowUnlimitedOwnerEditsOnFirstPost: [
      'allow_unlimited_owner_edits_on_first_post',
      boolean(),
    ],
    defaultSlowModeSeconds: ['default_slow_mode_seconds', nullable(string())],
    groupPermissions: ['group_permissions', array(groupPermissionSchema)],
    emailIn: ['email_in', nullable(string())],
    emailInAllowStrangers: ['email_in_allow_strangers', boolean()],
    mailinglistMirror: ['mailinglist_mirror', boolean()],
    allTopicsWiki: ['all_topics_wiki', boolean()],
    canDelete: ['can_delete', boolean()],
    allowBadges: ['allow_badges', boolean()],
    topicFeaturedLinkAllowed: ['topic_featured_link_allowed', boolean()],
    searchPriority: ['search_priority', number()],
    topicPostingReviewGroupIds: [
      'topic_posting_review_group_ids',
      array(number()),
    ],
    replyPostingReviewGroupIds: [
      'reply_posting_review_group_ids',
      array(number()),
    ],
    uploadedLogo: ['uploaded_logo', nullable(string())],
    uploadedLogoDark: ['uploaded_logo_dark', nullable(string())],
    uploadedBackground: ['uploaded_background', nullable(string())],
    uploadedBackgroundDark: ['uploaded_background_dark', nullable(string())],
    categoryTypes: ['category_types', optional(unknown())],
    categoryTypeSettings: ['category_type_settings', optional(unknown())],
    availableCategoryTypes: [
      'available_category_types',
      optional(array(availableCategoryTypeSchema)),
    ],
  })
);
