/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, unknown } from '../schema.js';
import { TopicList, topicListSchema } from './topicList.js';
import { User, userSchema } from './user.js';

export interface CJsonResponse {
  users?: User[];
  primaryGroups?: unknown[];
  topicList: TopicList;
}

export const cJsonResponseSchema: Schema<CJsonResponse> = lazy(() =>
  object({
    users: ['users', optional(array(userSchema))],
    primaryGroups: ['primary_groups', optional(array(unknown()))],
    topicList: ['topic_list', topicListSchema],
  })
);
