/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface Creator {
  id: number;
  username: string;
  name?: string | null;
  avatarTemplate: string;
}

export const creatorSchema: Schema<Creator> = object({
  id: ['id', number()],
  username: ['username', string()],
  name: ['name', optional(nullable(string()))],
  avatarTemplate: ['avatar_template', string()],
});
