/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Category, categorySchema } from './category.js';

export interface CShowJsonResponse {
  category: Category;
}

export const cShowJsonResponseSchema: Schema<CShowJsonResponse> = lazy(() =>
  object({ category: ['category', categorySchema] })
);
