/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema.js';

export interface CustomFields {
  firstName?: string | null;
}

export const customFieldsSchema: Schema<CustomFields> = object({
  firstName: ['first_name', optional(nullable(string()))],
});
