/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data {
  badgeId?: number;
  badgeName?: string;
  badgeSlug?: string;
  badgeTitle?: boolean;
  username?: string;
  additionalProperties?: Record<string, unknown>;
}

export const dataSchema: Schema<Data> = typedExpandoObject(
  {
    badgeId: ['badge_id', optional(number())],
    badgeName: ['badge_name', optional(string())],
    badgeSlug: ['badge_slug', optional(string())],
    badgeTitle: ['badge_title', optional(boolean())],
    username: ['username', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
