/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
} from '../schema.js';
import { CreatedBy, createdBySchema } from './createdBy.js';
import { LastPoster, lastPosterSchema } from './lastPoster.js';
import { Participant1, participant1Schema } from './participant1.js';

export interface Details {
  canEdit: boolean;
  notificationLevel: number;
  canMovePosts: boolean;
  canDelete: boolean;
  canRemoveAllowedUsers: boolean;
  canCreatePost: boolean;
  canReplyAsNewTopic: boolean;
  canInviteTo?: boolean;
  canInviteViaEmail?: boolean;
  canFlagTopic?: boolean;
  canConvertTopic: boolean;
  canReviewTopic: boolean;
  canCloseTopic: boolean;
  canArchiveTopic: boolean;
  canSplitMergeTopic: boolean;
  canEditStaffNotes: boolean;
  canToggleTopicVisibility: boolean;
  canPinUnpinTopic: boolean;
  canBannerTopic?: boolean;
  canModerateCategory: boolean;
  canRemoveSelfId: number;
  participants?: Participant1[];
  createdBy: CreatedBy;
  lastPoster: LastPoster;
}

export const detailsSchema: Schema<Details> = lazy(() =>
  object({
    canEdit: ['can_edit', boolean()],
    notificationLevel: ['notification_level', number()],
    canMovePosts: ['can_move_posts', boolean()],
    canDelete: ['can_delete', boolean()],
    canRemoveAllowedUsers: ['can_remove_allowed_users', boolean()],
    canCreatePost: ['can_create_post', boolean()],
    canReplyAsNewTopic: ['can_reply_as_new_topic', boolean()],
    canInviteTo: ['can_invite_to', optional(boolean())],
    canInviteViaEmail: ['can_invite_via_email', optional(boolean())],
    canFlagTopic: ['can_flag_topic', optional(boolean())],
    canConvertTopic: ['can_convert_topic', boolean()],
    canReviewTopic: ['can_review_topic', boolean()],
    canCloseTopic: ['can_close_topic', boolean()],
    canArchiveTopic: ['can_archive_topic', boolean()],
    canSplitMergeTopic: ['can_split_merge_topic', boolean()],
    canEditStaffNotes: ['can_edit_staff_notes', boolean()],
    canToggleTopicVisibility: ['can_toggle_topic_visibility', boolean()],
    canPinUnpinTopic: ['can_pin_unpin_topic', boolean()],
    canBannerTopic: ['can_banner_topic', optional(boolean())],
    canModerateCategory: ['can_moderate_category', boolean()],
    canRemoveSelfId: ['can_remove_self_id', number()],
    participants: ['participants', optional(array(participant1Schema))],
    createdBy: ['created_by', createdBySchema],
    lastPoster: ['last_poster', lastPosterSchema],
  })
);
