/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema } from '../schema.js';
import { User11, user11Schema } from './user11.js';

export interface DirectoryItem {
  id: number;
  likesReceived: number;
  likesGiven: number;
  topicsEntered: number;
  topicCount: number;
  postCount: number;
  postsRead: number;
  daysVisited: number;
  user: User11;
}

export const directoryItemSchema: Schema<DirectoryItem> = lazy(() =>
  object({
    id: ['id', number()],
    likesReceived: ['likes_received', number()],
    likesGiven: ['likes_given', number()],
    topicsEntered: ['topics_entered', number()],
    topicCount: ['topic_count', number()],
    postCount: ['post_count', number()],
    postsRead: ['posts_read', number()],
    daysVisited: ['days_visited', number()],
    user: ['user', user11Schema],
  })
);
