/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { DirectoryItem, directoryItemSchema } from './directoryItem.js';
import { Meta1, meta1Schema } from './meta1.js';

export interface DirectoryItemsJsonResponse {
  directoryItems: DirectoryItem[];
  meta: Meta1;
}

export const directoryItemsJsonResponseSchema: Schema<DirectoryItemsJsonResponse> = lazy(
  () =>
    object({
      directoryItems: ['directory_items', array(directoryItemSchema)],
      meta: ['meta', meta1Schema],
    })
);
