/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Event, eventSchema } from './event.js';

export interface DiscoursePostEventEventsJsonResponse {
  events: Event[];
}

export const discoursePostEventEventsJsonResponseSchema: Schema<DiscoursePostEventEventsJsonResponse> = lazy(
  () => object({ events: ['events', array(eventSchema)] })
);
