/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Enabled
 */
export enum Enabled {
  True = 'true',
  False = 'false',
}

/**
 * Schema for Enabled
 */
export const enabledSchema: Schema<Enabled> = stringEnum(Enabled);
