/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { Creator, creatorSchema } from './creator.js';
import { Occurrence, occurrenceSchema } from './occurrence.js';
import { Post, postSchema } from './post.js';
import { Reminder, reminderSchema } from './reminder.js';
import { Status, statusSchema } from './status.js';

export interface Event {
  id: number;
  categoryId: number | null;
  name?: string | null;
  recurrence?: string | null;
  recurrenceUntil?: string | null;
  startsAt: string | null;
  endsAt: string | null;
  rrule?: string;
  showLocalTime: boolean;
  timezone: string | null;
  duration?: string;
  allDay?: boolean;
  customFields?: unknown | null;
  post: Post;
  occurrences: Occurrence[];
  canActOnDiscoursePostEvent: boolean | null;
  canUpdateAttendance: boolean | null;
  creator?: Creator;
  isClosed: boolean;
  isExpired: boolean;
  isOngoing: boolean;
  isPrivate: boolean;
  isPublic: boolean;
  isStandalone: boolean;
  minimal?: boolean | null;
  rawInvitees?: string[] | null;
  reminders?: Reminder[];
  sampleInvitees?: unknown[];
  shouldDisplayInvitees: boolean;
  stats?: unknown;
  status: Status;
  url?: string;
  description?: string | null;
  descriptionHtml?: string | null;
  location?: string | null;
  watchingInvitee?: unknown | null;
  chatEnabled?: boolean | null;
  channel?: unknown;
  livestream?: boolean;
  livestreamOnebox?: string | null;
  isZoomLivestream?: boolean;
  maxAttendees?: number | null;
  atCapacity: boolean;
  imageUpload?: unknown | null;
}

export const eventSchema: Schema<Event> = lazy(() =>
  object({
    id: ['id', number()],
    categoryId: ['category_id', nullable(number())],
    name: ['name', optional(nullable(string()))],
    recurrence: ['recurrence', optional(nullable(string()))],
    recurrenceUntil: ['recurrence_until', optional(nullable(string()))],
    startsAt: ['starts_at', nullable(string())],
    endsAt: ['ends_at', nullable(string())],
    rrule: ['rrule', optional(string())],
    showLocalTime: ['show_local_time', boolean()],
    timezone: ['timezone', nullable(string())],
    duration: ['duration', optional(string())],
    allDay: ['all_day', optional(boolean())],
    customFields: ['custom_fields', optional(nullable(unknown()))],
    post: ['post', postSchema],
    occurrences: ['occurrences', array(occurrenceSchema)],
    canActOnDiscoursePostEvent: [
      'can_act_on_discourse_post_event',
      nullable(boolean()),
    ],
    canUpdateAttendance: ['can_update_attendance', nullable(boolean())],
    creator: ['creator', optional(creatorSchema)],
    isClosed: ['is_closed', boolean()],
    isExpired: ['is_expired', boolean()],
    isOngoing: ['is_ongoing', boolean()],
    isPrivate: ['is_private', boolean()],
    isPublic: ['is_public', boolean()],
    isStandalone: ['is_standalone', boolean()],
    minimal: ['minimal', optional(nullable(boolean()))],
    rawInvitees: ['raw_invitees', optional(nullable(array(string())))],
    reminders: ['reminders', optional(array(reminderSchema))],
    sampleInvitees: ['sample_invitees', optional(array(unknown()))],
    shouldDisplayInvitees: ['should_display_invitees', boolean()],
    stats: ['stats', optional(unknown())],
    status: ['status', statusSchema],
    url: ['url', optional(string())],
    description: ['description', optional(nullable(string()))],
    descriptionHtml: ['description_html', optional(nullable(string()))],
    location: ['location', optional(nullable(string()))],
    watchingInvitee: ['watching_invitee', optional(nullable(unknown()))],
    chatEnabled: ['chat_enabled', optional(nullable(boolean()))],
    channel: ['channel', optional(unknown())],
    livestream: ['livestream', optional(boolean())],
    livestreamOnebox: ['livestream_onebox', optional(nullable(string()))],
    isZoomLivestream: ['is_zoom_livestream', optional(boolean())],
    maxAttendees: ['max_attendees', optional(nullable(number()))],
    atCapacity: ['at_capacity', boolean()],
    imageUpload: ['image_upload', optional(nullable(unknown()))],
  })
);
