/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, unknown } from '../schema.js';

export interface Extras {
  visibleGroupNames: unknown[];
}

export const extrasSchema: Schema<Extras> = object({
  visibleGroupNames: ['visible_group_names', array(unknown())],
});
