/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, unknown } from '../schema.js';

export interface Extras2 {
  typeFilters: unknown[];
}

export const extras2Schema: Schema<Extras2> = object({
  typeFilters: ['type_filters', array(unknown())],
});
