/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Extra {
  categories?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const extraSchema: Schema<Extra> = typedExpandoObject(
  { categories: ['categories', optional(nullable(string()))] },
  'additionalProperties',
  optional(unknown())
);
