/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Extras3 {
  categories?: unknown[];
  additionalProperties?: Record<string, unknown>;
}

export const extras3Schema: Schema<Extras3> = typedExpandoObject(
  { categories: ['categories', optional(array(unknown()))] },
  'additionalProperties',
  optional(unknown())
);
