/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface FeaturedTopic {
  id: number;
  title: string;
  fancyTitle: string;
  slug: string;
  postsCount: number;
}

export const featuredTopicSchema: Schema<FeaturedTopic> = object({
  id: ['id', number()],
  title: ['title', string()],
  fancyTitle: ['fancy_title', string()],
  slug: ['slug', string()],
  postsCount: ['posts_count', number()],
});
