/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Flag
 */
export enum Flag {
  Active = 'active',
  New = 'new',
  Staff = 'staff',
  Suspended = 'suspended',
  Blocked = 'blocked',
  Suspect = 'suspect',
}

/**
 * Schema for Flag
 */
export const flagSchema: Schema<Flag> = stringEnum(Flag);
