/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';

export interface GrantedBy {
  id: number;
  username: string;
  name: string;
  avatarTemplate: string;
  flairName: string | null;
  admin: boolean;
  moderator: boolean;
  trustLevel: number;
}

export const grantedBySchema: Schema<GrantedBy> = object({
  id: ['id', number()],
  username: ['username', string()],
  name: ['name', string()],
  avatarTemplate: ['avatar_template', string()],
  flairName: ['flair_name', nullable(string())],
  admin: ['admin', boolean()],
  moderator: ['moderator', boolean()],
  trustLevel: ['trust_level', number()],
});
