/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface Group {
  name: string;
  fullName?: string;
  /** About Group */
  bioRaw?: string;
  /** comma,separated */
  usernames?: string;
  /** comma,separated */
  ownerUsernames?: string;
  /** pipe|separated */
  automaticMembershipEmailDomains?: string;
  visibilityLevel?: number;
  primaryGroup?: boolean;
  flairIcon?: string;
  flairUploadId?: number;
  flairBgColor?: string;
  publicAdmission?: boolean;
  publicExit?: boolean;
  defaultNotificationLevel?: number;
  mutedCategoryIds?: number[];
  regularCategoryIds?: number[];
  watchingCategoryIds?: number[];
  trackingCategoryIds?: number[];
  watchingFirstPostCategoryIds?: number[];
}

export const groupSchema: Schema<Group> = object({
  name: ['name', string()],
  fullName: ['full_name', optional(string())],
  bioRaw: ['bio_raw', optional(string())],
  usernames: ['usernames', optional(string())],
  ownerUsernames: ['owner_usernames', optional(string())],
  automaticMembershipEmailDomains: [
    'automatic_membership_email_domains',
    optional(string()),
  ],
  visibilityLevel: ['visibility_level', optional(number())],
  primaryGroup: ['primary_group', optional(boolean())],
  flairIcon: ['flair_icon', optional(string())],
  flairUploadId: ['flair_upload_id', optional(number())],
  flairBgColor: ['flair_bg_color', optional(string())],
  publicAdmission: ['public_admission', optional(boolean())],
  publicExit: ['public_exit', optional(boolean())],
  defaultNotificationLevel: ['default_notification_level', optional(number())],
  mutedCategoryIds: ['muted_category_ids', optional(array(number()))],
  regularCategoryIds: ['regular_category_ids', optional(array(number()))],
  watchingCategoryIds: ['watching_category_ids', optional(array(number()))],
  trackingCategoryIds: ['tracking_category_ids', optional(array(number()))],
  watchingFirstPostCategoryIds: [
    'watching_first_post_category_ids',
    optional(array(number())),
  ],
});
