/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema.js';
import { Extras2, extras2Schema } from './extras2.js';
import { Group4, group4Schema } from './group4.js';

export interface GroupsJsonResponse2 {
  groups: Group4[];
  extras: Extras2;
  totalRowsGroups: number;
  loadMoreGroups: string;
}

export const groupsJsonResponse2Schema: Schema<GroupsJsonResponse2> = lazy(() =>
  object({
    groups: ['groups', array(group4Schema)],
    extras: ['extras', extras2Schema],
    totalRowsGroups: ['total_rows_groups', number()],
    loadMoreGroups: ['load_more_groups', string()],
  })
);
