/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Extras, extrasSchema } from './extras.js';
import { Group1, group1Schema } from './group1.js';

export interface GroupsByIdJsonResponse {
  group: Group1;
  extras: Extras;
}

export const groupsByIdJsonResponseSchema: Schema<GroupsByIdJsonResponse> = lazy(
  () =>
    object({ group: ['group', group1Schema], extras: ['extras', extrasSchema] })
);
