/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface Group1 {
  id: number;
  automatic: boolean;
  name: string;
  userCount?: number;
  mentionableLevel: number;
  messageableLevel: number;
  visibilityLevel: number;
  primaryGroup: boolean;
  title: string | null;
  grantTrustLevel: string | null;
  incomingEmail: string | null;
  hasMessages: boolean;
  flairUrl: string | null;
  flairBgColor: string | null;
  flairColor: string | null;
  bioRaw: string | null;
  bioCooked: string | null;
  bioExcerpt: string | null;
  publicAdmission: boolean;
  publicExit: boolean;
  allowMembershipRequests: boolean;
  fullName: string | null;
  defaultNotificationLevel: number;
  membershipRequestTemplate: string | null;
  isGroupUser: boolean;
  membersVisibilityLevel: number;
  canSeeMembers: boolean;
  canAdminGroup: boolean;
  canEditGroup?: boolean;
  publishReadState: boolean;
  isGroupOwnerDisplay: boolean;
  mentionable: boolean;
  messageable: boolean;
  automaticMembershipEmailDomains: string | null;
  smtpUpdatedAt?: string | null;
  smtpUpdatedBy?: unknown | null;
  smtpEnabled?: boolean;
  smtpServer: string | null;
  smtpPort: string | null;
  smtpSslMode: number | null;
  emailUsername: string | null;
  emailFromAlias?: string | null;
  emailPassword: string | null;
  messageCount: number;
  allowUnknownSenderTopicReplies: boolean;
  associatedGroupIds?: unknown[];
  watchingCategoryIds: unknown[];
  trackingCategoryIds: unknown[];
  watchingFirstPostCategoryIds: unknown[];
  regularCategoryIds: unknown[];
  mutedCategoryIds: unknown[];
  watchingTags?: unknown[];
  watchingFirstPostTags?: unknown[];
  trackingTags?: unknown[];
  regularTags?: unknown[];
  mutedTags?: unknown[];
}

export const group1Schema: Schema<Group1> = object({
  id: ['id', number()],
  automatic: ['automatic', boolean()],
  name: ['name', string()],
  userCount: ['user_count', optional(number())],
  mentionableLevel: ['mentionable_level', number()],
  messageableLevel: ['messageable_level', number()],
  visibilityLevel: ['visibility_level', number()],
  primaryGroup: ['primary_group', boolean()],
  title: ['title', nullable(string())],
  grantTrustLevel: ['grant_trust_level', nullable(string())],
  incomingEmail: ['incoming_email', nullable(string())],
  hasMessages: ['has_messages', boolean()],
  flairUrl: ['flair_url', nullable(string())],
  flairBgColor: ['flair_bg_color', nullable(string())],
  flairColor: ['flair_color', nullable(string())],
  bioRaw: ['bio_raw', nullable(string())],
  bioCooked: ['bio_cooked', nullable(string())],
  bioExcerpt: ['bio_excerpt', nullable(string())],
  publicAdmission: ['public_admission', boolean()],
  publicExit: ['public_exit', boolean()],
  allowMembershipRequests: ['allow_membership_requests', boolean()],
  fullName: ['full_name', nullable(string())],
  defaultNotificationLevel: ['default_notification_level', number()],
  membershipRequestTemplate: [
    'membership_request_template',
    nullable(string()),
  ],
  isGroupUser: ['is_group_user', boolean()],
  membersVisibilityLevel: ['members_visibility_level', number()],
  canSeeMembers: ['can_see_members', boolean()],
  canAdminGroup: ['can_admin_group', boolean()],
  canEditGroup: ['can_edit_group', optional(boolean())],
  publishReadState: ['publish_read_state', boolean()],
  isGroupOwnerDisplay: ['is_group_owner_display', boolean()],
  mentionable: ['mentionable', boolean()],
  messageable: ['messageable', boolean()],
  automaticMembershipEmailDomains: [
    'automatic_membership_email_domains',
    nullable(string()),
  ],
  smtpUpdatedAt: ['smtp_updated_at', optional(nullable(string()))],
  smtpUpdatedBy: ['smtp_updated_by', optional(nullable(unknown()))],
  smtpEnabled: ['smtp_enabled', optional(boolean())],
  smtpServer: ['smtp_server', nullable(string())],
  smtpPort: ['smtp_port', nullable(string())],
  smtpSslMode: ['smtp_ssl_mode', nullable(number())],
  emailUsername: ['email_username', nullable(string())],
  emailFromAlias: ['email_from_alias', optional(nullable(string()))],
  emailPassword: ['email_password', nullable(string())],
  messageCount: ['message_count', number()],
  allowUnknownSenderTopicReplies: [
    'allow_unknown_sender_topic_replies',
    boolean(),
  ],
  associatedGroupIds: ['associated_group_ids', optional(array(unknown()))],
  watchingCategoryIds: ['watching_category_ids', array(unknown())],
  trackingCategoryIds: ['tracking_category_ids', array(unknown())],
  watchingFirstPostCategoryIds: [
    'watching_first_post_category_ids',
    array(unknown()),
  ],
  regularCategoryIds: ['regular_category_ids', array(unknown())],
  mutedCategoryIds: ['muted_category_ids', array(unknown())],
  watchingTags: ['watching_tags', optional(array(unknown()))],
  watchingFirstPostTags: [
    'watching_first_post_tags',
    optional(array(unknown())),
  ],
  trackingTags: ['tracking_tags', optional(array(unknown()))],
  regularTags: ['regular_tags', optional(array(unknown()))],
  mutedTags: ['muted_tags', optional(array(unknown()))],
});
