/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface GroupsMembersJsonRequest {
  /** comma separated list */
  usernames?: string;
}

export const groupsMembersJsonRequestSchema: Schema<GroupsMembersJsonRequest> = object(
  { usernames: ['usernames', optional(string())] }
);
