/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface GroupPermission {
  permissionType: number;
  groupName: string;
  groupId: number;
}

export const groupPermissionSchema: Schema<GroupPermission> = object({
  permissionType: ['permission_type', number()],
  groupName: ['group_name', string()],
  groupId: ['group_id', number()],
});
