/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Group6 {
  id?: number;
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const group6Schema: Schema<Group6> = typedExpandoObject(
  { id: ['id', optional(number())], name: ['name', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
