/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface GroupsJsonResponse1 {
  success: string;
}

export const groupsJsonResponse1Schema: Schema<GroupsJsonResponse1> = object({
  success: ['success', string()],
});
