/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema.js';

export interface GroupUser {
  groupId: number;
  userId: number;
  notificationLevel: number;
  owner?: boolean;
}

export const groupUserSchema: Schema<GroupUser> = object({
  groupId: ['group_id', number()],
  userId: ['user_id', number()],
  notificationLevel: ['notification_level', number()],
  owner: ['owner', optional(boolean())],
});
