/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Group, groupSchema } from './group.js';

export interface GroupsJsonRequest {
  group: Group;
}

export const groupsJsonRequestSchema: Schema<GroupsJsonRequest> = lazy(() =>
  object({ group: ['group', groupSchema] })
);
