/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema.js';

export interface GroupsMembersJsonResponse1 {
  success: string;
  usernames: unknown[];
  emails: unknown[];
}

export const groupsMembersJsonResponse1Schema: Schema<GroupsMembersJsonResponse1> = object(
  {
    success: ['success', string()],
    usernames: ['usernames', array(unknown())],
    emails: ['emails', array(unknown())],
  }
);
