/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Member, memberSchema } from './member.js';
import { Meta, metaSchema } from './meta.js';
import { Owner, ownerSchema } from './owner.js';

export interface GroupsMembersJsonResponse {
  members: Member[];
  owners: Owner[];
  meta: Meta;
}

export const groupsMembersJsonResponseSchema: Schema<GroupsMembersJsonResponse> = lazy(
  () =>
    object({
      members: ['members', array(memberSchema)],
      owners: ['owners', array(ownerSchema)],
      meta: ['meta', metaSchema],
    })
);
