/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { Extra, extraSchema } from './extra.js';

export interface GroupedSearchResult {
  morePosts: string | null;
  moreUsers: string | null;
  moreCategories: string | null;
  term: string;
  searchLogId: number;
  moreFullPageResults: string | null;
  canCreateTopic: boolean;
  error: string | null;
  extra?: Extra;
  postIds: unknown[];
  userIds: unknown[];
  categoryIds: unknown[];
  tagIds: unknown[];
  groupIds: unknown[];
}

export const groupedSearchResultSchema: Schema<GroupedSearchResult> = lazy(() =>
  object({
    morePosts: ['more_posts', nullable(string())],
    moreUsers: ['more_users', nullable(string())],
    moreCategories: ['more_categories', nullable(string())],
    term: ['term', string()],
    searchLogId: ['search_log_id', number()],
    moreFullPageResults: ['more_full_page_results', nullable(string())],
    canCreateTopic: ['can_create_topic', boolean()],
    error: ['error', nullable(string())],
    extra: ['extra', optional(extraSchema)],
    postIds: ['post_ids', array(unknown())],
    userIds: ['user_ids', array(unknown())],
    categoryIds: ['category_ids', array(unknown())],
    tagIds: ['tag_ids', array(unknown())],
    groupIds: ['group_ids', array(unknown())],
  })
);
