/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface Group5 {
  id: number;
  name: string;
  fullName?: string;
  displayName?: string;
  flairUrl: string | null;
  flairBgColor: string | null;
  flairColor: string | null;
  automatic: boolean;
}

export const group5Schema: Schema<Group5> = object({
  id: ['id', number()],
  name: ['name', string()],
  fullName: ['full_name', optional(string())],
  displayName: ['display_name', optional(string())],
  flairUrl: ['flair_url', nullable(string())],
  flairBgColor: ['flair_bg_color', nullable(string())],
  flairColor: ['flair_color', nullable(string())],
  automatic: ['automatic', boolean()],
});
