/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema.js';

export interface GroupsMembersJsonResponse2 {
  success: string;
  usernames: unknown[];
  skippedUsernames: unknown[];
}

export const groupsMembersJsonResponse2Schema: Schema<GroupsMembersJsonResponse2> = object(
  {
    success: ['success', string()],
    usernames: ['usernames', array(unknown())],
    skippedUsernames: ['skipped_usernames', array(unknown())],
  }
);
