/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IncludeDetails
 */
export enum IncludeDetails {
  True = 'true',
  False = 'false',
}

/**
 * Schema for IncludeDetails
 */
export const includeDetailsSchema: Schema<IncludeDetails> = stringEnum(
  IncludeDetails
);
