/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IncludeSubcategories
 */
export enum IncludeSubcategories {
  True = 'true',
  False = 'false',
}

/**
 * Schema for IncludeSubcategories
 */
export const includeSubcategoriesSchema: Schema<IncludeSubcategories> = stringEnum(
  IncludeSubcategories
);
