/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InvitesCreateMultipleJsonRequest {
  /**
   * pass 1 email per invite to be generated. other properties
   * will be shared by each invite.
   */
  email?: string;
  skipEmail?: boolean;
  /** optional, for email invites */
  customMessage?: string;
  /** optional, for link invites */
  maxRedemptionsAllowed?: number;
  topicId?: number;
  /**
   * Optional, either this or `group_names`. Comma separated
   * list for multiple ids.
   */
  groupIds?: string;
  /**
   * Optional, either this or `group_ids`. Comma separated
   * list for multiple names.
   */
  groupNames?: string;
  /**
   * optional, if not supplied, the invite_expiry_days site
   * setting is used
   */
  expiresAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const invitesCreateMultipleJsonRequestSchema: Schema<InvitesCreateMultipleJsonRequest> = typedExpandoObject(
  {
    email: ['email', optional(string())],
    skipEmail: ['skip_email', optional(boolean())],
    customMessage: ['custom_message', optional(string())],
    maxRedemptionsAllowed: ['max_redemptions_allowed', optional(number())],
    topicId: ['topic_id', optional(number())],
    groupIds: ['group_ids', optional(string())],
    groupNames: ['group_names', optional(string())],
    expiresAt: ['expires_at', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
