/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InvitesCreateMultipleJsonResponse {
  numSuccessfullyCreatedInvitations?: number;
  numFailedInvitations?: number;
  failedInvitations?: unknown[];
  successfulInvitations?: unknown[];
  additionalProperties?: Record<string, unknown>;
}

export const invitesCreateMultipleJsonResponseSchema: Schema<InvitesCreateMultipleJsonResponse> = typedExpandoObject(
  {
    numSuccessfullyCreatedInvitations: [
      'num_successfully_created_invitations',
      optional(number()),
    ],
    numFailedInvitations: ['num_failed_invitations', optional(number())],
    failedInvitations: ['failed_invitations', optional(array(unknown()))],
    successfulInvitations: [
      'successful_invitations',
      optional(array(unknown())),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
