/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface InvitesJsonResponse {
  id: number;
  inviteKey: string;
  link: string;
  description: string | null;
  email: string;
  domain: string | null;
  emailed: boolean;
  canDeleteInvite: boolean;
  customMessage: string | null;
  createdAt: string;
  updatedAt: string;
  expiresAt: string;
  expired: boolean;
  grantsAdmin: boolean;
  grantsModerator: boolean;
  topics: unknown[];
  groups: unknown[];
}

export const invitesJsonResponseSchema: Schema<InvitesJsonResponse> = object({
  id: ['id', number()],
  inviteKey: ['invite_key', string()],
  link: ['link', string()],
  description: ['description', nullable(string())],
  email: ['email', string()],
  domain: ['domain', nullable(string())],
  emailed: ['emailed', boolean()],
  canDeleteInvite: ['can_delete_invite', boolean()],
  customMessage: ['custom_message', nullable(string())],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  expiresAt: ['expires_at', string()],
  expired: ['expired', boolean()],
  grantsAdmin: ['grants_admin', boolean()],
  grantsModerator: ['grants_moderator', boolean()],
  topics: ['topics', array(unknown())],
  groups: ['groups', array(unknown())],
});
