/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TopicList4, topicList4Schema } from './topicList4.js';
import { User2, user2Schema } from './user2.js';

export interface LatestJsonResponse {
  users?: User2[];
  primaryGroups?: unknown[];
  topicList?: TopicList4;
  additionalProperties?: Record<string, unknown>;
}

export const latestJsonResponseSchema: Schema<LatestJsonResponse> = lazy(() =>
  typedExpandoObject(
    {
      users: ['users', optional(array(user2Schema))],
      primaryGroups: ['primary_groups', optional(array(unknown()))],
      topicList: ['topic_list', optional(topicList4Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
