/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { ActionsSummary, actionsSummarySchema } from './actionsSummary.js';

export interface LatestPost {
  id: number;
  name: string | null;
  username: string;
  avatarTemplate: string;
  createdAt: string;
  cooked: string;
  postNumber: number;
  postType: number;
  postsCount: number;
  updatedAt: string;
  replyCount: number;
  replyToPostNumber: string | null;
  quoteCount: number;
  incomingLinkCount: number;
  reads: number;
  readersCount: number;
  score: number;
  yours: boolean;
  topicId: number;
  topicSlug: string;
  topicTitle: string;
  topicHtmlTitle: string;
  categoryId: number;
  displayUsername: string | null;
  primaryGroupName: string | null;
  flairName: string | null;
  flairUrl: string | null;
  flairBgColor: string | null;
  flairColor: string | null;
  flairGroupId: string | null;
  badgesGranted: unknown[];
  version: number;
  canEdit: boolean;
  canDelete: boolean;
  canRecover: boolean;
  canSeeHiddenPost: boolean;
  canWiki: boolean;
  userTitle: string | null;
  bookmarked: boolean;
  raw: string;
  actionsSummary: ActionsSummary[];
  moderator: boolean;
  admin: boolean;
  staff: boolean;
  userId: number;
  hidden: boolean;
  trustLevel: number;
  deletedAt: string | null;
  userDeleted: boolean;
  editReason: string | null;
  canViewEditHistory: boolean;
  wiki: boolean;
  excerpt: string;
  truncated: boolean;
  reviewableId: string | null;
  reviewableScoreCount: number;
  reviewableScorePendingCount: number;
  postUrl: string;
}

export const latestPostSchema: Schema<LatestPost> = lazy(() =>
  object({
    id: ['id', number()],
    name: ['name', nullable(string())],
    username: ['username', string()],
    avatarTemplate: ['avatar_template', string()],
    createdAt: ['created_at', string()],
    cooked: ['cooked', string()],
    postNumber: ['post_number', number()],
    postType: ['post_type', number()],
    postsCount: ['posts_count', number()],
    updatedAt: ['updated_at', string()],
    replyCount: ['reply_count', number()],
    replyToPostNumber: ['reply_to_post_number', nullable(string())],
    quoteCount: ['quote_count', number()],
    incomingLinkCount: ['incoming_link_count', number()],
    reads: ['reads', number()],
    readersCount: ['readers_count', number()],
    score: ['score', number()],
    yours: ['yours', boolean()],
    topicId: ['topic_id', number()],
    topicSlug: ['topic_slug', string()],
    topicTitle: ['topic_title', string()],
    topicHtmlTitle: ['topic_html_title', string()],
    categoryId: ['category_id', number()],
    displayUsername: ['display_username', nullable(string())],
    primaryGroupName: ['primary_group_name', nullable(string())],
    flairName: ['flair_name', nullable(string())],
    flairUrl: ['flair_url', nullable(string())],
    flairBgColor: ['flair_bg_color', nullable(string())],
    flairColor: ['flair_color', nullable(string())],
    flairGroupId: ['flair_group_id', nullable(string())],
    badgesGranted: ['badges_granted', array(unknown())],
    version: ['version', number()],
    canEdit: ['can_edit', boolean()],
    canDelete: ['can_delete', boolean()],
    canRecover: ['can_recover', boolean()],
    canSeeHiddenPost: ['can_see_hidden_post', boolean()],
    canWiki: ['can_wiki', boolean()],
    userTitle: ['user_title', nullable(string())],
    bookmarked: ['bookmarked', boolean()],
    raw: ['raw', string()],
    actionsSummary: ['actions_summary', array(actionsSummarySchema)],
    moderator: ['moderator', boolean()],
    admin: ['admin', boolean()],
    staff: ['staff', boolean()],
    userId: ['user_id', number()],
    hidden: ['hidden', boolean()],
    trustLevel: ['trust_level', number()],
    deletedAt: ['deleted_at', nullable(string())],
    userDeleted: ['user_deleted', boolean()],
    editReason: ['edit_reason', nullable(string())],
    canViewEditHistory: ['can_view_edit_history', boolean()],
    wiki: ['wiki', boolean()],
    excerpt: ['excerpt', string()],
    truncated: ['truncated', boolean()],
    reviewableId: ['reviewable_id', nullable(string())],
    reviewableScoreCount: ['reviewable_score_count', number()],
    reviewableScorePendingCount: ['reviewable_score_pending_count', number()],
    postUrl: ['post_url', string()],
  })
);
