/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema.js';

export interface LinkCount {
  url: string;
  internal: boolean;
  reflection: boolean;
  title: string;
  clicks: number;
}

export const linkCountSchema: Schema<LinkCount> = object({
  url: ['url', string()],
  internal: ['internal', boolean()],
  reflection: ['reflection', boolean()],
  title: ['title', string()],
  clicks: ['clicks', number()],
});
