/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema.js';

export interface Meta1 {
  lastUpdatedAt: string | null;
  totalRowsDirectoryItems: number;
  loadMoreDirectoryItems: string;
}

export const meta1Schema: Schema<Meta1> = object({
  lastUpdatedAt: ['last_updated_at', nullable(string())],
  totalRowsDirectoryItems: ['total_rows_directory_items', number()],
  loadMoreDirectoryItems: ['load_more_directory_items', string()],
});
