/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Metadata {
  /**
   * The SHA1 checksum of the upload binary blob. Optionally
   * be provided and serves as an additional security check when
   * later processing the file in complete-external-upload endpoint.
   */
  sha1Checksum?: string;
}

export const metadataSchema: Schema<Metadata> = object({
  sha1Checksum: ['sha1-checksum', optional(string())],
});
