/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface Meta {
  total: number;
  limit: number;
  offset: number;
}

export const metaSchema: Schema<Meta> = object({
  total: ['total', number()],
  limit: ['limit', number()],
  offset: ['offset', number()],
});
