/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

export interface NotificationTypes {
  mentioned: number;
  replied: number;
  quoted: number;
  edited: number;
  liked: number;
  privateMessage: number;
  invitedToPrivateMessage: number;
  inviteeAccepted: number;
  posted: number;
  watchingCategoryOrTag: number;
  newFeatures?: number;
  adminProblems?: number;
  movedPost: number;
  linked: number;
  grantedBadge: number;
  invitedToTopic: number;
  custom: number;
  groupMentioned: number;
  groupMessageSummary: number;
  watchingFirstPost: number;
  topicReminder: number;
  likedConsolidated: number;
  linkedConsolidated: number;
  postApproved: number;
  codeReviewCommitApproved: number;
  membershipRequestAccepted: number;
  membershipRequestConsolidated: number;
  bookmarkReminder: number;
  reaction: number;
  votesReleased: number;
  eventReminder: number;
  eventInvitation: number;
  chatMention: number;
  chatMessage: number;
  chatInvitation: number;
  chatGroupMention: number;
  chatQuoted?: number;
  chatWatchedThread?: number;
  upcomingChangeAvailable?: number;
  upcomingChangeAutomaticallyPromoted?: number;
  assigned?: number;
  questionAnswerUserCommented?: number;
  following?: number;
  followingCreatedTopic?: number;
  followingReplied?: number;
  circlesActivity?: number;
  boost?: number;
  suggestedEditCreated?: number;
  suggestedEditAccepted?: number;
}

export const notificationTypesSchema: Schema<NotificationTypes> = object({
  mentioned: ['mentioned', number()],
  replied: ['replied', number()],
  quoted: ['quoted', number()],
  edited: ['edited', number()],
  liked: ['liked', number()],
  privateMessage: ['private_message', number()],
  invitedToPrivateMessage: ['invited_to_private_message', number()],
  inviteeAccepted: ['invitee_accepted', number()],
  posted: ['posted', number()],
  watchingCategoryOrTag: ['watching_category_or_tag', number()],
  newFeatures: ['new_features', optional(number())],
  adminProblems: ['admin_problems', optional(number())],
  movedPost: ['moved_post', number()],
  linked: ['linked', number()],
  grantedBadge: ['granted_badge', number()],
  invitedToTopic: ['invited_to_topic', number()],
  custom: ['custom', number()],
  groupMentioned: ['group_mentioned', number()],
  groupMessageSummary: ['group_message_summary', number()],
  watchingFirstPost: ['watching_first_post', number()],
  topicReminder: ['topic_reminder', number()],
  likedConsolidated: ['liked_consolidated', number()],
  linkedConsolidated: ['linked_consolidated', number()],
  postApproved: ['post_approved', number()],
  codeReviewCommitApproved: ['code_review_commit_approved', number()],
  membershipRequestAccepted: ['membership_request_accepted', number()],
  membershipRequestConsolidated: ['membership_request_consolidated', number()],
  bookmarkReminder: ['bookmark_reminder', number()],
  reaction: ['reaction', number()],
  votesReleased: ['votes_released', number()],
  eventReminder: ['event_reminder', number()],
  eventInvitation: ['event_invitation', number()],
  chatMention: ['chat_mention', number()],
  chatMessage: ['chat_message', number()],
  chatInvitation: ['chat_invitation', number()],
  chatGroupMention: ['chat_group_mention', number()],
  chatQuoted: ['chat_quoted', optional(number())],
  chatWatchedThread: ['chat_watched_thread', optional(number())],
  upcomingChangeAvailable: ['upcoming_change_available', optional(number())],
  upcomingChangeAutomaticallyPromoted: [
    'upcoming_change_automatically_promoted',
    optional(number()),
  ],
  assigned: ['assigned', optional(number())],
  questionAnswerUserCommented: [
    'question_answer_user_commented',
    optional(number()),
  ],
  following: ['following', optional(number())],
  followingCreatedTopic: ['following_created_topic', optional(number())],
  followingReplied: ['following_replied', optional(number())],
  circlesActivity: ['circles_activity', optional(number())],
  boost: ['boost', optional(number())],
  suggestedEditCreated: ['suggested_edit_created', optional(number())],
  suggestedEditAccepted: ['suggested_edit_accepted', optional(number())],
});
