/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface NotificationsMarkReadJsonRequest {
  /**
   * (optional) Leave off to mark all notifications as
   * read
   */
  id?: number;
  additionalProperties?: Record<string, unknown>;
}

export const notificationsMarkReadJsonRequestSchema: Schema<NotificationsMarkReadJsonRequest> = typedExpandoObject(
  { id: ['id', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
