/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Notification, notificationSchema } from './notification.js';

export interface NotificationsJsonResponse {
  notifications?: Notification[];
  totalRowsNotifications?: number;
  seenNotificationId?: number;
  loadMoreNotifications?: string;
  additionalProperties?: Record<string, unknown>;
}

export const notificationsJsonResponseSchema: Schema<NotificationsJsonResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        notifications: ['notifications', optional(array(notificationSchema))],
        totalRowsNotifications: [
          'total_rows_notifications',
          optional(number()),
        ],
        seenNotificationId: ['seen_notification_id', optional(number())],
        loadMoreNotifications: ['load_more_notifications', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
