/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NotificationLevel
 */
export enum NotificationLevel {
  Enum0 = '0',
  Enum1 = '1',
  Enum2 = '2',
  Enum3 = '3',
}

/**
 * Schema for NotificationLevel
 */
export const notificationLevelSchema: Schema<NotificationLevel> = stringEnum(
  NotificationLevel
);
