/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data, dataSchema } from './data.js';

export interface Notification {
  id?: number;
  userId?: number;
  notificationType?: number;
  read?: boolean;
  createdAt?: string;
  postNumber?: number | null;
  topicId?: number | null;
  slug?: string | null;
  data?: Data;
  additionalProperties?: Record<string, unknown>;
}

export const notificationSchema: Schema<Notification> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', optional(number())],
      userId: ['user_id', optional(number())],
      notificationType: ['notification_type', optional(number())],
      read: ['read', optional(boolean())],
      createdAt: ['created_at', optional(string())],
      postNumber: ['post_number', optional(nullable(number()))],
      topicId: ['topic_id', optional(nullable(number()))],
      slug: ['slug', optional(nullable(string()))],
      data: ['data', optional(dataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
