import * as s from "../core/validation/index.js";
import type { Schema } from "../core/validation/schema.js";

export type NotificationTypes = {
  mentioned: number;
  replied: number;
  quoted: number;
  edited: number;
  liked: number;
  privateMessage: number;
  invitedToPrivateMessage: number;
  inviteeAccepted: number;
  posted: number;
  watchingCategoryOrTag: number;
  newFeatures?: number;
  adminProblems?: number;
  movedPost: number;
  linked: number;
  grantedBadge: number;
  invitedToTopic: number;
  custom: number;
  groupMentioned: number;
  groupMessageSummary: number;
  watchingFirstPost: number;
  topicReminder: number;
  likedConsolidated: number;
  linkedConsolidated: number;
  postApproved: number;
  codeReviewCommitApproved: number;
  membershipRequestAccepted: number;
  membershipRequestConsolidated: number;
  bookmarkReminder: number;
  reaction: number;
  votesReleased: number;
  eventReminder: number;
  eventInvitation: number;
  chatMention: number;
  chatMessage: number;
  chatInvitation: number;
  chatGroupMention: number;
  chatQuoted?: number;
  chatWatchedThread?: number;
  upcomingChangeAvailable?: number;
  upcomingChangeAutomaticallyPromoted?: number;
  assigned?: number;
  questionAnswerUserCommented?: number;
  following?: number;
  followingCreatedTopic?: number;
  followingReplied?: number;
  circlesActivity?: number;
  boost?: number;
  suggestedEditCreated?: number;
  suggestedEditAccepted?: number;
};

export const notificationTypesSchema: Schema<NotificationTypes> = s.object<NotificationTypes>({
  mentioned: s.number(),
  replied: s.number(),
  quoted: s.number(),
  edited: s.number(),
  liked: s.number(),
  privateMessage: s.number(),
  invitedToPrivateMessage: s.number(),
  inviteeAccepted: s.number(),
  posted: s.number(),
  watchingCategoryOrTag: s.number(),
  newFeatures: s.optional(s.number()),
  adminProblems: s.optional(s.number()),
  movedPost: s.number(),
  linked: s.number(),
  grantedBadge: s.number(),
  invitedToTopic: s.number(),
  custom: s.number(),
  groupMentioned: s.number(),
  groupMessageSummary: s.number(),
  watchingFirstPost: s.number(),
  topicReminder: s.number(),
  likedConsolidated: s.number(),
  linkedConsolidated: s.number(),
  postApproved: s.number(),
  codeReviewCommitApproved: s.number(),
  membershipRequestAccepted: s.number(),
  membershipRequestConsolidated: s.number(),
  bookmarkReminder: s.number(),
  reaction: s.number(),
  votesReleased: s.number(),
  eventReminder: s.number(),
  eventInvitation: s.number(),
  chatMention: s.number(),
  chatMessage: s.number(),
  chatInvitation: s.number(),
  chatGroupMention: s.number(),
  chatQuoted: s.optional(s.number()),
  chatWatchedThread: s.optional(s.number()),
  upcomingChangeAvailable: s.optional(s.number()),
  upcomingChangeAutomaticallyPromoted: s.optional(s.number()),
  assigned: s.optional(s.number()),
  questionAnswerUserCommented: s.optional(s.number()),
  following: s.optional(s.number()),
  followingCreatedTopic: s.optional(s.number()),
  followingReplied: s.optional(s.number()),
  circlesActivity: s.optional(s.number()),
  boost: s.optional(s.number()),
  suggestedEditCreated: s.optional(s.number()),
  suggestedEditAccepted: s.optional(s.number()),
  _keysMap: {
    privateMessage: "private_message",
    invitedToPrivateMessage: "invited_to_private_message",
    inviteeAccepted: "invitee_accepted",
    watchingCategoryOrTag: "watching_category_or_tag",
    newFeatures: "new_features",
    adminProblems: "admin_problems",
    movedPost: "moved_post",
    grantedBadge: "granted_badge",
    invitedToTopic: "invited_to_topic",
    groupMentioned: "group_mentioned",
    groupMessageSummary: "group_message_summary",
    watchingFirstPost: "watching_first_post",
    topicReminder: "topic_reminder",
    likedConsolidated: "liked_consolidated",
    linkedConsolidated: "linked_consolidated",
    postApproved: "post_approved",
    codeReviewCommitApproved: "code_review_commit_approved",
    membershipRequestAccepted: "membership_request_accepted",
    membershipRequestConsolidated: "membership_request_consolidated",
    bookmarkReminder: "bookmark_reminder",
    votesReleased: "votes_released",
    eventReminder: "event_reminder",
    eventInvitation: "event_invitation",
    chatMention: "chat_mention",
    chatMessage: "chat_message",
    chatInvitation: "chat_invitation",
    chatGroupMention: "chat_group_mention",
    chatQuoted: "chat_quoted",
    chatWatchedThread: "chat_watched_thread",
    upcomingChangeAvailable: "upcoming_change_available",
    upcomingChangeAutomaticallyPromoted: "upcoming_change_automatically_promoted",
    questionAnswerUserCommented: "question_answer_user_commented",
    followingCreatedTopic: "following_created_topic",
    followingReplied: "following_replied",
    circlesActivity: "circles_activity",
    suggestedEditCreated: "suggested_edit_created",
    suggestedEditAccepted: "suggested_edit_accepted",
  },
});
