/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema.js';

export interface Occurrence {
  startsAt: string | null;
  endsAt: string | null;
}

export const occurrenceSchema: Schema<Occurrence> = object({
  startsAt: ['starts_at', nullable(string())],
  endsAt: ['ends_at', nullable(string())],
});
