/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

export interface OptimizedVideo {
  id?: number;
  uploadId?: number;
  url?: string;
  extension?: string;
  filesize?: number;
  sha1?: string;
  originalFilename?: string;
}

export const optimizedVideoSchema: Schema<OptimizedVideo> = object({
  id: ['id', optional(number())],
  uploadId: ['upload_id', optional(number())],
  url: ['url', optional(string())],
  extension: ['extension', optional(string())],
  filesize: ['filesize', optional(number())],
  sha1: ['sha1', optional(string())],
  originalFilename: ['original_filename', optional(string())],
});
