/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Order3
 */
export enum Order3 {
  Created = 'created',
  LastEmailed = 'last_emailed',
  Seen = 'seen',
  Username = 'username',
  Email = 'email',
  TrustLevel = 'trust_level',
  DaysVisited = 'days_visited',
  PostsRead = 'posts_read',
  TopicsViewed = 'topics_viewed',
  Posts = 'posts',
  ReadTime = 'read_time',
}

/**
 * Schema for Order3
 */
export const order3Schema: Schema<Order3> = stringEnum(Order3);
