/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Order2
 */
export enum Order2 {
  LikesReceived = 'likes_received',
  LikesGiven = 'likes_given',
  TopicCount = 'topic_count',
  PostCount = 'post_count',
  TopicsEntered = 'topics_entered',
  PostsRead = 'posts_read',
  DaysVisited = 'days_visited',
}

/**
 * Schema for Order2
 */
export const order2Schema: Schema<Order2> = stringEnum(Order2);
