/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Order
 */
export enum Order {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for Order
 */
export const orderSchema: Schema<Order> = stringEnum(Order);
