/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema.js';

export interface Owner {
  id: number;
  username: string;
  name: string | null;
  avatarTemplate: string;
  title: string | null;
  lastPostedAt: string;
  lastSeenAt: string;
  addedAt: string;
  timezone: string;
}

export const ownerSchema: Schema<Owner> = object({
  id: ['id', number()],
  username: ['username', string()],
  name: ['name', nullable(string())],
  avatarTemplate: ['avatar_template', string()],
  title: ['title', nullable(string())],
  lastPostedAt: ['last_posted_at', string()],
  lastSeenAt: ['last_seen_at', string()],
  addedAt: ['added_at', string()],
  timezone: ['timezone', string()],
});
