/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface ParentTag {
  id: number;
  name: string;
  slug: string;
}

export const parentTagSchema: Schema<ParentTag> = object({
  id: ['id', number()],
  name: ['name', string()],
  slug: ['slug', string()],
});
