/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface Participant1 {
  id: number;
  username: string;
  name: string;
  avatarTemplate: string;
  postCount: number;
  primaryGroupName: string | null;
  flairName: string | null;
  flairUrl: string | null;
  flairColor: string | null;
  flairBgColor: string | null;
  flairGroupId?: number | null;
  admin: boolean;
  moderator: boolean;
  trustLevel: number;
}

export const participant1Schema: Schema<Participant1> = object({
  id: ['id', number()],
  username: ['username', string()],
  name: ['name', string()],
  avatarTemplate: ['avatar_template', string()],
  postCount: ['post_count', number()],
  primaryGroupName: ['primary_group_name', nullable(string())],
  flairName: ['flair_name', nullable(string())],
  flairUrl: ['flair_url', nullable(string())],
  flairColor: ['flair_color', nullable(string())],
  flairBgColor: ['flair_bg_color', nullable(string())],
  flairGroupId: ['flair_group_id', optional(nullable(number()))],
  admin: ['admin', boolean()],
  moderator: ['moderator', boolean()],
  trustLevel: ['trust_level', number()],
});
