/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Participant {
  extras?: string;
  description?: string | null;
  userId?: number;
  primaryGroupId?: number | null;
  additionalProperties?: Record<string, unknown>;
}

export const participantSchema: Schema<Participant> = typedExpandoObject(
  {
    extras: ['extras', optional(string())],
    description: ['description', optional(nullable(string()))],
    userId: ['user_id', optional(number())],
    primaryGroupId: ['primary_group_id', optional(nullable(number()))],
  },
  'additionalProperties',
  optional(unknown())
);
