/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface PenaltyCounts1 {
  silenced: number;
  suspended: number;
  total: number;
}

export const penaltyCounts1Schema: Schema<PenaltyCounts1> = object({
  silenced: ['silenced', number()],
  suspended: ['suspended', number()],
  total: ['total', number()],
});
