/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface PenaltyCounts {
  silenced: number;
  suspended: number;
}

export const penaltyCountsSchema: Schema<PenaltyCounts> = object({
  silenced: ['silenced', number()],
  suspended: ['suspended', number()],
});
