/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Period
 */
export enum Period {
  Before = 'before',
  After = 'after',
}

/**
 * Schema for Period
 */
export const periodSchema: Schema<Period> = stringEnum(Period);
