/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Period1
 */
export enum Period1 {
  Daily = 'daily',
  Weekly = 'weekly',
  Monthly = 'monthly',
  Quarterly = 'quarterly',
  Yearly = 'yearly',
  All = 'all',
}

/**
 * Schema for Period1
 */
export const period1Schema: Schema<Period1> = stringEnum(Period1);
