/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Permissions {
  everyone?: number;
  staff?: number;
  additionalProperties?: Record<string, unknown>;
}

export const permissionsSchema: Schema<Permissions> = typedExpandoObject(
  {
    everyone: ['everyone', optional(number())],
    staff: ['staff', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
