/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

export interface PostsJsonRequest2 {
  /**
   * The `SiteSetting.can_permanently_delete` needs to be
   * enabled first before this param can be used. Also this endpoint
   * needs to be called first without `force_destroy` and then followed
   * up with a second call 5 minutes later with `force_destroy` to
   * permanently delete.
   */
  forceDestroy?: boolean;
}

export const postsJsonRequest2Schema: Schema<PostsJsonRequest2> = object({
  forceDestroy: ['force_destroy', optional(boolean())],
});
