/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PostsLockedJsonResponse {
  /** Whether the post is locked */
  locked: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const postsLockedJsonResponseSchema: Schema<PostsLockedJsonResponse> = typedExpandoObject(
  { locked: ['locked', boolean()] },
  'additionalProperties',
  optional(unknown())
);
