/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { LatestPost, latestPostSchema } from './latestPost.js';

export interface PostsJsonResponse {
  latestPosts: LatestPost[];
}

export const postsJsonResponseSchema: Schema<PostsJsonResponse> = lazy(() =>
  object({ latestPosts: ['latest_posts', array(latestPostSchema)] })
);
