/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import { Post1, post1Schema } from './post1.js';

export interface PostsJsonRequest1 {
  post?: Post1;
  /**
   * Skip bumping the topic when updating the post. Requires
   * staff or TL4 permissions.
   */
  bypassBump?: boolean;
}

export const postsJsonRequest1Schema: Schema<PostsJsonRequest1> = lazy(() =>
  object({
    post: ['post', optional(post1Schema)],
    bypassBump: ['bypass_bump', optional(boolean())],
  })
);
