/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface PostsJsonRequest {
  /** Required if creating a new topic or new private message. */
  title?: string;
  raw: string;
  /** Required if creating a new post. */
  topicId?: number;
  /**
   * Optional if creating a new topic, and ignored if creating
   * a new post.
   */
  category?: number;
  /** Required for private message, comma separated. */
  targetRecipients?: string;
  /** Deprecated. Use target_recipients instead. */
  targetUsernames?: string;
  /** Required for new private message. */
  archetype?: string;
  createdAt?: string;
  /** Optional, the post number to reply to inside a topic. */
  replyToPostNumber?: number;
  /**
   * Provide a URL from a remote system to associate a forum
   * topic with that URL, typically for using Discourse as a comments
   * system for an external blog.
   */
  embedUrl?: string;
  /**
   * Provide an external_id from a remote system to associate
   * a forum topic with that id.
   */
  externalId?: string;
  /**
   * If false, the user will not track the topic. By default,
   * the user will track the topic.
   */
  autoTrack?: boolean;
}

export const postsJsonRequestSchema: Schema<PostsJsonRequest> = object({
  title: ['title', optional(string())],
  raw: ['raw', string()],
  topicId: ['topic_id', optional(number())],
  category: ['category', optional(number())],
  targetRecipients: ['target_recipients', optional(string())],
  targetUsernames: ['target_usernames', optional(string())],
  archetype: ['archetype', optional(string())],
  createdAt: ['created_at', optional(string())],
  replyToPostNumber: ['reply_to_post_number', optional(number())],
  embedUrl: ['embed_url', optional(string())],
  externalId: ['external_id', optional(string())],
  autoTrack: ['auto_track', optional(boolean())],
});
