/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Poster1 {
  extras?: string;
  description?: string;
  userId?: number;
  primaryGroupId?: number | null;
  additionalProperties?: Record<string, unknown>;
}

export const poster1Schema: Schema<Poster1> = typedExpandoObject(
  {
    extras: ['extras', optional(string())],
    description: ['description', optional(string())],
    userId: ['user_id', optional(number())],
    primaryGroupId: ['primary_group_id', optional(nullable(number()))],
  },
  'additionalProperties',
  optional(unknown())
);
