/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface PostTypes {
  regular: number;
  moderatorAction: number;
  smallAction: number;
  whisper: number;
}

export const postTypesSchema: Schema<PostTypes> = object({
  regular: ['regular', number()],
  moderatorAction: ['moderator_action', number()],
  smallAction: ['small_action', number()],
  whisper: ['whisper', number()],
});
