/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, unknown } from '../schema.js';
import { Post4, post4Schema } from './post4.js';

export interface PostStream1 {
  posts: Post4[];
  stream: unknown[];
}

export const postStream1Schema: Schema<PostStream1> = lazy(() =>
  object({
    posts: ['posts', array(post4Schema)],
    stream: ['stream', array(unknown())],
  })
);
