/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PostsLockedJsonRequest {
  /** Whether to lock the post (true/false) */
  locked: string;
  additionalProperties?: Record<string, unknown>;
}

export const postsLockedJsonRequestSchema: Schema<PostsLockedJsonRequest> = typedExpandoObject(
  { locked: ['locked', string()] },
  'additionalProperties',
  optional(unknown())
);
