/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Post2, post2Schema } from './post2.js';

export interface PostsJsonResponse3 {
  post: Post2;
}

export const postsJsonResponse3Schema: Schema<PostsJsonResponse3> = lazy(() =>
  object({ post: ['post', post2Schema] })
);
