/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema.js';
import { Topic, topicSchema } from './topic.js';

export interface Post {
  id: number;
  postNumber: number;
  url: string;
  categorySlug: string;
  topic: Topic;
}

export const postSchema: Schema<Post> = lazy(() =>
  object({
    id: ['id', number()],
    postNumber: ['post_number', number()],
    url: ['url', string()],
    categorySlug: ['category_slug', string()],
    topic: ['topic', topicSchema],
  })
);
