/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Post3, post3Schema } from './post3.js';

export interface PostStream {
  posts?: Post3[];
  additionalProperties?: Record<string, unknown>;
}

export const postStreamSchema: Schema<PostStream> = lazy(() =>
  typedExpandoObject(
    { posts: ['posts', optional(array(post3Schema))] },
    'additionalProperties',
    optional(unknown())
  )
);
