/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { ActionsSummary, actionsSummarySchema } from './actionsSummary.js';

export interface PostsJsonResponse1 {
  id: number;
  name: string | null;
  username: string;
  avatarTemplate: string;
  createdAt: string;
  raw?: string;
  cooked: string;
  postNumber: number;
  postType: number;
  postsCount: number;
  updatedAt: string;
  replyCount: number;
  replyToPostNumber: string | null;
  quoteCount: number;
  incomingLinkCount: number;
  reads: number;
  readersCount: number;
  score: number;
  yours: boolean;
  topicId: number;
  topicSlug: string;
  displayUsername: string | null;
  primaryGroupName: string | null;
  flairName: string | null;
  flairUrl: string | null;
  flairBgColor: string | null;
  flairColor: string | null;
  flairGroupId?: number | null;
  badgesGranted?: unknown[];
  version: number;
  canEdit: boolean;
  canDelete: boolean;
  canRecover: boolean;
  canSeeHiddenPost?: boolean;
  canWiki: boolean;
  userTitle: string | null;
  bookmarked: boolean;
  actionsSummary: ActionsSummary[];
  moderator: boolean;
  admin: boolean;
  staff: boolean;
  userId: number;
  draftSequence: number;
  hidden: boolean;
  trustLevel: number;
  deletedAt: string | null;
  userDeleted: boolean;
  editReason: string | null;
  canViewEditHistory: boolean;
  wiki: boolean;
  reviewableId: number | null;
  reviewableScoreCount: number;
  reviewableScorePendingCount: number;
  postUrl: string;
  postLocalizations?: unknown[];
  mentionedUsers?: unknown[];
}

export const postsJsonResponse1Schema: Schema<PostsJsonResponse1> = lazy(() =>
  object({
    id: ['id', number()],
    name: ['name', nullable(string())],
    username: ['username', string()],
    avatarTemplate: ['avatar_template', string()],
    createdAt: ['created_at', string()],
    raw: ['raw', optional(string())],
    cooked: ['cooked', string()],
    postNumber: ['post_number', number()],
    postType: ['post_type', number()],
    postsCount: ['posts_count', number()],
    updatedAt: ['updated_at', string()],
    replyCount: ['reply_count', number()],
    replyToPostNumber: ['reply_to_post_number', nullable(string())],
    quoteCount: ['quote_count', number()],
    incomingLinkCount: ['incoming_link_count', number()],
    reads: ['reads', number()],
    readersCount: ['readers_count', number()],
    score: ['score', number()],
    yours: ['yours', boolean()],
    topicId: ['topic_id', number()],
    topicSlug: ['topic_slug', string()],
    displayUsername: ['display_username', nullable(string())],
    primaryGroupName: ['primary_group_name', nullable(string())],
    flairName: ['flair_name', nullable(string())],
    flairUrl: ['flair_url', nullable(string())],
    flairBgColor: ['flair_bg_color', nullable(string())],
    flairColor: ['flair_color', nullable(string())],
    flairGroupId: ['flair_group_id', optional(nullable(number()))],
    badgesGranted: ['badges_granted', optional(array(unknown()))],
    version: ['version', number()],
    canEdit: ['can_edit', boolean()],
    canDelete: ['can_delete', boolean()],
    canRecover: ['can_recover', boolean()],
    canSeeHiddenPost: ['can_see_hidden_post', optional(boolean())],
    canWiki: ['can_wiki', boolean()],
    userTitle: ['user_title', nullable(string())],
    bookmarked: ['bookmarked', boolean()],
    actionsSummary: ['actions_summary', array(actionsSummarySchema)],
    moderator: ['moderator', boolean()],
    admin: ['admin', boolean()],
    staff: ['staff', boolean()],
    userId: ['user_id', number()],
    draftSequence: ['draft_sequence', number()],
    hidden: ['hidden', boolean()],
    trustLevel: ['trust_level', number()],
    deletedAt: ['deleted_at', nullable(string())],
    userDeleted: ['user_deleted', boolean()],
    editReason: ['edit_reason', nullable(string())],
    canViewEditHistory: ['can_view_edit_history', boolean()],
    wiki: ['wiki', boolean()],
    reviewableId: ['reviewable_id', nullable(number())],
    reviewableScoreCount: ['reviewable_score_count', number()],
    reviewableScorePendingCount: ['reviewable_score_pending_count', number()],
    postUrl: ['post_url', string()],
    postLocalizations: ['post_localizations', optional(array(unknown()))],
    mentionedUsers: ['mentioned_users', optional(array(unknown()))],
  })
);
