/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema.js';

export interface PostActionsJsonRequest {
  /** The ID of the post to perform the action on */
  id: number;
  /** The ID of the post action type (e.g., 2 for like) */
  postActionTypeId: number;
  /** Whether to flag the entire topic */
  flagTopic?: boolean;
}

export const postActionsJsonRequestSchema: Schema<PostActionsJsonRequest> = object(
  {
    id: ['id', number()],
    postActionTypeId: ['post_action_type_id', number()],
    flagTopic: ['flag_topic', optional(boolean())],
  }
);
