/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface PostActionType {
  id: number | null;
  nameKey: string | null;
  name: string;
  description: string;
  shortDescription: string;
  isFlag: boolean;
  requireMessage: boolean;
  enabled: boolean;
  appliesTo: unknown[];
  isUsed: boolean;
  position?: number;
  autoActionType: boolean;
  system?: boolean;
}

export const postActionTypeSchema: Schema<PostActionType> = object({
  id: ['id', nullable(number())],
  nameKey: ['name_key', nullable(string())],
  name: ['name', string()],
  description: ['description', string()],
  shortDescription: ['short_description', string()],
  isFlag: ['is_flag', boolean()],
  requireMessage: ['require_message', boolean()],
  enabled: ['enabled', boolean()],
  appliesTo: ['applies_to', array(unknown())],
  isUsed: ['is_used', boolean()],
  position: ['position', optional(number())],
  autoActionType: ['auto_action_type', boolean()],
  system: ['system', optional(boolean())],
});
