/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ActionsSummary5, actionsSummary5Schema } from './actionsSummary5.js';

export interface PostActionsJsonResponse {
  /** The ID of the post */
  id: number;
  /** The name of the post author */
  name: string;
  /** The username of the post author */
  username: string;
  /** Template for the author's avatar URL */
  avatarTemplate: string;
  /** When the post was created */
  createdAt: string;
  /** The HTML content of the post */
  cooked: string;
  /** The post number within the topic */
  postNumber: number;
  /** The type of post */
  postType: number;
  /** Total posts count for the user */
  postsCount: number;
  /** When the post was last updated */
  updatedAt: string;
  /** Number of replies to this post */
  replyCount: number;
  /** Post number this post is replying to */
  replyToPostNumber: string | null;
  /** Number of times this post has been quoted */
  quoteCount: number;
  /** Number of incoming links to this post */
  incomingLinkCount: number;
  /** Number of reads */
  reads: number;
  /** Number of readers */
  readersCount: number;
  /** Post score */
  score: number;
  /** Whether this post belongs to the current user */
  yours: boolean;
  /** ID of the topic this post belongs to */
  topicId: number;
  /** Slug of the topic this post belongs to */
  topicSlug: string;
  /** Display username of the post author */
  displayUsername: string;
  /** Primary group name of the author */
  primaryGroupName: string | null;
  /** Flair name of the author */
  flairName: string | null;
  /** Flair URL of the author */
  flairUrl: string | null;
  /** Flair background color of the author */
  flairBgColor: string | null;
  /** Flair color of the author */
  flairColor: string | null;
  /** Flair group ID of the author */
  flairGroupId: number | null;
  /** Badges granted to the user */
  badgesGranted: unknown[];
  /** Version number of the post */
  version: number;
  /** Whether the current user can edit this post */
  canEdit: boolean;
  /** Whether the current user can delete this post */
  canDelete: boolean;
  /** Whether the current user can recover this post */
  canRecover: boolean;
  /** Whether the current user can see hidden posts */
  canSeeHiddenPost: boolean;
  /** Whether the current user can wiki this post */
  canWiki: boolean;
  /** Title of the post author */
  userTitle: string | null;
  /** Whether the post is bookmarked by the current user */
  bookmarked: boolean;
  /** Summary of actions performed on this post */
  actionsSummary: ActionsSummary5[];
  /** Whether the post author is a moderator */
  moderator: boolean;
  /** Whether the post author is an admin */
  admin: boolean;
  /** Whether the post author is staff */
  staff: boolean;
  /** ID of the post author */
  userId: number;
  /** Whether the post is hidden */
  hidden: boolean;
  /** Trust level of the post author */
  trustLevel: number;
  /** When the post was deleted */
  deletedAt: string | null;
  /** Whether the post was deleted by the user */
  userDeleted: boolean;
  /** Reason for the last edit */
  editReason: string | null;
  /** Whether the current user can view edit history */
  canViewEditHistory: boolean;
  /** Whether this is a wiki post */
  wiki: boolean;
  /** ID of the reviewable if this post is under review */
  reviewableId: number | null;
  /** Number of reviewable scores */
  reviewableScoreCount: number;
  /** Number of pending reviewable scores */
  reviewableScorePendingCount: number;
  /** URL of the post */
  postUrl: string;
  additionalProperties?: Record<string, unknown>;
}

export const postActionsJsonResponseSchema: Schema<PostActionsJsonResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        id: ['id', number()],
        name: ['name', string()],
        username: ['username', string()],
        avatarTemplate: ['avatar_template', string()],
        createdAt: ['created_at', string()],
        cooked: ['cooked', string()],
        postNumber: ['post_number', number()],
        postType: ['post_type', number()],
        postsCount: ['posts_count', number()],
        updatedAt: ['updated_at', string()],
        replyCount: ['reply_count', number()],
        replyToPostNumber: ['reply_to_post_number', nullable(string())],
        quoteCount: ['quote_count', number()],
        incomingLinkCount: ['incoming_link_count', number()],
        reads: ['reads', number()],
        readersCount: ['readers_count', number()],
        score: ['score', number()],
        yours: ['yours', boolean()],
        topicId: ['topic_id', number()],
        topicSlug: ['topic_slug', string()],
        displayUsername: ['display_username', string()],
        primaryGroupName: ['primary_group_name', nullable(string())],
        flairName: ['flair_name', nullable(string())],
        flairUrl: ['flair_url', nullable(string())],
        flairBgColor: ['flair_bg_color', nullable(string())],
        flairColor: ['flair_color', nullable(string())],
        flairGroupId: ['flair_group_id', nullable(number())],
        badgesGranted: ['badges_granted', array(unknown())],
        version: ['version', number()],
        canEdit: ['can_edit', boolean()],
        canDelete: ['can_delete', boolean()],
        canRecover: ['can_recover', boolean()],
        canSeeHiddenPost: ['can_see_hidden_post', boolean()],
        canWiki: ['can_wiki', boolean()],
        userTitle: ['user_title', nullable(string())],
        bookmarked: ['bookmarked', boolean()],
        actionsSummary: ['actions_summary', array(actionsSummary5Schema)],
        moderator: ['moderator', boolean()],
        admin: ['admin', boolean()],
        staff: ['staff', boolean()],
        userId: ['user_id', number()],
        hidden: ['hidden', boolean()],
        trustLevel: ['trust_level', number()],
        deletedAt: ['deleted_at', nullable(string())],
        userDeleted: ['user_deleted', boolean()],
        editReason: ['edit_reason', nullable(string())],
        canViewEditHistory: ['can_view_edit_history', boolean()],
        wiki: ['wiki', boolean()],
        reviewableId: ['reviewable_id', nullable(number())],
        reviewableScoreCount: ['reviewable_score_count', number()],
        reviewableScorePendingCount: [
          'reviewable_score_pending_count',
          number(),
        ],
        postUrl: ['post_url', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
