/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema.js';

export interface Poster {
  extras: string;
  description: string;
  userId: number;
  primaryGroupId: number | null;
}

export const posterSchema: Schema<Poster> = object({
  extras: ['extras', string()],
  description: ['description', string()],
  userId: ['user_id', number()],
  primaryGroupId: ['primary_group_id', nullable(number())],
});
