/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Post1 {
  raw: string;
  editReason?: string;
}

export const post1Schema: Schema<Post1> = object({
  raw: ['raw', string()],
  editReason: ['edit_reason', optional(string())],
});
