/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ActionsSummary6, actionsSummary6Schema } from './actionsSummary6.js';

export interface Post3 {
  id?: number;
  name?: string | null;
  username?: string;
  avatarTemplate?: string;
  createdAt?: string;
  cooked?: string;
  postNumber?: number;
  postType?: number;
  updatedAt?: string;
  replyCount?: number;
  replyToPostNumber?: string | null;
  quoteCount?: number;
  incomingLinkCount?: number;
  reads?: number;
  readersCount?: number;
  score?: number;
  yours?: boolean;
  topicId?: number;
  topicSlug?: string;
  displayUsername?: string | null;
  primaryGroupName?: string | null;
  flairName?: string | null;
  flairUrl?: string | null;
  flairBgColor?: string | null;
  flairColor?: string | null;
  version?: number;
  canEdit?: boolean;
  canDelete?: boolean;
  canRecover?: boolean;
  canWiki?: boolean;
  read?: boolean;
  userTitle?: string | null;
  actionsSummary?: ActionsSummary6[];
  moderator?: boolean;
  admin?: boolean;
  staff?: boolean;
  userId?: number;
  hidden?: boolean;
  trustLevel?: number;
  deletedAt?: string | null;
  userDeleted?: boolean;
  editReason?: string | null;
  canViewEditHistory?: boolean;
  wiki?: boolean;
  reviewableId?: number;
  reviewableScoreCount?: number;
  reviewableScorePendingCount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const post3Schema: Schema<Post3> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', optional(number())],
      name: ['name', optional(nullable(string()))],
      username: ['username', optional(string())],
      avatarTemplate: ['avatar_template', optional(string())],
      createdAt: ['created_at', optional(string())],
      cooked: ['cooked', optional(string())],
      postNumber: ['post_number', optional(number())],
      postType: ['post_type', optional(number())],
      updatedAt: ['updated_at', optional(string())],
      replyCount: ['reply_count', optional(number())],
      replyToPostNumber: ['reply_to_post_number', optional(nullable(string()))],
      quoteCount: ['quote_count', optional(number())],
      incomingLinkCount: ['incoming_link_count', optional(number())],
      reads: ['reads', optional(number())],
      readersCount: ['readers_count', optional(number())],
      score: ['score', optional(number())],
      yours: ['yours', optional(boolean())],
      topicId: ['topic_id', optional(number())],
      topicSlug: ['topic_slug', optional(string())],
      displayUsername: ['display_username', optional(nullable(string()))],
      primaryGroupName: ['primary_group_name', optional(nullable(string()))],
      flairName: ['flair_name', optional(nullable(string()))],
      flairUrl: ['flair_url', optional(nullable(string()))],
      flairBgColor: ['flair_bg_color', optional(nullable(string()))],
      flairColor: ['flair_color', optional(nullable(string()))],
      version: ['version', optional(number())],
      canEdit: ['can_edit', optional(boolean())],
      canDelete: ['can_delete', optional(boolean())],
      canRecover: ['can_recover', optional(boolean())],
      canWiki: ['can_wiki', optional(boolean())],
      read: ['read', optional(boolean())],
      userTitle: ['user_title', optional(nullable(string()))],
      actionsSummary: [
        'actions_summary',
        optional(array(actionsSummary6Schema)),
      ],
      moderator: ['moderator', optional(boolean())],
      admin: ['admin', optional(boolean())],
      staff: ['staff', optional(boolean())],
      userId: ['user_id', optional(number())],
      hidden: ['hidden', optional(boolean())],
      trustLevel: ['trust_level', optional(number())],
      deletedAt: ['deleted_at', optional(nullable(string()))],
      userDeleted: ['user_deleted', optional(boolean())],
      editReason: ['edit_reason', optional(nullable(string()))],
      canViewEditHistory: ['can_view_edit_history', optional(boolean())],
      wiki: ['wiki', optional(boolean())],
      reviewableId: ['reviewable_id', optional(number())],
      reviewableScoreCount: ['reviewable_score_count', optional(number())],
      reviewableScorePendingCount: [
        'reviewable_score_pending_count',
        optional(number()),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
