/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { User, userSchema } from './user.js';

export interface Poster4 {
  extras: string;
  description: string;
  user: User;
}

export const poster4Schema: Schema<Poster4> = lazy(() =>
  object({
    extras: ['extras', string()],
    description: ['description', string()],
    user: ['user', userSchema],
  })
);
