/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Reason
 */
export enum Reason {
  EnabledForEveryone = 'enabled_for_everyone',
  EnabledForNoOne = 'enabled_for_no_one',
  InSpecificGroups = 'in_specific_groups',
  NotInSpecificGroups = 'not_in_specific_groups',
}

/**
 * Schema for Reason
 */
export const reasonSchema: Schema<Reason> = stringEnum(Reason);
