/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Period, periodSchema } from './period.js';

export interface Reminder {
  value: number;
  unit: string;
  period: Period;
  type: string;
  additionalProperties?: Record<string, unknown>;
}

export const reminderSchema: Schema<Reminder> = typedExpandoObject(
  {
    value: ['value', number()],
    unit: ['unit', string()],
    period: ['period', periodSchema],
    type: ['type', string()],
  },
  'additionalProperties',
  optional(unknown())
);
