/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

export interface ReplyToUser {
  id?: number;
  username: string;
  name?: string;
  avatarTemplate: string;
}

export const replyToUserSchema: Schema<ReplyToUser> = object({
  id: ['id', optional(number())],
  username: ['username', string()],
  name: ['name', optional(string())],
  avatarTemplate: ['avatar_template', string()],
});
