/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface RequiredTagGroup {
  name: string;
  minCount: number;
}

export const requiredTagGroupSchema: Schema<RequiredTagGroup> = object({
  name: ['name', string()],
  minCount: ['min_count', number()],
});
