/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, unknown } from '../schema.js';
import {
  GroupedSearchResult,
  groupedSearchResultSchema,
} from './groupedSearchResult.js';
import { Tag, tagSchema } from './tag.js';

export interface SearchJsonResponse {
  posts: unknown[];
  users: unknown[];
  categories: unknown[];
  tags: Tag[];
  groups: unknown[];
  groupedSearchResult: GroupedSearchResult;
}

export const searchJsonResponseSchema: Schema<SearchJsonResponse> = lazy(() =>
  object({
    posts: ['posts', array(unknown())],
    users: ['users', array(unknown())],
    categories: ['categories', array(unknown())],
    tags: ['tags', array(tagSchema)],
    groups: ['groups', array(unknown())],
    groupedSearchResult: ['grouped_search_result', groupedSearchResultSchema],
  })
);
