/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema.js';

export interface SessionForgotPasswordJsonResponse {
  success: string;
  userFound: boolean;
}

export const sessionForgotPasswordJsonResponseSchema: Schema<SessionForgotPasswordJsonResponse> = object(
  { success: ['success', string()], userFound: ['user_found', boolean()] }
);
