/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface SessionForgotPasswordJsonRequest {
  login: string;
}

export const sessionForgotPasswordJsonRequestSchema: Schema<SessionForgotPasswordJsonRequest> = object(
  { login: ['login', string()] }
);
