/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, Schema, string } from '../schema.js';
import { SilencedBy, silencedBySchema } from './silencedBy.js';

export interface Silence {
  silenced: boolean;
  silenceReason: string;
  fullSilenceReason: string;
  silencedTill: string;
  silencedAt: string;
  silencedBy: SilencedBy;
}

export const silenceSchema: Schema<Silence> = lazy(() =>
  object({
    silenced: ['silenced', boolean()],
    silenceReason: ['silence_reason', string()],
    fullSilenceReason: ['full_silence_reason', string()],
    silencedTill: ['silenced_till', string()],
    silencedAt: ['silenced_at', string()],
    silencedBy: ['silenced_by', silencedBySchema],
  })
);
