/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema.js';

export interface SiteBasicInfoJsonResponse {
  logoUrl: string;
  logoSmallUrl: string;
  appleTouchIconUrl: string;
  faviconUrl: string;
  title: string;
  description: string;
  headerPrimaryColor: string;
  headerBackgroundColor: string;
  loginRequired: boolean;
  locale: string;
  includeInDiscourseDiscover: boolean;
  mobileLogoUrl: string;
}

export const siteBasicInfoJsonResponseSchema: Schema<SiteBasicInfoJsonResponse> = object(
  {
    logoUrl: ['logo_url', string()],
    logoSmallUrl: ['logo_small_url', string()],
    appleTouchIconUrl: ['apple_touch_icon_url', string()],
    faviconUrl: ['favicon_url', string()],
    title: ['title', string()],
    description: ['description', string()],
    headerPrimaryColor: ['header_primary_color', string()],
    headerBackgroundColor: ['header_background_color', string()],
    loginRequired: ['login_required', boolean()],
    locale: ['locale', string()],
    includeInDiscourseDiscover: ['include_in_discourse_discover', boolean()],
    mobileLogoUrl: ['mobile_logo_url', string()],
  }
);
