/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { AccessControl, accessControlSchema } from './accessControl.js';
import { Archetype, archetypeSchema } from './archetype.js';
import { Category4, category4Schema } from './category4.js';
import { CategoryType, categoryTypeSchema } from './categoryType.js';
import { Group5, group5Schema } from './group5.js';
import {
  NotificationTypes,
  notificationTypesSchema,
} from './notificationTypes.js';
import { PostActionType, postActionTypeSchema } from './postActionType.js';
import { PostTypes, postTypesSchema } from './postTypes.js';
import { TopicFlagType, topicFlagTypeSchema } from './topicFlagType.js';
import { TopTag, topTagSchema } from './topTag.js';
import { TrustLevels, trustLevelsSchema } from './trustLevels.js';
import { UserColorScheme, userColorSchemeSchema } from './userColorScheme.js';
import { UserTheme, userThemeSchema } from './userTheme.js';
import { UserTips, userTipsSchema } from './userTips.js';

export interface SiteJsonResponse {
  defaultArchetype: string;
  notificationTypes: NotificationTypes;
  postTypes: PostTypes;
  trustLevels: TrustLevels;
  userTips?: UserTips;
  groups: Group5[];
  filters: unknown[];
  homepageChoices: unknown[];
  periods: unknown[];
  topMenuItems: unknown[];
  anonymousTopMenuItems: unknown[];
  uncategorizedCategoryId: number;
  userFieldMaxLength: number;
  postActionTypes: PostActionType[];
  topicFlagTypes: TopicFlagType[];
  canCreateTag: boolean;
  canTagTopics: boolean;
  canTagPms: boolean;
  tagsFilterRegexp: string;
  topTags: TopTag[];
  wizardRequired?: boolean;
  canAssociateGroups?: boolean;
  emailConfigured: boolean;
  upcomingChangesWithCss?: string[];
  topicFeaturedLinkAllowedCategoryIds: unknown[];
  userThemes: UserTheme[];
  userColorSchemes: UserColorScheme[];
  defaultLightColorScheme?: unknown | null;
  defaultDarkColorScheme?: unknown | null;
  censoredRegexp: unknown[];
  customEmojiTranslation?: unknown;
  watchedWordsReplace: string | null;
  watchedWordsLink: string | null;
  markdownAdditionalOptions?: unknown;
  hashtagConfigurations?: unknown;
  hashtagIcons?: unknown;
  displayedAboutPluginStatGroups?: unknown[];
  categories: Category4[];
  archetypes: Archetype[];
  userFields: unknown[];
  authProviders: unknown[];
  whispersAllowedGroupsNames?: unknown[];
  deniedEmojis?: unknown[];
  validFlagAppliesToTypes?: unknown[];
  navigationMenuSiteTopTags?: unknown[];
  fullNameRequiredForSignup: boolean;
  fullNameVisibleInSignup: boolean;
  adminConfigLoginRoutes?: unknown[];
  accessControl?: AccessControl;
  permanentUpcomingChangeNames?: string[];
  categoryTypes?: CategoryType[];
}

export const siteJsonResponseSchema: Schema<SiteJsonResponse> = lazy(() =>
  object({
    defaultArchetype: ['default_archetype', string()],
    notificationTypes: ['notification_types', notificationTypesSchema],
    postTypes: ['post_types', postTypesSchema],
    trustLevels: ['trust_levels', trustLevelsSchema],
    userTips: ['user_tips', optional(userTipsSchema)],
    groups: ['groups', array(group5Schema)],
    filters: ['filters', array(unknown())],
    homepageChoices: ['homepage_choices', array(unknown())],
    periods: ['periods', array(unknown())],
    topMenuItems: ['top_menu_items', array(unknown())],
    anonymousTopMenuItems: ['anonymous_top_menu_items', array(unknown())],
    uncategorizedCategoryId: ['uncategorized_category_id', number()],
    userFieldMaxLength: ['user_field_max_length', number()],
    postActionTypes: ['post_action_types', array(postActionTypeSchema)],
    topicFlagTypes: ['topic_flag_types', array(topicFlagTypeSchema)],
    canCreateTag: ['can_create_tag', boolean()],
    canTagTopics: ['can_tag_topics', boolean()],
    canTagPms: ['can_tag_pms', boolean()],
    tagsFilterRegexp: ['tags_filter_regexp', string()],
    topTags: ['top_tags', array(topTagSchema)],
    wizardRequired: ['wizard_required', optional(boolean())],
    canAssociateGroups: ['can_associate_groups', optional(boolean())],
    emailConfigured: ['email_configured', boolean()],
    upcomingChangesWithCss: [
      'upcoming_changes_with_css',
      optional(array(string())),
    ],
    topicFeaturedLinkAllowedCategoryIds: [
      'topic_featured_link_allowed_category_ids',
      array(unknown()),
    ],
    userThemes: ['user_themes', array(userThemeSchema)],
    userColorSchemes: ['user_color_schemes', array(userColorSchemeSchema)],
    defaultLightColorScheme: [
      'default_light_color_scheme',
      optional(nullable(unknown())),
    ],
    defaultDarkColorScheme: [
      'default_dark_color_scheme',
      optional(nullable(unknown())),
    ],
    censoredRegexp: ['censored_regexp', array(unknown())],
    customEmojiTranslation: ['custom_emoji_translation', optional(unknown())],
    watchedWordsReplace: ['watched_words_replace', nullable(string())],
    watchedWordsLink: ['watched_words_link', nullable(string())],
    markdownAdditionalOptions: [
      'markdown_additional_options',
      optional(unknown()),
    ],
    hashtagConfigurations: ['hashtag_configurations', optional(unknown())],
    hashtagIcons: ['hashtag_icons', optional(unknown())],
    displayedAboutPluginStatGroups: [
      'displayed_about_plugin_stat_groups',
      optional(array(unknown())),
    ],
    categories: ['categories', array(category4Schema)],
    archetypes: ['archetypes', array(archetypeSchema)],
    userFields: ['user_fields', array(unknown())],
    authProviders: ['auth_providers', array(unknown())],
    whispersAllowedGroupsNames: [
      'whispers_allowed_groups_names',
      optional(array(unknown())),
    ],
    deniedEmojis: ['denied_emojis', optional(array(unknown()))],
    validFlagAppliesToTypes: [
      'valid_flag_applies_to_types',
      optional(array(unknown())),
    ],
    navigationMenuSiteTopTags: [
      'navigation_menu_site_top_tags',
      optional(array(unknown())),
    ],
    fullNameRequiredForSignup: ['full_name_required_for_signup', boolean()],
    fullNameVisibleInSignup: ['full_name_visible_in_signup', boolean()],
    adminConfigLoginRoutes: [
      'admin_config_login_routes',
      optional(array(unknown())),
    ],
    accessControl: ['access_control', optional(accessControlSchema)],
    permanentUpcomingChangeNames: [
      'permanent_upcoming_change_names',
      optional(array(string())),
    ],
    categoryTypes: ['category_types', optional(array(categoryTypeSchema))],
  })
);
