/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { Poster4, poster4Schema } from './poster4.js';
import { Tag, tagSchema } from './tag.js';

export interface SuggestedTopic {
  id: number;
  title: string;
  fancyTitle: string;
  slug: string;
  postsCount: number;
  replyCount: number;
  highestPostNumber: number;
  imageUrl: string | null;
  createdAt: string;
  lastPostedAt: string | null;
  bumped: boolean;
  bumpedAt: string;
  archetype: string;
  unseen: boolean;
  pinned: boolean;
  unpinned: string | null;
  excerpt: string;
  visible: boolean;
  closed: boolean;
  archived: boolean;
  bookmarked: string | null;
  liked: string | null;
  tags: Tag[];
  tagsDescriptions?: unknown;
  likeCount: number;
  views: number;
  categoryId: number;
  featuredLink: string | null;
  posters: Poster4[];
}

export const suggestedTopicSchema: Schema<SuggestedTopic> = lazy(() =>
  object({
    id: ['id', number()],
    title: ['title', string()],
    fancyTitle: ['fancy_title', string()],
    slug: ['slug', string()],
    postsCount: ['posts_count', number()],
    replyCount: ['reply_count', number()],
    highestPostNumber: ['highest_post_number', number()],
    imageUrl: ['image_url', nullable(string())],
    createdAt: ['created_at', string()],
    lastPostedAt: ['last_posted_at', nullable(string())],
    bumped: ['bumped', boolean()],
    bumpedAt: ['bumped_at', string()],
    archetype: ['archetype', string()],
    unseen: ['unseen', boolean()],
    pinned: ['pinned', boolean()],
    unpinned: ['unpinned', nullable(string())],
    excerpt: ['excerpt', string()],
    visible: ['visible', boolean()],
    closed: ['closed', boolean()],
    archived: ['archived', boolean()],
    bookmarked: ['bookmarked', nullable(string())],
    liked: ['liked', nullable(string())],
    tags: ['tags', array(tagSchema)],
    tagsDescriptions: ['tags_descriptions', optional(unknown())],
    likeCount: ['like_count', number()],
    views: ['views', number()],
    categoryId: ['category_id', number()],
    featuredLink: ['featured_link', nullable(string())],
    posters: ['posters', array(poster4Schema)],
  })
);
