/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface SuspendedBy {
  id: number;
  username: string;
  name: string;
  avatarTemplate: string;
}

export const suspendedBySchema: Schema<SuspendedBy> = object({
  id: ['id', number()],
  username: ['username', string()],
  name: ['name', string()],
  avatarTemplate: ['avatar_template', string()],
});
