/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { SuspendedBy, suspendedBySchema } from './suspendedBy.js';

export interface Suspension {
  suspendReason: string;
  fullSuspendReason: string;
  suspendedTill: string;
  suspendedAt: string;
  suspendedBy: SuspendedBy;
}

export const suspensionSchema: Schema<Suspension> = lazy(() =>
  object({
    suspendReason: ['suspend_reason', string()],
    fullSuspendReason: ['full_suspend_reason', string()],
    suspendedTill: ['suspended_till', string()],
    suspendedAt: ['suspended_at', string()],
    suspendedBy: ['suspended_by', suspendedBySchema],
  })
);
