/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Tag {
  id: number;
  name: string;
  slug: string;
  additionalProperties?: Record<string, unknown>;
}

export const tagSchema: Schema<Tag> = typedExpandoObject(
  { id: ['id', number()], name: ['name', string()], slug: ['slug', string()] },
  'additionalProperties',
  optional(unknown())
);
