/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Tag3 {
  id?: number;
  text?: string;
  name?: string;
  count?: number;
  pmCount?: number;
  targetTag?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const tag3Schema: Schema<Tag3> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    text: ['text', optional(string())],
    name: ['name', optional(string())],
    count: ['count', optional(number())],
    pmCount: ['pm_count', optional(number())],
    targetTag: ['target_tag', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
