/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Tag4 {
  id?: number;
  name?: string;
  topicCount?: number;
  staff?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const tag4Schema: Schema<Tag4> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    name: ['name', optional(string())],
    topicCount: ['topic_count', optional(number())],
    staff: ['staff', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
