/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Permissions2, permissions2Schema } from './permissions2.js';

export interface TagGroup2 {
  id?: number;
  name?: string;
  tagNames?: unknown[];
  parentTagName?: unknown[];
  onePerTopic?: boolean;
  permissions?: Permissions2;
  additionalProperties?: Record<string, unknown>;
}

export const tagGroup2Schema: Schema<TagGroup2> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', optional(number())],
      name: ['name', optional(string())],
      tagNames: ['tag_names', optional(array(unknown()))],
      parentTagName: ['parent_tag_name', optional(array(unknown()))],
      onePerTopic: ['one_per_topic', optional(boolean())],
      permissions: ['permissions', optional(permissions2Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
