/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TagGroupsJsonRequest1 {
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const tagGroupsJsonRequest1Schema: Schema<TagGroupsJsonRequest1> = typedExpandoObject(
  { name: ['name', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
