/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface TagGroupsJsonRequest {
  name: string;
}

export const tagGroupsJsonRequestSchema: Schema<TagGroupsJsonRequest> = object({
  name: ['name', string()],
});
