/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { TagGroup1, tagGroup1Schema } from './tagGroup1.js';

export interface TagGroupsJsonResponse1 {
  tagGroup: TagGroup1;
}

export const tagGroupsJsonResponse1Schema: Schema<TagGroupsJsonResponse1> = lazy(
  () => object({ tagGroup: ['tag_group', tagGroup1Schema] })
);
