/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TagGroup2, tagGroup2Schema } from './tagGroup2.js';

export interface TagGroupsJsonResponse3 {
  success?: string;
  tagGroup?: TagGroup2;
  additionalProperties?: Record<string, unknown>;
}

export const tagGroupsJsonResponse3Schema: Schema<TagGroupsJsonResponse3> = lazy(
  () =>
    typedExpandoObject(
      {
        success: ['success', optional(string())],
        tagGroup: ['tag_group', optional(tagGroup2Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
