/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { ParentTag, parentTagSchema } from './parentTag.js';
import { Tag, tagSchema } from './tag.js';

export interface TagGroup {
  id: number;
  name: string;
  tags: Tag[];
  parentTag: ParentTag[];
  onePerTopic: boolean;
  permissions: Record<string, number>;
}

export const tagGroupSchema: Schema<TagGroup> = lazy(() =>
  object({
    id: ['id', number()],
    name: ['name', string()],
    tags: ['tags', array(tagSchema)],
    parentTag: ['parent_tag', array(parentTagSchema)],
    onePerTopic: ['one_per_topic', boolean()],
    permissions: ['permissions', dict(number())],
  })
);
