/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TagGroup2, tagGroup2Schema } from './tagGroup2.js';

export interface TagGroupsJsonResponse2 {
  tagGroup?: TagGroup2;
  additionalProperties?: Record<string, unknown>;
}

export const tagGroupsJsonResponse2Schema: Schema<TagGroupsJsonResponse2> = lazy(
  () =>
    typedExpandoObject(
      { tagGroup: ['tag_group', optional(tagGroup2Schema)] },
      'additionalProperties',
      optional(unknown())
    )
);
