/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ParentTag, parentTagSchema } from './parentTag.js';
import { Tag, tagSchema } from './tag.js';

export interface TagGroup1 {
  id: number;
  name: string;
  tags: Tag[];
  parentTag: ParentTag[];
  onePerTopic: boolean;
  permissions?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const tagGroup1Schema: Schema<TagGroup1> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', number()],
      name: ['name', string()],
      tags: ['tags', array(tagSchema)],
      parentTag: ['parent_tag', array(parentTagSchema)],
      onePerTopic: ['one_per_topic', boolean()],
      permissions: ['permissions', optional(unknown())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
