/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { TagGroup, tagGroupSchema } from './tagGroup.js';

export interface TagGroupsJsonResponse {
  tagGroups: TagGroup[];
}

export const tagGroupsJsonResponseSchema: Schema<TagGroupsJsonResponse> = lazy(
  () => object({ tagGroups: ['tag_groups', array(tagGroupSchema)] })
);
