/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TopicList3, topicList3Schema } from './topicList3.js';
import { User2, user2Schema } from './user2.js';

export interface TagJsonResponse {
  users?: User2[];
  primaryGroups?: unknown[];
  topicList?: TopicList3;
  additionalProperties?: Record<string, unknown>;
}

export const tagJsonResponseSchema: Schema<TagJsonResponse> = lazy(() =>
  typedExpandoObject(
    {
      users: ['users', optional(array(user2Schema))],
      primaryGroups: ['primary_groups', optional(array(unknown()))],
      topicList: ['topic_list', optional(topicList3Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
