/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Extras3, extras3Schema } from './extras3.js';
import { Tag3, tag3Schema } from './tag3.js';

export interface TagsJsonResponse {
  tags?: Tag3[];
  extras?: Extras3;
  additionalProperties?: Record<string, unknown>;
}

export const tagsJsonResponseSchema: Schema<TagsJsonResponse> = lazy(() =>
  typedExpandoObject(
    {
      tags: ['tags', optional(array(tag3Schema))],
      extras: ['extras', optional(extras3Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
