/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TChangeTimestampJsonRequest {
  timestamp: string;
  additionalProperties?: Record<string, unknown>;
}

export const tChangeTimestampJsonRequestSchema: Schema<TChangeTimestampJsonRequest> = typedExpandoObject(
  { timestamp: ['timestamp', string()] },
  'additionalProperties',
  optional(unknown())
);
