/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

export interface Thumbnail {
  id?: number;
  uploadId?: number;
  url?: string;
  extension?: string;
  width?: number;
  height?: number;
  filesize?: number;
}

export const thumbnailSchema: Schema<Thumbnail> = object({
  id: ['id', optional(number())],
  uploadId: ['upload_id', optional(number())],
  url: ['url', optional(string())],
  extension: ['extension', optional(string())],
  width: ['width', optional(number())],
  height: ['height', optional(number())],
  filesize: ['filesize', optional(number())],
});
