/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TInviteJsonRequest {
  user?: string;
  email?: string;
  additionalProperties?: Record<string, unknown>;
}

export const tInviteJsonRequestSchema: Schema<TInviteJsonRequest> = typedExpandoObject(
  { user: ['user', optional(string())], email: ['email', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
