/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TInviteGroupJsonRequest {
  /** The name of the group to invite */
  group?: string;
  /** Whether to notify the group, it defaults to true */
  shouldNotify?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const tInviteGroupJsonRequestSchema: Schema<TInviteGroupJsonRequest> = typedExpandoObject(
  {
    group: ['group', optional(string())],
    shouldNotify: ['should_notify', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
