/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { User1, user1Schema } from './user1.js';

export interface TInviteJsonResponse {
  user?: User1;
  additionalProperties?: Record<string, unknown>;
}

export const tInviteJsonResponseSchema: Schema<TInviteJsonResponse> = lazy(() =>
  typedExpandoObject(
    { user: ['user', optional(user1Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
