/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Group6, group6Schema } from './group6.js';

export interface TInviteGroupJsonResponse {
  group?: Group6;
  additionalProperties?: Record<string, unknown>;
}

export const tInviteGroupJsonResponseSchema: Schema<TInviteGroupJsonResponse> = lazy(
  () =>
    typedExpandoObject(
      { group: ['group', optional(group6Schema)] },
      'additionalProperties',
      optional(unknown())
    )
);
