/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Topic5, topic5Schema } from './topic5.js';

export interface TJsonRequest {
  topic?: Topic5;
  additionalProperties?: Record<string, unknown>;
}

export const tJsonRequestSchema: Schema<TJsonRequest> = lazy(() =>
  typedExpandoObject(
    { topic: ['topic', optional(topic5Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
