/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { ActionsSummary8, actionsSummary8Schema } from './actionsSummary8.js';
import { Details, detailsSchema } from './details.js';
import { PostStream1, postStream1Schema } from './postStream1.js';
import { SuggestedTopic, suggestedTopicSchema } from './suggestedTopic.js';
import { Tag, tagSchema } from './tag.js';

export interface TJsonResponse {
  postStream: PostStream1;
  timelineLookup: unknown[];
  suggestedTopics: SuggestedTopic[];
  tags: Tag[];
  tagsDescriptions?: unknown;
  id: number;
  title: string;
  fancyTitle: string;
  postsCount: number;
  createdAt: string;
  views: number;
  replyCount: number;
  likeCount: number;
  lastPostedAt: string | null;
  visible: boolean;
  closed: boolean;
  archived: boolean;
  hasSummary: boolean;
  archetype: string;
  slug: string;
  categoryId: number;
  wordCount: number | null;
  deletedAt: string | null;
  userId: number;
  featuredLink: string | null;
  pinnedGlobally: boolean;
  pinnedAt: string | null;
  pinnedUntil: string | null;
  imageUrl: string | null;
  slowModeSeconds: number;
  draft: string | null;
  draftKey: string;
  draftSequence: number;
  unpinned: string | null;
  pinned: boolean;
  currentPostNumber?: number;
  highestPostNumber: number | null;
  deletedBy: string | null;
  hasDeleted: boolean;
  actionsSummary: ActionsSummary8[];
  chunkSize: number;
  bookmarked: boolean;
  bookmarks: unknown[];
  topicTimer: string | null;
  messageBusLastId: number;
  participantCount: number;
  showReadIndicator: boolean;
  thumbnails: string | null;
  slowModeEnabledUntil: string | null;
  details: Details;
}

export const tJsonResponseSchema: Schema<TJsonResponse> = lazy(() =>
  object({
    postStream: ['post_stream', postStream1Schema],
    timelineLookup: ['timeline_lookup', array(unknown())],
    suggestedTopics: ['suggested_topics', array(suggestedTopicSchema)],
    tags: ['tags', array(tagSchema)],
    tagsDescriptions: ['tags_descriptions', optional(unknown())],
    id: ['id', number()],
    title: ['title', string()],
    fancyTitle: ['fancy_title', string()],
    postsCount: ['posts_count', number()],
    createdAt: ['created_at', string()],
    views: ['views', number()],
    replyCount: ['reply_count', number()],
    likeCount: ['like_count', number()],
    lastPostedAt: ['last_posted_at', nullable(string())],
    visible: ['visible', boolean()],
    closed: ['closed', boolean()],
    archived: ['archived', boolean()],
    hasSummary: ['has_summary', boolean()],
    archetype: ['archetype', string()],
    slug: ['slug', string()],
    categoryId: ['category_id', number()],
    wordCount: ['word_count', nullable(number())],
    deletedAt: ['deleted_at', nullable(string())],
    userId: ['user_id', number()],
    featuredLink: ['featured_link', nullable(string())],
    pinnedGlobally: ['pinned_globally', boolean()],
    pinnedAt: ['pinned_at', nullable(string())],
    pinnedUntil: ['pinned_until', nullable(string())],
    imageUrl: ['image_url', nullable(string())],
    slowModeSeconds: ['slow_mode_seconds', number()],
    draft: ['draft', nullable(string())],
    draftKey: ['draft_key', string()],
    draftSequence: ['draft_sequence', number()],
    unpinned: ['unpinned', nullable(string())],
    pinned: ['pinned', boolean()],
    currentPostNumber: ['current_post_number', optional(number())],
    highestPostNumber: ['highest_post_number', nullable(number())],
    deletedBy: ['deleted_by', nullable(string())],
    hasDeleted: ['has_deleted', boolean()],
    actionsSummary: ['actions_summary', array(actionsSummary8Schema)],
    chunkSize: ['chunk_size', number()],
    bookmarked: ['bookmarked', boolean()],
    bookmarks: ['bookmarks', array(unknown())],
    topicTimer: ['topic_timer', nullable(string())],
    messageBusLastId: ['message_bus_last_id', number()],
    participantCount: ['participant_count', number()],
    showReadIndicator: ['show_read_indicator', boolean()],
    thumbnails: ['thumbnails', nullable(string())],
    slowModeEnabledUntil: ['slow_mode_enabled_until', nullable(string())],
    details: ['details', detailsSchema],
  })
);
