/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BasicTopic, basicTopicSchema } from './basicTopic.js';

export interface TJsonResponse1 {
  basicTopic?: BasicTopic;
  additionalProperties?: Record<string, unknown>;
}

export const tJsonResponse1Schema: Schema<TJsonResponse1> = lazy(() =>
  typedExpandoObject(
    { basicTopic: ['basic_topic', optional(basicTopicSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
