/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, number, object, Schema } from '../schema.js';
import { PenaltyCounts1, penaltyCounts1Schema } from './penaltyCounts1.js';

export interface Tl3Requirements {
  timePeriod: number;
  requirementsMet: boolean;
  requirementsLost: boolean;
  trustLevelLocked: boolean;
  onGracePeriod: boolean;
  daysVisited: number;
  minDaysVisited: number;
  numTopicsRepliedTo: number;
  minTopicsRepliedTo: number;
  topicsViewed: number;
  minTopicsViewed: number;
  postsRead: number;
  minPostsRead: number;
  topicsViewedAllTime: number;
  minTopicsViewedAllTime: number;
  postsReadAllTime: number;
  minPostsReadAllTime: number;
  numFlaggedPosts: number;
  maxFlaggedPosts: number;
  numFlaggedByUsers: number;
  maxFlaggedByUsers: number;
  numLikesGiven: number;
  minLikesGiven: number;
  numLikesReceived: number;
  minLikesReceived: number;
  numLikesReceivedDays: number;
  minLikesReceivedDays: number;
  numLikesReceivedUsers: number;
  minLikesReceivedUsers: number;
  penaltyCounts: PenaltyCounts1;
}

export const tl3RequirementsSchema: Schema<Tl3Requirements> = lazy(() =>
  object({
    timePeriod: ['time_period', number()],
    requirementsMet: ['requirements_met', boolean()],
    requirementsLost: ['requirements_lost', boolean()],
    trustLevelLocked: ['trust_level_locked', boolean()],
    onGracePeriod: ['on_grace_period', boolean()],
    daysVisited: ['days_visited', number()],
    minDaysVisited: ['min_days_visited', number()],
    numTopicsRepliedTo: ['num_topics_replied_to', number()],
    minTopicsRepliedTo: ['min_topics_replied_to', number()],
    topicsViewed: ['topics_viewed', number()],
    minTopicsViewed: ['min_topics_viewed', number()],
    postsRead: ['posts_read', number()],
    minPostsRead: ['min_posts_read', number()],
    topicsViewedAllTime: ['topics_viewed_all_time', number()],
    minTopicsViewedAllTime: ['min_topics_viewed_all_time', number()],
    postsReadAllTime: ['posts_read_all_time', number()],
    minPostsReadAllTime: ['min_posts_read_all_time', number()],
    numFlaggedPosts: ['num_flagged_posts', number()],
    maxFlaggedPosts: ['max_flagged_posts', number()],
    numFlaggedByUsers: ['num_flagged_by_users', number()],
    maxFlaggedByUsers: ['max_flagged_by_users', number()],
    numLikesGiven: ['num_likes_given', number()],
    minLikesGiven: ['min_likes_given', number()],
    numLikesReceived: ['num_likes_received', number()],
    minLikesReceived: ['min_likes_received', number()],
    numLikesReceivedDays: ['num_likes_received_days', number()],
    minLikesReceivedDays: ['min_likes_received_days', number()],
    numLikesReceivedUsers: ['num_likes_received_users', number()],
    minLikesReceivedUsers: ['min_likes_received_users', number()],
    penaltyCounts: ['penalty_counts', penaltyCounts1Schema],
  })
);
