/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TNotificationsJsonResponse {
  success?: string;
  additionalProperties?: Record<string, unknown>;
}

export const tNotificationsJsonResponseSchema: Schema<TNotificationsJsonResponse> = typedExpandoObject(
  { success: ['success', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
