/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import {
  NotificationLevel,
  notificationLevelSchema,
} from './notificationLevel.js';

export interface TNotificationsJsonRequest {
  notificationLevel: NotificationLevel;
  additionalProperties?: Record<string, unknown>;
}

export const tNotificationsJsonRequestSchema: Schema<TNotificationsJsonRequest> = typedExpandoObject(
  { notificationLevel: ['notification_level', notificationLevelSchema] },
  'additionalProperties',
  optional(unknown())
);
