/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Topic7, topic7Schema } from './topic7.js';

export interface TopicList5 {
  canCreateTopic?: boolean;
  draft?: string | null;
  draftKey?: string;
  draftSequence?: number;
  forPeriod?: string;
  perPage?: number;
  topics?: Topic7[];
  additionalProperties?: Record<string, unknown>;
}

export const topicList5Schema: Schema<TopicList5> = lazy(() =>
  typedExpandoObject(
    {
      canCreateTopic: ['can_create_topic', optional(boolean())],
      draft: ['draft', optional(nullable(string()))],
      draftKey: ['draft_key', optional(string())],
      draftSequence: ['draft_sequence', optional(number())],
      forPeriod: ['for_period', optional(string())],
      perPage: ['per_page', optional(number())],
      topics: ['topics', optional(array(topic7Schema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
