/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { Poster, posterSchema } from './poster.js';

export interface Topic1 {
  id: number;
  title: string;
  fancyTitle: string;
  slug: string;
  postsCount: number;
  replyCount: number;
  highestPostNumber: number;
  imageUrl: string | null;
  createdAt: string;
  lastPostedAt: string;
  bumped: boolean;
  bumpedAt: string;
  archetype: string;
  unseen: boolean;
  pinned: boolean;
  unpinned: string | null;
  excerpt: string;
  visible: boolean;
  closed: boolean;
  archived: boolean;
  bookmarked: string | null;
  liked: string | null;
  views: number;
  likeCount: number;
  hasSummary: boolean;
  lastPosterUsername: string;
  categoryId: number;
  pinnedGlobally: boolean;
  featuredLink: string | null;
  posters: Poster[];
}

export const topic1Schema: Schema<Topic1> = lazy(() =>
  object({
    id: ['id', number()],
    title: ['title', string()],
    fancyTitle: ['fancy_title', string()],
    slug: ['slug', string()],
    postsCount: ['posts_count', number()],
    replyCount: ['reply_count', number()],
    highestPostNumber: ['highest_post_number', number()],
    imageUrl: ['image_url', nullable(string())],
    createdAt: ['created_at', string()],
    lastPostedAt: ['last_posted_at', string()],
    bumped: ['bumped', boolean()],
    bumpedAt: ['bumped_at', string()],
    archetype: ['archetype', string()],
    unseen: ['unseen', boolean()],
    pinned: ['pinned', boolean()],
    unpinned: ['unpinned', nullable(string())],
    excerpt: ['excerpt', string()],
    visible: ['visible', boolean()],
    closed: ['closed', boolean()],
    archived: ['archived', boolean()],
    bookmarked: ['bookmarked', nullable(string())],
    liked: ['liked', nullable(string())],
    views: ['views', number()],
    likeCount: ['like_count', number()],
    hasSummary: ['has_summary', boolean()],
    lastPosterUsername: ['last_poster_username', string()],
    categoryId: ['category_id', number()],
    pinnedGlobally: ['pinned_globally', boolean()],
    featuredLink: ['featured_link', nullable(string())],
    posters: ['posters', array(posterSchema)],
  })
);
