/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TopicList2, topicList2Schema } from './topicList2.js';
import { User2, user2Schema } from './user2.js';

export interface TopicsPrivateMessagesSentJsonResponse {
  users?: User2[];
  primaryGroups?: unknown[];
  topicList?: TopicList2;
  additionalProperties?: Record<string, unknown>;
}

export const topicsPrivateMessagesSentJsonResponseSchema: Schema<TopicsPrivateMessagesSentJsonResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        users: ['users', optional(array(user2Schema))],
        primaryGroups: ['primary_groups', optional(array(unknown()))],
        topicList: ['topic_list', optional(topicList2Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
