/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
} from '../schema.js';
import { Topic1, topic1Schema } from './topic1.js';
import { TopTag, topTagSchema } from './topTag.js';

export interface TopicList {
  canCreateTopic: boolean;
  perPage: number;
  topTags?: TopTag[];
  topics: Topic1[];
}

export const topicListSchema: Schema<TopicList> = lazy(() =>
  object({
    canCreateTopic: ['can_create_topic', boolean()],
    perPage: ['per_page', number()],
    topTags: ['top_tags', optional(array(topTagSchema))],
    topics: ['topics', array(topic1Schema)],
  })
);
