/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Topic6, topic6Schema } from './topic6.js';

export interface TopicList4 {
  canCreateTopic?: boolean;
  draft?: string | null;
  draftKey?: string;
  draftSequence?: number;
  perPage?: number;
  topics?: Topic6[];
  additionalProperties?: Record<string, unknown>;
}

export const topicList4Schema: Schema<TopicList4> = lazy(() =>
  typedExpandoObject(
    {
      canCreateTopic: ['can_create_topic', optional(boolean())],
      draft: ['draft', optional(nullable(string()))],
      draftKey: ['draft_key', optional(string())],
      draftSequence: ['draft_sequence', optional(number())],
      perPage: ['per_page', optional(number())],
      topics: ['topics', optional(array(topic6Schema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
