/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface Topic {
  id: number;
  title: string;
  tags: string[];
  tagsDescriptions?: unknown;
  slug: string;
}

export const topicSchema: Schema<Topic> = object({
  id: ['id', number()],
  title: ['title', string()],
  tags: ['tags', array(string())],
  tagsDescriptions: ['tags_descriptions', optional(unknown())],
  slug: ['slug', string()],
});
