/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Poster1, poster1Schema } from './poster1.js';

export interface Topic6 {
  id?: number;
  title?: string;
  fancyTitle?: string;
  slug?: string;
  postsCount?: number;
  replyCount?: number;
  highestPostNumber?: number;
  imageUrl?: string;
  createdAt?: string;
  lastPostedAt?: string;
  bumped?: boolean;
  bumpedAt?: string;
  archetype?: string;
  unseen?: boolean;
  lastReadPostNumber?: number;
  unreadPosts?: number;
  pinned?: boolean;
  unpinned?: string | null;
  visible?: boolean;
  closed?: boolean;
  archived?: boolean;
  notificationLevel?: number;
  bookmarked?: boolean;
  liked?: boolean;
  views?: number;
  likeCount?: number;
  hasSummary?: boolean;
  lastPosterUsername?: string;
  categoryId?: number;
  opLikeCount?: number;
  pinnedGlobally?: boolean;
  featuredLink?: string | null;
  posters?: Poster1[];
  additionalProperties?: Record<string, unknown>;
}

export const topic6Schema: Schema<Topic6> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', optional(number())],
      title: ['title', optional(string())],
      fancyTitle: ['fancy_title', optional(string())],
      slug: ['slug', optional(string())],
      postsCount: ['posts_count', optional(number())],
      replyCount: ['reply_count', optional(number())],
      highestPostNumber: ['highest_post_number', optional(number())],
      imageUrl: ['image_url', optional(string())],
      createdAt: ['created_at', optional(string())],
      lastPostedAt: ['last_posted_at', optional(string())],
      bumped: ['bumped', optional(boolean())],
      bumpedAt: ['bumped_at', optional(string())],
      archetype: ['archetype', optional(string())],
      unseen: ['unseen', optional(boolean())],
      lastReadPostNumber: ['last_read_post_number', optional(number())],
      unreadPosts: ['unread_posts', optional(number())],
      pinned: ['pinned', optional(boolean())],
      unpinned: ['unpinned', optional(nullable(string()))],
      visible: ['visible', optional(boolean())],
      closed: ['closed', optional(boolean())],
      archived: ['archived', optional(boolean())],
      notificationLevel: ['notification_level', optional(number())],
      bookmarked: ['bookmarked', optional(boolean())],
      liked: ['liked', optional(boolean())],
      views: ['views', optional(number())],
      likeCount: ['like_count', optional(number())],
      hasSummary: ['has_summary', optional(boolean())],
      lastPosterUsername: ['last_poster_username', optional(string())],
      categoryId: ['category_id', optional(number())],
      opLikeCount: ['op_like_count', optional(number())],
      pinnedGlobally: ['pinned_globally', optional(boolean())],
      featuredLink: ['featured_link', optional(nullable(string()))],
      posters: ['posters', optional(array(poster1Schema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
