/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TopicList1, topicList1Schema } from './topicList1.js';
import { User1, user1Schema } from './user1.js';

export interface TopicsPrivateMessagesJsonResponse {
  users?: User1[];
  primaryGroups?: unknown[];
  topicList?: TopicList1;
  additionalProperties?: Record<string, unknown>;
}

export const topicsPrivateMessagesJsonResponseSchema: Schema<TopicsPrivateMessagesJsonResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        users: ['users', optional(array(user1Schema))],
        primaryGroups: ['primary_groups', optional(array(unknown()))],
        topicList: ['topic_list', optional(topicList1Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
