/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Topic5 {
  title?: string;
  categoryId?: number;
  additionalProperties?: Record<string, unknown>;
}

export const topic5Schema: Schema<Topic5> = typedExpandoObject(
  {
    title: ['title', optional(string())],
    categoryId: ['category_id', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
