/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Tag4, tag4Schema } from './tag4.js';
import { Topic4, topic4Schema } from './topic4.js';

export interface TopicList3 {
  canCreateTopic?: boolean;
  draft?: string | null;
  draftKey?: string;
  draftSequence?: number;
  perPage?: number;
  tags?: Tag4[];
  topics?: Topic4[];
  additionalProperties?: Record<string, unknown>;
}

export const topicList3Schema: Schema<TopicList3> = lazy(() =>
  typedExpandoObject(
    {
      canCreateTopic: ['can_create_topic', optional(boolean())],
      draft: ['draft', optional(nullable(string()))],
      draftKey: ['draft_key', optional(string())],
      draftSequence: ['draft_sequence', optional(number())],
      perPage: ['per_page', optional(number())],
      tags: ['tags', optional(array(tag4Schema))],
      topics: ['topics', optional(array(topic4Schema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
