/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TopicList5, topicList5Schema } from './topicList5.js';
import { User1, user1Schema } from './user1.js';

export interface TopJsonResponse {
  users?: User1[];
  primaryGroups?: unknown[];
  topicList?: TopicList5;
  additionalProperties?: Record<string, unknown>;
}

export const topJsonResponseSchema: Schema<TopJsonResponse> = lazy(() =>
  typedExpandoObject(
    {
      users: ['users', optional(array(user1Schema))],
      primaryGroups: ['primary_groups', optional(array(unknown()))],
      topicList: ['topic_list', optional(topicList5Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
