/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PostStream, postStreamSchema } from './postStream.js';

export interface TPostsJsonResponse {
  postStream?: PostStream;
  id?: number;
  additionalProperties?: Record<string, unknown>;
}

export const tPostsJsonResponseSchema: Schema<TPostsJsonResponse> = lazy(() =>
  typedExpandoObject(
    {
      postStream: ['post_stream', optional(postStreamSchema)],
      id: ['id', optional(number())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
