/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface Triggers {
  userChange: number;
  none: number;
  postRevision: number;
  trustLevelChange: number;
  postAction: number;
}

export const triggersSchema: Schema<Triggers> = object({
  userChange: ['user_change', number()],
  none: ['none', number()],
  postRevision: ['post_revision', number()],
  trustLevelChange: ['trust_level_change', number()],
  postAction: ['post_action', number()],
});
