/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface TrustLevels {
  newuser: number;
  basic: number;
  member: number;
  regular: number;
  leader: number;
}

export const trustLevelsSchema: Schema<TrustLevels> = object({
  newuser: ['newuser', number()],
  basic: ['basic', number()],
  member: ['member', number()],
  regular: ['regular', number()],
  leader: ['leader', number()],
});
