/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TStatusJsonResponse {
  success?: string;
  topicStatusUpdate?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const tStatusJsonResponseSchema: Schema<TStatusJsonResponse> = typedExpandoObject(
  {
    success: ['success', optional(string())],
    topicStatusUpdate: ['topic_status_update', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
