/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Enabled, enabledSchema } from './enabled.js';
import { Status1, status1Schema } from './status1.js';

export interface TStatusJsonRequest {
  status: Status1;
  enabled: Enabled;
  /** Only required for `pinned` and `pinned_globally` */
  until?: string;
  additionalProperties?: Record<string, unknown>;
}

export const tStatusJsonRequestSchema: Schema<TStatusJsonRequest> = typedExpandoObject(
  {
    status: ['status', status1Schema],
    enabled: ['enabled', enabledSchema],
    until: ['until', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
