/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TTimerJsonResponse {
  success?: string;
  executeAt?: string;
  duration?: string | null;
  basedOnLastPost?: boolean;
  closed?: boolean;
  categoryId?: number | null;
  additionalProperties?: Record<string, unknown>;
}

export const tTimerJsonResponseSchema: Schema<TTimerJsonResponse> = typedExpandoObject(
  {
    success: ['success', optional(string())],
    executeAt: ['execute_at', optional(string())],
    duration: ['duration', optional(nullable(string()))],
    basedOnLastPost: ['based_on_last_post', optional(boolean())],
    closed: ['closed', optional(boolean())],
    categoryId: ['category_id', optional(nullable(number()))],
  },
  'additionalProperties',
  optional(unknown())
);
