/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TTimerJsonRequest {
  time?: string;
  statusType?: string;
  basedOnLastPost?: boolean;
  categoryId?: number;
  additionalProperties?: Record<string, unknown>;
}

export const tTimerJsonRequestSchema: Schema<TTimerJsonRequest> = typedExpandoObject(
  {
    time: ['time', optional(string())],
    statusType: ['status_type', optional(string())],
    basedOnLastPost: ['based_on_last_post', optional(boolean())],
    categoryId: ['category_id', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
