/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, unknown } from '../schema.js';
import { User8, user8Schema } from './user8.js';

export interface UByExternalJsonResponse {
  userBadges: unknown[];
  user: User8;
}

export const uByExternalJsonResponseSchema: Schema<UByExternalJsonResponse> = lazy(
  () =>
    object({
      userBadges: ['user_badges', array(unknown())],
      user: ['user', user8Schema],
    })
);
