/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema.js';

export interface UEmailsJsonResponse {
  email: string;
  secondaryEmails: unknown[];
  unconfirmedEmails: unknown[];
  associatedAccounts: unknown[];
}

export const uEmailsJsonResponseSchema: Schema<UEmailsJsonResponse> = object({
  email: ['email', string()],
  secondaryEmails: ['secondary_emails', array(unknown())],
  unconfirmedEmails: ['unconfirmed_emails', array(unknown())],
  associatedAccounts: ['associated_accounts', array(unknown())],
});
