/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, unknown } from '../schema.js';
import { User8, user8Schema } from './user8.js';

export interface UJsonResponse {
  userBadges: unknown[];
  user: User8;
}

export const uJsonResponseSchema: Schema<UJsonResponse> = lazy(() =>
  object({
    userBadges: ['user_badges', array(unknown())],
    user: ['user', user8Schema],
  })
);
