/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema.js';

export interface UJsonResponse1 {
  success: string;
  user?: unknown;
}

export const uJsonResponse1Schema: Schema<UJsonResponse1> = object({
  success: ['success', string()],
  user: ['user', optional(unknown())],
});
