/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema.js';

export interface UJsonRequest {
  name?: string;
  externalIds?: unknown;
}

export const uJsonRequestSchema: Schema<UJsonRequest> = object({
  name: ['name', optional(string())],
  externalIds: ['external_ids', optional(unknown())],
});
