/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, Schema, string } from '../schema.js';
import { Reason, reasonSchema } from './reason.js';

export interface UpcomingChangesStat {
  name: string;
  humanizedName: string;
  description: string;
  enabled: boolean;
  specificGroups: string[];
  reason: Reason;
}

export const upcomingChangesStatSchema: Schema<UpcomingChangesStat> = object({
  name: ['name', string()],
  humanizedName: ['humanized_name', string()],
  description: ['description', string()],
  enabled: ['enabled', boolean()],
  specificGroups: ['specific_groups', array(string())],
  reason: ['reason', reasonSchema],
});
