/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { OptimizedVideo, optimizedVideoSchema } from './optimizedVideo.js';
import { Thumbnail, thumbnailSchema } from './thumbnail.js';

export interface UploadsCompleteExternalUploadJsonResponse {
  id: number;
  url: string;
  originalFilename: string;
  filesize: number;
  width: number;
  height: number;
  thumbnailWidth: number;
  thumbnailHeight: number;
  extension: string;
  shortUrl: string;
  shortPath: string;
  retainHours: string | null;
  humanFilesize: string;
  dominantColor?: string | null;
  thumbnail?: Thumbnail | null;
  optimizedVideo?: OptimizedVideo | null;
}

export const uploadsCompleteExternalUploadJsonResponseSchema: Schema<UploadsCompleteExternalUploadJsonResponse> = lazy(
  () =>
    object({
      id: ['id', number()],
      url: ['url', string()],
      originalFilename: ['original_filename', string()],
      filesize: ['filesize', number()],
      width: ['width', number()],
      height: ['height', number()],
      thumbnailWidth: ['thumbnail_width', number()],
      thumbnailHeight: ['thumbnail_height', number()],
      extension: ['extension', string()],
      shortUrl: ['short_url', string()],
      shortPath: ['short_path', string()],
      retainHours: ['retain_hours', nullable(string())],
      humanFilesize: ['human_filesize', string()],
      dominantColor: ['dominant_color', optional(nullable(string()))],
      thumbnail: ['thumbnail', optional(nullable(thumbnailSchema))],
      optimizedVideo: [
        'optimized_video',
        optional(nullable(optimizedVideoSchema)),
      ],
    })
);
