/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface UploadsAbortMultipartJsonRequest {
  /**
   * The identifier of the multipart upload in the external
   * storage provider. This is the multipart upload_id in AWS S3.
   */
  externalUploadIdentifier: string;
}

export const uploadsAbortMultipartJsonRequestSchema: Schema<UploadsAbortMultipartJsonRequest> = object(
  { externalUploadIdentifier: ['external_upload_identifier', string()] }
);
