/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema.js';

export interface UploadsCompleteMultipartJsonRequest {
  /**
   * The unique identifier returned in the original /create-multipart
   * request.
   */
  uniqueIdentifier: string;
  /**
   * All of the part numbers and their corresponding ETags
   * that have been uploaded must be provided.
   */
  parts: unknown[];
}

export const uploadsCompleteMultipartJsonRequestSchema: Schema<UploadsCompleteMultipartJsonRequest> = object(
  {
    uniqueIdentifier: ['unique_identifier', string()],
    parts: ['parts', array(unknown())],
  }
);
