/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema.js';
import { Metadata, metadataSchema } from './metadata.js';
import { Type, typeSchema } from './type.js';

export interface UploadsGeneratePresignedPutJsonRequest {
  type: Type;
  fileName: string;
  /** File size should be represented in bytes. */
  fileSize: number;
  metadata?: Metadata;
}

export const uploadsGeneratePresignedPutJsonRequestSchema: Schema<UploadsGeneratePresignedPutJsonRequest> = lazy(
  () =>
    object({
      type: ['type', typeSchema],
      fileName: ['file_name', string()],
      fileSize: ['file_size', number()],
      metadata: ['metadata', optional(metadataSchema)],
    })
);
