/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema.js';

export interface UploadsGeneratePresignedPutJsonResponse {
  /**
   * The path of the temporary file on the external storage
   * service.
   */
  key?: string;
  /**
   * A presigned PUT URL which must be used to upload
   * the file binary blob to.
   */
  url?: string;
  /** A map of headers that must be sent with the PUT request. */
  signedHeaders?: unknown;
  /**
   * A unique string that identifies the external upload.
   * This must be stored and then sent in the /complete-external-upload
   * endpoint to complete the direct upload.
   */
  uniqueIdentifier?: string;
}

export const uploadsGeneratePresignedPutJsonResponseSchema: Schema<UploadsGeneratePresignedPutJsonResponse> = object(
  {
    key: ['key', optional(string())],
    url: ['url', optional(string())],
    signedHeaders: ['signed_headers', optional(unknown())],
    uniqueIdentifier: ['unique_identifier', optional(string())],
  }
);
