/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UploadType1
 */
export enum UploadType1 {
  Avatar = 'avatar',
  ProfileBackground = 'profile_background',
  CardBackground = 'card_background',
  CustomEmoji = 'custom_emoji',
  Composer = 'composer',
}

/**
 * Schema for UploadType1
 */
export const uploadType1Schema: Schema<UploadType1> = stringEnum(UploadType1);
