/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema.js';

export interface UploadsBatchPresignMultipartPartsJsonResponse {
  /**
   * The presigned URLs for each part number, which has
   * the part numbers as keys.
   */
  presignedUrls?: unknown;
}

export const uploadsBatchPresignMultipartPartsJsonResponseSchema: Schema<UploadsBatchPresignMultipartPartsJsonResponse> = object(
  { presignedUrls: ['presigned_urls', optional(unknown())] }
);
