/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface UploadsCreateMultipartJsonResponse {
  /**
   * The path of the temporary file on the external storage
   * service.
   */
  key: string;
  /**
   * The identifier of the multipart upload in the external
   * storage provider. This is the multipart upload_id in AWS S3.
   */
  externalUploadIdentifier: string;
  /**
   * A unique string that identifies the external upload.
   * This must be stored and then sent in the /complete-multipart
   * and /batch-presign-multipart-parts endpoints.
   */
  uniqueIdentifier: string;
}

export const uploadsCreateMultipartJsonResponseSchema: Schema<UploadsCreateMultipartJsonResponse> = object(
  {
    key: ['key', string()],
    externalUploadIdentifier: ['external_upload_identifier', string()],
    uniqueIdentifier: ['unique_identifier', string()],
  }
);
