/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UploadType
 */
export enum UploadType {
  Avatar = 'avatar',
  ProfileBackground = 'profile_background',
  CardBackground = 'card_background',
  CustomEmoji = 'custom_emoji',
  Composer = 'composer',
}

/**
 * Schema for UploadType
 */
export const uploadTypeSchema: Schema<UploadType> = stringEnum(UploadType);
