/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema.js';

export interface UploadsBatchPresignMultipartPartsJsonRequest {
  /**
   * The part numbers to generate the presigned URLs for,
   * must be between 1 and 10000.
   */
  partNumbers: unknown[];
  /**
   * The unique identifier returned in the original /create-multipart
   * request.
   */
  uniqueIdentifier: string;
}

export const uploadsBatchPresignMultipartPartsJsonRequestSchema: Schema<UploadsBatchPresignMultipartPartsJsonRequest> = object(
  {
    partNumbers: ['part_numbers', array(unknown())],
    uniqueIdentifier: ['unique_identifier', string()],
  }
);
