/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface UploadsCompleteExternalUploadJsonRequest {
  /**
   * The unique identifier returned in the original /generate-presigned-put
   * request.
   */
  uniqueIdentifier: string;
  /**
   * Optionally set this to true if the upload is for a
   * private message.
   */
  forPrivateMessage?: string;
  /**
   * Optionally set this to true if the upload is for a
   * site setting.
   */
  forSiteSetting?: string;
  /**
   * Optionally set this to true if the upload was pasted
   * into the upload area. This will convert PNG files to JPEG.
   */
  pasted?: string;
}

export const uploadsCompleteExternalUploadJsonRequestSchema: Schema<UploadsCompleteExternalUploadJsonRequest> = object(
  {
    uniqueIdentifier: ['unique_identifier', string()],
    forPrivateMessage: ['for_private_message', optional(string())],
    forSiteSetting: ['for_site_setting', optional(string())],
    pasted: ['pasted', optional(string())],
  }
);
