/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema.js';
import { Metadata, metadataSchema } from './metadata.js';
import { UploadType1, uploadType1Schema } from './uploadType1.js';

export interface UploadsCreateMultipartJsonRequest {
  uploadType: UploadType1;
  fileName: string;
  /** File size should be represented in bytes. */
  fileSize: number;
  metadata?: Metadata;
}

export const uploadsCreateMultipartJsonRequestSchema: Schema<UploadsCreateMultipartJsonRequest> = lazy(
  () =>
    object({
      uploadType: ['upload_type', uploadType1Schema],
      fileName: ['file_name', string()],
      fileSize: ['file_size', number()],
      metadata: ['metadata', optional(metadataSchema)],
    })
);
