/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface UPreferencesUsernameJsonRequest {
  newUsername: string;
}

export const uPreferencesUsernameJsonRequestSchema: Schema<UPreferencesUsernameJsonRequest> = object(
  { newUsername: ['new_username', string()] }
);
