/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';
import { Type1, type1Schema } from './type1.js';

export interface UPreferencesAvatarPickJsonRequest {
  uploadId: number;
  type: Type1;
}

export const uPreferencesAvatarPickJsonRequestSchema: Schema<UPreferencesAvatarPickJsonRequest> = object(
  { uploadId: ['upload_id', number()], type: ['type', type1Schema] }
);
