/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface UPreferencesEmailJsonRequest {
  email: string;
}

export const uPreferencesEmailJsonRequestSchema: Schema<UPreferencesEmailJsonRequest> = object(
  { email: ['email', string()] }
);
