/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface UPreferencesAvatarPickJsonResponse {
  success: string;
}

export const uPreferencesAvatarPickJsonResponseSchema: Schema<UPreferencesAvatarPickJsonResponse> = object(
  { success: ['success', string()] }
);
