/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface UsersPasswordResetJsonRequest {
  username: string;
  password: string;
}

export const usersPasswordResetJsonRequestSchema: Schema<UsersPasswordResetJsonRequest> = object(
  { username: ['username', string()], password: ['password', string()] }
);
