/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface UsersJsonRequest {
  name: string;
  email: string;
  password: string;
  username: string;
  /**
   * This param requires an admin api key in the request
   * header or it will be ignored
   */
  active?: boolean;
  approved?: boolean;
  userFields?: Record<string, boolean>;
  externalIds?: unknown;
}

export const usersJsonRequestSchema: Schema<UsersJsonRequest> = object({
  name: ['name', string()],
  email: ['email', string()],
  password: ['password', string()],
  username: ['username', string()],
  active: ['active', optional(boolean())],
  approved: ['approved', optional(boolean())],
  userFields: ['user_fields', optional(dict(boolean()))],
  externalIds: ['external_ids', optional(unknown())],
});
