/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface User1 {
  id?: number;
  username?: string;
  name?: string;
  avatarTemplate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const user1Schema: Schema<User1> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    username: ['username', optional(string())],
    name: ['name', optional(string())],
    avatarTemplate: ['avatar_template', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
