/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface UserTheme {
  themeId: number;
  name: string;
  mDefault: boolean;
  colorSchemeId: number | null;
  darkColorSchemeId?: number | null;
  onlyThemeColorSchemes?: boolean;
}

export const userThemeSchema: Schema<UserTheme> = object({
  themeId: ['theme_id', number()],
  name: ['name', string()],
  mDefault: ['default', boolean()],
  colorSchemeId: ['color_scheme_id', nullable(number())],
  darkColorSchemeId: ['dark_color_scheme_id', optional(nullable(number()))],
  onlyThemeColorSchemes: ['only_theme_color_schemes', optional(boolean())],
});
