/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { UserAction, userActionSchema } from './userAction.js';

export interface UserActionsJsonResponse {
  userActions: UserAction[];
}

export const userActionsJsonResponseSchema: Schema<UserActionsJsonResponse> = lazy(
  () => object({ userActions: ['user_actions', array(userActionSchema)] })
);
