/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface UserTips {
  firstNotification: number;
  topicTimeline: number;
  postMenu: number;
  topicNotificationLevels: number;
  suggestedTopics: number;
}

export const userTipsSchema: Schema<UserTips> = object({
  firstNotification: ['first_notification', number()],
  topicTimeline: ['topic_timeline', number()],
  postMenu: ['post_menu', number()],
  topicNotificationLevels: ['topic_notification_levels', number()],
  suggestedTopics: ['suggested_topics', number()],
});
