/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema } from '../schema.js';

export interface UserNotificationSchedule {
  enabled: boolean;
  day0StartTime: number;
  day0EndTime: number;
  day1StartTime: number;
  day1EndTime: number;
  day2StartTime: number;
  day2EndTime: number;
  day3StartTime: number;
  day3EndTime: number;
  day4StartTime: number;
  day4EndTime: number;
  day5StartTime: number;
  day5EndTime: number;
  day6StartTime: number;
  day6EndTime: number;
}

export const userNotificationScheduleSchema: Schema<UserNotificationSchedule> = object(
  {
    enabled: ['enabled', boolean()],
    day0StartTime: ['day_0_start_time', number()],
    day0EndTime: ['day_0_end_time', number()],
    day1StartTime: ['day_1_start_time', number()],
    day1EndTime: ['day_1_end_time', number()],
    day2StartTime: ['day_2_start_time', number()],
    day2EndTime: ['day_2_end_time', number()],
    day3StartTime: ['day_3_start_time', number()],
    day3EndTime: ['day_3_end_time', number()],
    day4StartTime: ['day_4_start_time', number()],
    day4EndTime: ['day_4_end_time', number()],
    day5StartTime: ['day_5_start_time', number()],
    day5EndTime: ['day_5_end_time', number()],
    day6StartTime: ['day_6_start_time', number()],
    day6EndTime: ['day_6_end_time', number()],
  }
);
