/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema.js';

export interface UserAuthToken {
  id: number;
  clientIp: string;
  location: string;
  browser: string;
  device: string;
  os: string;
  icon: string;
  createdAt: string;
  seenAt: string;
  isActive: boolean;
}

export const userAuthTokenSchema: Schema<UserAuthToken> = object({
  id: ['id', number()],
  clientIp: ['client_ip', string()],
  location: ['location', string()],
  browser: ['browser', string()],
  device: ['device', string()],
  os: ['os', string()],
  icon: ['icon', string()],
  createdAt: ['created_at', string()],
  seenAt: ['seen_at', string()],
  isActive: ['is_active', boolean()],
});
