/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';

export interface UserBadge {
  id: number;
  grantedAt: string;
  groupingPosition: number;
  isFavorite: string | null;
  canFavorite: boolean;
  badgeId: number;
  grantedById: number;
}

export const userBadgeSchema: Schema<UserBadge> = object({
  id: ['id', number()],
  grantedAt: ['granted_at', string()],
  groupingPosition: ['grouping_position', number()],
  isFavorite: ['is_favorite', nullable(string())],
  canFavorite: ['can_favorite', boolean()],
  badgeId: ['badge_id', number()],
  grantedById: ['granted_by_id', number()],
});
