/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface User2 {
  id?: number;
  username?: string;
  name?: string | null;
  avatarTemplate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const user2Schema: Schema<User2> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    username: ['username', optional(string())],
    name: ['name', optional(nullable(string()))],
    avatarTemplate: ['avatar_template', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
