/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface UsersJsonResponse {
  success: boolean;
  active: boolean;
  message: string;
  userId?: number;
}

export const usersJsonResponseSchema: Schema<UsersJsonResponse> = object({
  success: ['success', boolean()],
  active: ['active', boolean()],
  message: ['message', string()],
  userId: ['user_id', optional(number())],
});
