/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema.js';

export interface UserAvatarRefreshGravatarJsonResponse {
  gravatarUploadId: number | null;
  gravatarAvatarTemplate: string | null;
}

export const userAvatarRefreshGravatarJsonResponseSchema: Schema<UserAvatarRefreshGravatarJsonResponse> = object(
  {
    gravatarUploadId: ['gravatar_upload_id', nullable(number())],
    gravatarAvatarTemplate: ['gravatar_avatar_template', nullable(string())],
  }
);
