/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Badge3, badge3Schema } from './badge3.js';
import { BadgeType, badgeTypeSchema } from './badgeType.js';
import { GrantedBy, grantedBySchema } from './grantedBy.js';
import { UserBadge, userBadgeSchema } from './userBadge.js';

export interface UserBadgesJsonResponse {
  badges?: Badge3[];
  badgeTypes?: BadgeType[];
  grantedBies?: GrantedBy[];
  userBadges: UserBadge[];
}

export const userBadgesJsonResponseSchema: Schema<UserBadgesJsonResponse> = lazy(
  () =>
    object({
      badges: ['badges', optional(array(badge3Schema))],
      badgeTypes: ['badge_types', optional(array(badgeTypeSchema))],
      grantedBies: ['granted_bies', optional(array(grantedBySchema))],
      userBadges: ['user_badges', array(userBadgeSchema)],
    })
);
