/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface UserColorScheme {
  id: number;
  name: string;
  isDark: boolean;
  themeId?: number | null;
  colors: unknown[];
}

export const userColorSchemeSchema: Schema<UserColorScheme> = object({
  id: ['id', number()],
  name: ['name', string()],
  isDark: ['is_dark', boolean()],
  themeId: ['theme_id', optional(nullable(number()))],
  colors: ['colors', array(unknown())],
});
