/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema.js';

export interface User11 {
  id: number;
  username: string;
  name: string | null;
  avatarTemplate: string;
  title: string | null;
}

export const user11Schema: Schema<User11> = object({
  id: ['id', number()],
  username: ['username', string()],
  name: ['name', nullable(string())],
  avatarTemplate: ['avatar_template', string()],
  title: ['title', nullable(string())],
});
