/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { CustomFields, customFieldsSchema } from './customFields.js';
import { FeaturedTopic, featuredTopicSchema } from './featuredTopic.js';
import { Group7, group7Schema } from './group7.js';
import { GroupUser, groupUserSchema } from './groupUser.js';
import { UserAuthToken, userAuthTokenSchema } from './userAuthToken.js';
import {
  UserNotificationSchedule,
  userNotificationScheduleSchema,
} from './userNotificationSchedule.js';
import { UserOption, userOptionSchema } from './userOption.js';

export interface User8 {
  id: number;
  username: string;
  name: string;
  avatarTemplate: string;
  lastPostedAt: string | null;
  lastSeenAt: string | null;
  createdAt: string;
  ignored: boolean;
  muted: boolean;
  canIgnoreUser: boolean;
  canIgnoreUsers?: boolean;
  canMuteUser: boolean;
  canMuteUsers?: boolean;
  canSendPrivateMessages: boolean;
  canSendPrivateMessageToUser: boolean;
  trustLevel: number;
  moderator: boolean;
  admin: boolean;
  title: string | null;
  badgeCount: number;
  secondFactorBackupEnabled?: boolean;
  userFields?: Record<string, string>;
  customFields: CustomFields;
  timeRead: number;
  recentTimeRead: number;
  primaryGroupId: number | null;
  primaryGroupName: string | null;
  flairGroupId: number | null;
  flairName: string | null;
  flairUrl: string | null;
  flairBgColor: string | null;
  flairColor: string | null;
  featuredTopic: FeaturedTopic;
  staged: boolean;
  canEdit: boolean;
  canEditUsername: boolean;
  canEditEmail: boolean;
  canEditName: boolean;
  uploadedAvatarId: number | null;
  hasTitleBadges: boolean;
  pendingCount: number;
  pendingPostsCount?: number;
  profileViewCount: number;
  secondFactorEnabled: boolean;
  canUploadProfileHeader: boolean;
  canUploadUserCardBackground: boolean;
  postCount: number;
  topicCount: number;
  canBeDeleted: boolean;
  canDeleteAllPosts: boolean;
  locale: string | null;
  mutedCategoryIds: unknown[];
  regularCategoryIds: unknown[];
  watchedTags: unknown[];
  watchingFirstPostTags: unknown[];
  trackedTags: unknown[];
  mutedTags: unknown[];
  trackedCategoryIds: unknown[];
  watchedCategoryIds: unknown[];
  watchedFirstPostCategoryIds: unknown[];
  systemAvatarUploadId: string | null;
  systemAvatarTemplate: string;
  mutedUsernames: unknown[];
  ignoredUsernames: unknown[];
  allowedPmUsernames: unknown[];
  mailingListPostsPerDay: number;
  canChangeBio: boolean;
  canChangeLocation: boolean;
  canChangeWebsite: boolean;
  canChangeTrackingPreferences: boolean;
  userApiKeys: string | null;
  userPasskeys?: unknown[];
  sidebarTags?: unknown[];
  sidebarCategoryIds?: unknown[];
  displaySidebarTags?: boolean;
  canPickThemeWithCustomHomepage?: boolean;
  userAuthTokens: UserAuthToken[];
  userNotificationSchedule: UserNotificationSchedule;
  useLogoSmallAsAvatar: boolean;
  featuredUserBadgeIds: unknown[];
  invitedBy: string | null;
  groups: Group7[];
  groupUsers: GroupUser[];
  userOption: UserOption;
}

export const user8Schema: Schema<User8> = lazy(() =>
  object({
    id: ['id', number()],
    username: ['username', string()],
    name: ['name', string()],
    avatarTemplate: ['avatar_template', string()],
    lastPostedAt: ['last_posted_at', nullable(string())],
    lastSeenAt: ['last_seen_at', nullable(string())],
    createdAt: ['created_at', string()],
    ignored: ['ignored', boolean()],
    muted: ['muted', boolean()],
    canIgnoreUser: ['can_ignore_user', boolean()],
    canIgnoreUsers: ['can_ignore_users', optional(boolean())],
    canMuteUser: ['can_mute_user', boolean()],
    canMuteUsers: ['can_mute_users', optional(boolean())],
    canSendPrivateMessages: ['can_send_private_messages', boolean()],
    canSendPrivateMessageToUser: [
      'can_send_private_message_to_user',
      boolean(),
    ],
    trustLevel: ['trust_level', number()],
    moderator: ['moderator', boolean()],
    admin: ['admin', boolean()],
    title: ['title', nullable(string())],
    badgeCount: ['badge_count', number()],
    secondFactorBackupEnabled: [
      'second_factor_backup_enabled',
      optional(boolean()),
    ],
    userFields: ['user_fields', optional(dict(string()))],
    customFields: ['custom_fields', customFieldsSchema],
    timeRead: ['time_read', number()],
    recentTimeRead: ['recent_time_read', number()],
    primaryGroupId: ['primary_group_id', nullable(number())],
    primaryGroupName: ['primary_group_name', nullable(string())],
    flairGroupId: ['flair_group_id', nullable(number())],
    flairName: ['flair_name', nullable(string())],
    flairUrl: ['flair_url', nullable(string())],
    flairBgColor: ['flair_bg_color', nullable(string())],
    flairColor: ['flair_color', nullable(string())],
    featuredTopic: ['featured_topic', featuredTopicSchema],
    staged: ['staged', boolean()],
    canEdit: ['can_edit', boolean()],
    canEditUsername: ['can_edit_username', boolean()],
    canEditEmail: ['can_edit_email', boolean()],
    canEditName: ['can_edit_name', boolean()],
    uploadedAvatarId: ['uploaded_avatar_id', nullable(number())],
    hasTitleBadges: ['has_title_badges', boolean()],
    pendingCount: ['pending_count', number()],
    pendingPostsCount: ['pending_posts_count', optional(number())],
    profileViewCount: ['profile_view_count', number()],
    secondFactorEnabled: ['second_factor_enabled', boolean()],
    canUploadProfileHeader: ['can_upload_profile_header', boolean()],
    canUploadUserCardBackground: ['can_upload_user_card_background', boolean()],
    postCount: ['post_count', number()],
    topicCount: ['topic_count', number()],
    canBeDeleted: ['can_be_deleted', boolean()],
    canDeleteAllPosts: ['can_delete_all_posts', boolean()],
    locale: ['locale', nullable(string())],
    mutedCategoryIds: ['muted_category_ids', array(unknown())],
    regularCategoryIds: ['regular_category_ids', array(unknown())],
    watchedTags: ['watched_tags', array(unknown())],
    watchingFirstPostTags: ['watching_first_post_tags', array(unknown())],
    trackedTags: ['tracked_tags', array(unknown())],
    mutedTags: ['muted_tags', array(unknown())],
    trackedCategoryIds: ['tracked_category_ids', array(unknown())],
    watchedCategoryIds: ['watched_category_ids', array(unknown())],
    watchedFirstPostCategoryIds: [
      'watched_first_post_category_ids',
      array(unknown()),
    ],
    systemAvatarUploadId: ['system_avatar_upload_id', nullable(string())],
    systemAvatarTemplate: ['system_avatar_template', string()],
    mutedUsernames: ['muted_usernames', array(unknown())],
    ignoredUsernames: ['ignored_usernames', array(unknown())],
    allowedPmUsernames: ['allowed_pm_usernames', array(unknown())],
    mailingListPostsPerDay: ['mailing_list_posts_per_day', number()],
    canChangeBio: ['can_change_bio', boolean()],
    canChangeLocation: ['can_change_location', boolean()],
    canChangeWebsite: ['can_change_website', boolean()],
    canChangeTrackingPreferences: [
      'can_change_tracking_preferences',
      boolean(),
    ],
    userApiKeys: ['user_api_keys', nullable(string())],
    userPasskeys: ['user_passkeys', optional(array(unknown()))],
    sidebarTags: ['sidebar_tags', optional(array(unknown()))],
    sidebarCategoryIds: ['sidebar_category_ids', optional(array(unknown()))],
    displaySidebarTags: ['display_sidebar_tags', optional(boolean())],
    canPickThemeWithCustomHomepage: [
      'can_pick_theme_with_custom_homepage',
      optional(boolean()),
    ],
    userAuthTokens: ['user_auth_tokens', array(userAuthTokenSchema)],
    userNotificationSchedule: [
      'user_notification_schedule',
      userNotificationScheduleSchema,
    ],
    useLogoSmallAsAvatar: ['use_logo_small_as_avatar', boolean()],
    featuredUserBadgeIds: ['featured_user_badge_ids', array(unknown())],
    invitedBy: ['invited_by', nullable(string())],
    groups: ['groups', array(group7Schema)],
    groupUsers: ['group_users', array(groupUserSchema)],
    userOption: ['user_option', userOptionSchema],
  })
);
