/**
 * Discourse API DocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';

export interface UserAction {
  excerpt: string;
  actionType: number;
  createdAt: string;
  avatarTemplate: string;
  actingAvatarTemplate: string;
  slug: string;
  topicId: number;
  targetUserId: number;
  targetName: string | null;
  targetUsername: string;
  postNumber: number;
  postId: string | null;
  username: string;
  name: string | null;
  userId: number;
  actingUsername: string;
  actingName: string | null;
  actingUserId: number;
  title: string;
  deleted: boolean;
  hidden: string | null;
  postType: string | null;
  actionCode: string | null;
  categoryId: number;
  closed: boolean;
  archived: boolean;
}

export const userActionSchema: Schema<UserAction> = object({
  excerpt: ['excerpt', string()],
  actionType: ['action_type', number()],
  createdAt: ['created_at', string()],
  avatarTemplate: ['avatar_template', string()],
  actingAvatarTemplate: ['acting_avatar_template', string()],
  slug: ['slug', string()],
  topicId: ['topic_id', number()],
  targetUserId: ['target_user_id', number()],
  targetName: ['target_name', nullable(string())],
  targetUsername: ['target_username', string()],
  postNumber: ['post_number', number()],
  postId: ['post_id', nullable(string())],
  username: ['username', string()],
  name: ['name', nullable(string())],
  userId: ['user_id', number()],
  actingUsername: ['acting_username', string()],
  actingName: ['acting_name', nullable(string())],
  actingUserId: ['acting_user_id', number()],
  title: ['title', string()],
  deleted: ['deleted', boolean()],
  hidden: ['hidden', nullable(string())],
  postType: ['post_type', nullable(string())],
  actionCode: ['action_code', nullable(string())],
  categoryId: ['category_id', number()],
  closed: ['closed', boolean()],
  archived: ['archived', boolean()],
});
