/**
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface UserOption {
  userId: number;
  mailingListMode: boolean;
  mailingListModeFrequency: number;
  emailDigests: boolean;
  emailLevel: number;
  emailMessagesLevel: number;
  externalLinksInNewTab: boolean;
  bookmarkAutoDeletePreference?: number;
  colorSchemeId: string | null;
  darkSchemeId: string | null;
  dynamicFavicon: boolean;
  enableQuoting: boolean;
  enableSmartLists: boolean;
  enableMarkdownMonospaceFont: boolean;
  enableDefer: boolean;
  digestAfterMinutes: number;
  automaticallyUnpinTopics: boolean;
  autoTrackTopicsAfterMsecs: number;
  notificationLevelWhenReplying: number;
  newTopicDurationMinutes: number;
  emailPreviousReplies: number;
  emailInReplyTo: boolean;
  likeNotificationFrequency: number;
  notifyOnLinkedPosts: boolean;
  pushNotificationLevel: string;
  enableUpcomingChangeAvailableNotifications: boolean;
  includeTl0InDigests: boolean;
  themeIds: unknown[];
  themeKeySeq: number;
  allowPrivateMessages: boolean;
  enableAllowedPmUsers: boolean;
  homepageId: string | null;
  hideProfileAndPresence: boolean;
  hideProfile: boolean;
  hidePresence: boolean;
  textSize: string;
  textSizeSeq: number;
  titleCountMode: string;
  timezone: string | null;
  skipNewUserTips: boolean;
  defaultCalendar?: string;
  oldestSearchLogDate?: string | null;
  sidebarLinkToFilteredList?: boolean;
  sidebarShowCountOfNewItems?: boolean;
  watchedPrecedenceOverMuted?: boolean;
  seenPopups?: string | null;
  topicsUnreadWhenClosed: boolean;
  compositionMode?: number;
  interfaceColorMode: number;
  showOriginalContent: boolean;
}

export const userOptionSchema: Schema<UserOption> = object({
  userId: ['user_id', number()],
  mailingListMode: ['mailing_list_mode', boolean()],
  mailingListModeFrequency: ['mailing_list_mode_frequency', number()],
  emailDigests: ['email_digests', boolean()],
  emailLevel: ['email_level', number()],
  emailMessagesLevel: ['email_messages_level', number()],
  externalLinksInNewTab: ['external_links_in_new_tab', boolean()],
  bookmarkAutoDeletePreference: [
    'bookmark_auto_delete_preference',
    optional(number()),
  ],
  colorSchemeId: ['color_scheme_id', nullable(string())],
  darkSchemeId: ['dark_scheme_id', nullable(string())],
  dynamicFavicon: ['dynamic_favicon', boolean()],
  enableQuoting: ['enable_quoting', boolean()],
  enableSmartLists: ['enable_smart_lists', boolean()],
  enableMarkdownMonospaceFont: ['enable_markdown_monospace_font', boolean()],
  enableDefer: ['enable_defer', boolean()],
  digestAfterMinutes: ['digest_after_minutes', number()],
  automaticallyUnpinTopics: ['automatically_unpin_topics', boolean()],
  autoTrackTopicsAfterMsecs: ['auto_track_topics_after_msecs', number()],
  notificationLevelWhenReplying: ['notification_level_when_replying', number()],
  newTopicDurationMinutes: ['new_topic_duration_minutes', number()],
  emailPreviousReplies: ['email_previous_replies', number()],
  emailInReplyTo: ['email_in_reply_to', boolean()],
  likeNotificationFrequency: ['like_notification_frequency', number()],
  notifyOnLinkedPosts: ['notify_on_linked_posts', boolean()],
  pushNotificationLevel: ['push_notification_level', string()],
  enableUpcomingChangeAvailableNotifications: [
    'enable_upcoming_change_available_notifications',
    boolean(),
  ],
  includeTl0InDigests: ['include_tl0_in_digests', boolean()],
  themeIds: ['theme_ids', array(unknown())],
  themeKeySeq: ['theme_key_seq', number()],
  allowPrivateMessages: ['allow_private_messages', boolean()],
  enableAllowedPmUsers: ['enable_allowed_pm_users', boolean()],
  homepageId: ['homepage_id', nullable(string())],
  hideProfileAndPresence: ['hide_profile_and_presence', boolean()],
  hideProfile: ['hide_profile', boolean()],
  hidePresence: ['hide_presence', boolean()],
  textSize: ['text_size', string()],
  textSizeSeq: ['text_size_seq', number()],
  titleCountMode: ['title_count_mode', string()],
  timezone: ['timezone', nullable(string())],
  skipNewUserTips: ['skip_new_user_tips', boolean()],
  defaultCalendar: ['default_calendar', optional(string())],
  oldestSearchLogDate: ['oldest_search_log_date', optional(nullable(string()))],
  sidebarLinkToFilteredList: [
    'sidebar_link_to_filtered_list',
    optional(boolean()),
  ],
  sidebarShowCountOfNewItems: [
    'sidebar_show_count_of_new_items',
    optional(boolean()),
  ],
  watchedPrecedenceOverMuted: [
    'watched_precedence_over_muted',
    optional(boolean()),
  ],
  seenPopups: ['seen_popups', optional(nullable(string()))],
  topicsUnreadWhenClosed: ['topics_unread_when_closed', boolean()],
  compositionMode: ['composition_mode', optional(number())],
  interfaceColorMode: ['interface_color_mode', number()],
  showOriginalContent: ['show_original_content', boolean()],
});
